// Generated by scripts/convert-country-pages.mjs from the v1.2 handoff
// (German Pension Refund for Argentine Citizens (2026)). Do not edit copy here — regenerate from the handoff.
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'argentina',
  title: 'German Pension Refund for Argentine Citizens (2026)',
  meta: 'German pension refunds for Argentine citizens. Check the citizenship rule, waiting period, refund amount, certification in Argentina and how to claim.',
  h1: '🇦🇷 German Pension Refund for Argentine Citizens',
  archetype: 'citizenship',
  version: 'v1.2',
  hero: [
    {
      t: 'p',
      x: 'A Working Holiday year that turned into six in Berlin, a research post in Munich, engineering in Stuttgart before Montevideo — the statutory German pension contributions deducted from your salary come back in one sum once you live outside the EU, the UK and India and the 24-month waiting period has run. Argentine citizenship sets no limit on the months; an Italian or Spanish passport held alongside changes everything. Checking your eligibility takes a minute; starting the claim takes less.',
      sp: [],
    },
    {
      t: 'p',
      x: 'We check your eligibility, prepare your application and payment documents, and coordinate your claim with our German partner law firm, which reviews and submits it. Along the way you get plain-English explanations of your pension-office letters, regular updates, and support that continues after the decision. No refund, no service fee.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Argentine citizenship carries no contribution-month limit — 18 German months or 108, the whole refundable balance',
    'No social security agreement with Germany — so no special rule for Argentine citizens; the three general conditions are the test',
    '{{M-04.sentence.hero}}',
    '{{TM-01.sentence.hero}}',
    'No German bank account required · No refund, no service fee · No minimum service fee',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Do I qualify for a German pension refund as an Argentine citizen?',
      blocks: [
        {
          t: 'p',
          x: 'Three conditions, each judged on the day the application is filed, decide a refund before German retirement age: which citizenships you hold, where your home is, and whether 24 full months have passed since your last month of mandatory pension insurance in Germany or another listed country. Argentine citizenship on its own satisfies the citizenship condition; the question to settle first is any second passport.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'Citizenship — every citizenship you hold counts, and the stricter rule decides',
        },
        {
          t: 'p',
          x: "Under German refund law an Argentine citizen belongs to the general group: no ceiling on contribution months and no residence rule of its own. Italian, Spanish or any other EU, EEA, Swiss or British citizenship beside the Argentine one means no refund before German retirement age (one narrow exception aside) — and it makes no difference whether you entered Germany on that passport or never used it. A US, Canadian or Australian citizenship beside the Argentine one brings that country's 60-month limit instead. The Argentine citizenship itself stays — Argentine law gives a native-born Argentine no way to renounce it, and naturalising elsewhere does not end it — so an Argentine by birth who becomes American, Spanish or German holds both.",
          sp: [],
        },
        {
          t: 'p',
          x: 'Citizenship by descent needs the most care. Italian law treats citizenship by descent as existing from birth, recognition merely confirming it, and its 2025 reform narrowed who counts as Italian by descent at all — so an Argentine with Italian grandparents may already be an Italian citizen without ever holding a passport, or may not count as Italian at all. Spanish citizenship by option or naturalisation exists only from the day it is granted and registered, so an application on those routes that is still pending is not yet a citizenship. Only the citizenship legally held on the filing date counts for the German claim, so tell us about every citizenship you hold, may hold or have applied for before anything is filed; one acquired after a valid application does not undo the claim.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'Residence — outside the EU, the UK and India',
        },
        {
          t: 'p',
          x: 'The second condition is your home address on the filing date, and for an Argentine citizen any home outside the EU, the UK and India qualifies — Buenos Aires, Montevideo or Miami, and Zurich or Oslo just as well, since Switzerland, Norway, Iceland and Liechtenstein sit outside the residence rule. Spain is the onward move that needs naming: settle in Madrid or Barcelona and you live in the EU, where the refund stays closed for as long as you stay, whatever passport you hold (the same narrow exception aside) — settle in London and the UK rule does the same. India is closed to everyone but Indian citizens. Home means home; two weeks in Berlin do not make one.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'The 24-month waiting period — counted from your last month of mandatory insurance in Germany or another listed country',
        },
        {
          t: 'p',
          x: "The third condition is a wait of 24 full months (Deutsche Rentenversicherung sets out the 24-month rule here), measured from your last month of mandatory pension insurance — in Germany, another EU state, the UK, Türkiye or an ex-Yugoslav state (Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia) — rather than from the day you deregistered or landed at Ezeiza. Your earliest filing date is the first day of the 25th month after that; filing earlier gains nothing — the period does not shorten, and extra confirmation requests can follow. Paying into Argentina's pension system leaves the clock where it is, and for citizens outside the no-refund group so does mandatory insurance in Switzerland, Norway, Iceland or Liechtenstein. What restarts it is new mandatory insurance inside the listed area — the Argentine case to spell out is Spain: an insured job in Barcelona after Germany makes the 24 months run from that job's last contribution month instead, while local employment in Montevideo after Germany — with no compulsory German pension insurance continuing under a posting from Germany — changes nothing. No deadline applies to a first application; no interest is paid for the years before it. Our waiting-period calculator works out the date from your last contribution month.",
          sp: [
            {
              k: 'a',
              x: 'Deutsche Rentenversicherung sets out the 24-month rule here',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Allgemeine-Informationen/Wissenswertes-zur-Rente/FAQs/International/Erstattung.html',
            },
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'what-we-do',
      kind: 'service',
      h2: 'What we do for you — and what it costs',
      blocks: [
        {
          t: 'p',
          x: 'Before anything is filed. You provide your details, documents and signatures; we do the rest of the preparation. We check your eligibility, obtain and review the relevant DRV account information during the managed process where required, prepare your refund application and payment documents, identify the recommended first pension office from your record and coordinate the claim with our German partner law firm, which reviews and submits it.',
          sp: [
            {
              k: 'b',
              x: 'Before anything is filed.',
            },
          ],
        },
        {
          t: 'p',
          x: 'While the pension office works. Pension-office letters for your claim are received at a German address, scanned to you and explained in plain English. After your claim is submitted, you receive an update at least every four weeks — even when the update is that no pension-office response has arrived. If there is still no decision six months after submission, updates come at least every two weeks, whether or not a formal complaint has been filed. Material requests and developments are communicated sooner. If we are still waiting for a decision three months after submission, we contact the pension office to check where the application stands. We keep track of known response and objection deadlines within the agreed scope; if a letter reaches you directly, forward it to us straight away with the date you received it — only deadlines known to us or our partner law firm can be protected.',
          sp: [
            {
              k: 'b',
              x: 'While the pension office works.',
            },
          ],
        },
        {
          t: 'p',
          x: "After the decision. Our managed service includes checking the pension office's decision against your record and evidence. If contribution periods you can evidence — payslips, for example — are missing from the refund statement, a straightforward objection is included in the service fee: we draft it from our standard template and your evidence, and it goes to the pension office; no extra cost. If the disagreement is a legal question — for example, the office rejects the refund on a legal ground you could not be expected to assess yourself — objection representation is separate work by our partner law firm, agreed directly between you and the firm at its own cost, outside the service scope. If an approved refund does not arrive, we follow it up within the managed scope with the pension office and Renten Service until the payment is resolved.",
          sp: [
            {
              k: 'b',
              x: 'After the decision.',
            },
          ],
        },
        {
          t: 'p',
          x: "Our fee is 9.75% of the refunded amount, capped at €2,500 including VAT, with no upfront service fee and no minimum service fee. No refund, no service fee. The fee covers the agreed managed administrative scope, including our partner law firm's support within that scope. We do not provide legal services, advice or representation; separate representation in an objection, appeal or court proceeding is not included automatically. German deregistration is available as an optional €50 add-on including VAT, payable with the service fee after your refund reaches escrow — and if your German pension insurance number has gone missing, we can help identify or recover it.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
        {
          t: 'p',
          x: '{{TM-01.sentence}} {{M-12.sentence}} Individual processing times vary — see the full data and methodology. Processing and payment dates depend on the responsible pension office and the payment route, so a specific date cannot be guaranteed; the process is designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      id: 'what-you-need-to-start',
      kind: 'intake',
      h2: 'What you need to start',
      blocks: [
        {
          t: 'p',
          x: 'To get started, upload a copy of your passport, a payslip from your time in Germany and your deregistration confirmation (Abmeldebestätigung). Your account guides you through the questions and documents. Missing your German pension number? We help recover it. Not deregistered yet? We offer deregistration assistance for €50 including VAT. If your claim needs additional documents or signed originals by post, we explain exactly what to provide.',
          sp: [],
        },
      ],
    },
    {
      id: 'is-there-a-60-month-limit',
      kind: 'sixty-month',
      h2: 'Is there a 60-month limit for Argentine citizens — and does the missing agreement matter?',
      blocks: [
        {
          t: 'p',
          x: "There is none, and the reason is the very agreement Argentina lacks. Citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay — and Japanese citizens while they live in Japan — are held to 59 German months or fewer for a refund before retirement age, counting contribution months plus the German months credited to the account (child-raising periods, for instance, or months on unemployment benefit, though not every line of the insurance record counts) and nothing from any other country. The limit exists because each of those countries' social security agreements lets its citizens pay voluntary German contributions, and a person who could pay in — even one who never does — cannot take the money out early. Argentina and Germany have no agreement at all, so an Argentine citizen who holds no other citizenship and lives outside the EU, the UK and India has no such right, and after the 24-month waiting period German law refunds the employee share. The limit follows the passport, not the address: living in São Paulo or Montevideo does not put someone holding Argentine citizenship alone under the 60-month rule that Brazil's and Uruguay's agreements bring for their own citizens. What 60 German months add is an alternative: the five-year qualifying period (allgemeine Wartezeit) is then met and a German old-age pension at retirement age has been earned as well, payable in Argentina — the refund replaces it, after which the refunded months never count towards a pension again.",
          sp: [
            {
              k: 'a',
              x: 'no agreement at all',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Sozialversicherungsabkommen/sozialversicherungsabkommen_detailseite.html',
            },
          ],
        },
      ],
    },
    {
      id: 'journeys',
      kind: 'journeys',
      h2: 'Three illustrative journeys — Buenos Aires, Rosario, Montevideo',
      blocks: [
        {
          t: 'note',
          x: 'Worked examples, not client cases.',
        },
        {
          t: 'p',
          x: 'The developer whose Working Holiday became six years. A Working Holiday year in Berlin from October 2019 to September 2020 with insured jobs in seven of its twelve months at €2,600 gross, then a local contract from October 2020 to September 2025 — 60 months at €4,900 gross, statutory pension contributions paid throughout — and home to Buenos Aires in October 2025. The five uninsured travelling months carry nothing; the other 67 count, Argentine citizenship setting no ceiling: €241.80 a month for the seven and €455.70 a month for the sixty, roughly €29,000 in refundable employee contributions; 1 October 2027, the first day of the 25th month after September 2025, is the earliest application date. With more than five insured years he has also earned a German old-age pension, which the refund would replace — worth comparing before he decides.',
          sp: [
            {
              k: 'b',
              x: 'The developer whose Working Holiday became six years.',
            },
          ],
        },
        {
          t: 'p',
          x: "The couple who went home to Rosario. Five years in Hamburg, January 2020 to December 2024, 60 months each at €4,000 gross, then Rosario from January 2025. She holds Argentine citizenship alone: no limit, €372 a month, roughly €22,300 in refundable employee contributions, claimable from 1 January 2027 — and, at exactly 60 months, a German old-age pension at retirement age has been earned as well, which the refund would replace. He came to Germany on the Italian passport his grandfather's birth in Calabria gave him, recognised years before the 2025 reform: the Italian citizenship, not the Argentine one, decides his case, and it means no refund before German retirement age (one narrow exception aside), even though the passport now sits in a drawer in Rosario.",
          sp: [
            {
              k: 'b',
              x: 'The couple who went home to Rosario.',
            },
          ],
        },
        {
          t: 'p',
          x: "The engineer who moved on to Montevideo. Stuttgart from January 2022 to June 2025 — 42 months at €4,300 gross — then Montevideo from July 2025. Uruguay lies outside the EU, the UK and India, and living there does not put her under the 60-month rule that Uruguay's agreement brings for Uruguayan citizens: her Argentine passport sets the rule, no limit. €399.90 a month, roughly €16,800 in refundable employee contributions, claimable from 1 July 2027; on her German record alone, 42 months fall short of the five-year qualifying period, so no earned German pension stands against the refund — unless periods in an agreement state such as Uruguay could one day be added, a comparison to make before filing. Her Uruguayan address may steer the claim to a liaison office — our guide says which.",
          sp: [
            {
              k: 'b',
              x: 'The engineer who moved on to Montevideo.',
            },
          ],
        },
        {
          t: 'p',
          x: 'Your own months go through the free refund calculator in a minute.',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'which-of-your-years-in-germany',
      kind: 'years',
      h2: 'Which of your years in Germany actually paid pension contributions?',
      blocks: [
        {
          t: 'p',
          x: 'Before a single month is counted, each stretch of your German years answers one question: was statutory pension insurance paid for it?',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: "Employment based in Germany under German social insurance — the normal result of a German employment contract, whether on a Blue Card, a skilled-worker permit or a Working Holiday visa — brings pension insurance from the start: every month counts and the employee share is refundable. Lower pay is the exception: for months in employment covered by the Übergangsbereich rules for the relevant year (in 2026, regular pay between €603.01 and €2,000 a month) the refund is half of the total pension contributions paid for them — 9.3% of gross pay is the wrong sum for those months, so a part-time job at €1,500 a month in 2026 is insured and every month counts, but its refund follows the half-of-total rule (for years before 2023 the band's upper limit was lower, so the year decides).",
              sp: [
                {
                  k: 'b',
                  x: 'Employment based in Germany under German social insurance',
                },
              ],
            },
            {
              x: "Working Holiday months are ordinary employment months once an employer put you on its payroll — apart from a short seasonal job registered as insurance-free short-term employment; the visa changes nothing about the insurance. Minijobs turn on one choice: if the small employee top-up (the default since 2013) was kept, the months count and the top-up is refundable; if it was waived, only the employer's flat-rate contributions were paid: nothing of yours is in the record and those months neither block nor restart the waiting period, though they can still earn partial credit toward the five-year qualifying period.",
              sp: [
                {
                  k: 'b',
                  x: 'Working Holiday months',
                },
                {
                  k: 'b',
                  x: 'Minijobs',
                },
              ],
            },
            {
              x: 'Werkstudent jobs are pension-insured although students pay no health, care or unemployment insurance through that employment; above the minijob limit the months count and the contributions come back. Ausbildung contracts are pension-insured too, and the Übergangsbereich rules are not applied to training pay. (Only where training pay was €325 a month or less did the employer bear the whole contribution; those months count, but hold no employee share.)',
              sp: [
                {
                  k: 'b',
                  x: 'Werkstudent jobs',
                },
                {
                  k: 'b',
                  x: 'Ausbildung contracts',
                },
              ],
            },
            {
              x: 'A scholarship or stipend without an employment contract — a DAAD or CONICET-funded stay, say — carries no pension insurance, whereas a doctoral or postdoc position on an employment contract is insured like any job. Freelance or self-employed work usually falls outside mandatory insurance, and where voluntary or compulsory self-employed contributions were paid, the refund is half of them.',
              sp: [
                {
                  k: 'b',
                  x: 'A scholarship or stipend without an employment contract',
                },
                {
                  k: 'b',
                  x: 'Freelance or self-employed work',
                },
              ],
            },
            {
              x: 'Sent to Germany by an Argentine employer for a period fixed in advance, with the employment relationship kept in Argentina? Then the Einstrahlung rule may have kept you outside German insurance — with no agreement between Argentina and Germany, German law alone decides — and no German contributions exist for those months.',
              sp: [
                {
                  k: 'b',
                  x: 'Sent to Germany by an Argentine employer',
                },
              ],
            },
          ],
        },
        {
          t: 'p',
          x: 'Memory and old payslips produce an estimate; the months actually refunded are those in the official insurance record (Versicherungsverlauf), which we obtain and review in a managed claim where required.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-comes-back-and-what',
      kind: 'amount',
      h2: 'How much comes back — and what about tax in Argentina?',
      blocks: [
        {
          t: 'p',
          x: "The refund is your own share of the contributions — 9.3% of gross pay since 2018, charged up to the monthly ceiling (Beitragsbemessungsgrenze: €8,450 in 2026, €8,050 in 2025) — and normally the whole of it; the employer's share stays in the system, and pay above the ceiling was never insured. The main exceptions change the calculation: voluntary contributions and the compulsory contributions of self-employed people are refunded at 50%; months in employment covered by the Übergangsbereich rules for the relevant year at half of the total contributions paid for them; and where Deutsche Rentenversicherung once funded a benefit for you — a rehabilitation programme, say — only the contributions paid after it are refundable, while the completed refund still closes the whole record. These are checked before anything is filed. The legal basis is § 210 SGB VI.",
          sp: [
            {
              k: 'a',
              x: '§ 210 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__210.html',
            },
          ],
        },
        {
          t: 'p',
          x: '{{M-04.sentence}} Our refund calculator applies the actual statutory employee contribution rate and monthly ceiling (Beitragsbemessungsgrenze) of every year back to 1975 — including Deutsche-Mark periods and East/West differences — rather than a flat percentage.',
          sp: [
            {
              k: 'a',
              x: 'refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
        {
          t: 'p',
          x: 'On the German side the refund is paid out without income tax; the exemption is written into German law and confirmed by the Federal Fiscal Court. Where you are tax-resident — Argentina, say — is a different question: Argentine residents are taxed on their worldwide income, and whether a German contribution refund falls into that net in your case is for a local adviser to say — we do not provide individual tax, pension or legal advice.',
          sp: [],
        },
      ],
    },
    {
      id: 'which-german-pension-office-handles-an',
      kind: 'office',
      h2: "Which German pension office handles an Argentine citizen's claim?",
      blocks: [
        {
          t: 'p',
          x: 'No German pension office serves as liaison office (Verbindungsstelle) for Argentina, so the office follows from your insurance record, any second citizenship and your country of residence, in that order: DRV Knappschaft-Bahn-See if it was ever your carrier; otherwise DRV Bund if it was the last carrier of your account; otherwise the liaison office of a second citizenship (DRV Nord for a US or Canadian citizen, wherever they live); otherwise the liaison office for your country of residence where one exists — DRV Nord for the USA and Canada, DRV Oldenburg-Bremen for Australia, DRV Braunschweig-Hannover for Japan, South Korea and the Philippines, and the offices for agreement states such as Brazil, Chile and Uruguay, listed in our guide; and where none exists — an Argentine citizen living in Argentina, say — the regional office that holds the account. A claim posted to the wrong office is forwarded, filing date intact, weeks lost — our guide to the responsible pension office has the full decision tree and the office finder. In a managed claim, our German partner law firm files the claim with the recommended office we identify from your record.',
          sp: [
            {
              k: 'a',
              x: 'our guide to the responsible pension office',
              href: 'https://www.germanypensionrefund.com/post/which-german-pension-office-handles-your-claim',
            },
          ],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Getting paid in Argentina — or wherever you live',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account is required. In a claim we manage, your refund is paid through the escrow account operated by our German partner law firm; after the agreed service fee is deducted, the remaining balance is transferred to the bank account you nominate — a third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent, so the route for a transfer to Argentina or elsewhere is checked shortly before the money moves. Eligibility and payment route are separate: a valid refund may require an account in a permitted country if transfers to the residence country are restricted.',
          sp: [],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Digital for most clients — certified signatures in Argentina',
      blocks: [
        {
          t: 'p',
          x: "Most clients can complete their entire part of the process digitally: you submit your details and sign online. Every client has their identity and signature confirmed using their passport or an accepted equivalent; depending on the route, that confirmation can be completed digitally or, where a certified signature is needed, in person. Where one is needed, we prepare the document and you have it certified by one certifier — no combination of certifiers is ever required. In Argentina the route to try first, and usually the cheaper one, is the German Embassy in Buenos Aires: it certifies signatures on documents for use with a German authority whatever your nationality, only in person and only by appointment booked through its online system in the category for other legal and consular matters — bring your passport or DNI (the Embassy's signature-certification page). Germany also has honorary consuls in Córdoba, Mendoza, Salta, Bariloche and other cities (directory); Mendoza's lists signature certification in civil-law matters — ask before you travel. The alternative is an escribano público or a bank whose certification the responsible pension office accepts for that particular document — the document exists in a Spanish version, so no translation stands in the way. Required local certification, notary or translation costs are borne by the client. If DRV Oldenburg-Bremen is responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — for an Argentine citizen that office is the usual result of living in Australia, unless Knappschaft-Bahn-See ever insured you or DRV Bund was the last carrier of your account.",
          sp: [
            {
              k: 'a',
              x: "the Embassy's signature-certification page",
              href: 'https://buenos-aires.diplo.de/ar-de/service/2006786-2006786',
            },
            {
              k: 'a',
              x: 'directory',
              href: 'https://buenos-aires.diplo.de/ar-de/ueber-uns/honorarkonsuln/1801030-1801030',
            },
          ],
        },
        {
          t: 'p',
          x: 'You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. Self-filing from Argentina means paper — form V0901 in the post, since ordinary email is not accepted for identity reasons and fax has been discontinued. In a self-filed claim, the official application form provides for your personal data to be certified on the form itself, so the application travels to the certifying body — the Embassy, an honorary consul that offers the service, or an escribano or bank where its certification is accepted for that form. In a managed claim, the analog step is a single page we prepare for you. The form is walked through section by section in our V0901 guide.',
          sp: [
            {
              k: 'a',
              x: 'V0901 guide',
              href: 'https://www.germanypensionrefund.com/v0901-pension-refund-form-english',
            },
          ],
        },
      ],
    },
    {
      id: 'living-in-argentina-with-another-citizenship',
      kind: 'dual-citizenship',
      h2: 'Living in Argentina with another citizenship?',
      blocks: [
        {
          t: 'p',
          x: 'For anyone living in Argentina on another passport the address side is settled — Argentina lies outside the EU, the UK and India — and contributions to the Argentine pension system have no bearing on a German refund: they never block, restart or count, whatever your citizenship. No limit for most nationalities; the 60-month limit, counting German months only, for citizens of the eleven countries named above — US, Canadian, Australian, Indian, Korean and Filipino citizens among them; no refund before German retirement age for Italian, Spanish, German and other EU, EEA, Swiss and British citizens (one narrow exception aside). Our guide for citizens of other countries lists the rule for every nationality.',
          sp: [
            {
              k: 'a',
              x: 'US',
              href: 'https://www.germanypensionrefund.com/usa',
            },
            {
              k: 'a',
              x: 'Canadian',
              href: 'https://www.germanypensionrefund.com/canada',
            },
            {
              k: 'a',
              x: 'Australian',
              href: 'https://www.germanypensionrefund.com/australia',
            },
            {
              k: 'a',
              x: 'Indian',
              href: 'https://www.germanypensionrefund.com/india',
            },
            {
              k: 'a',
              x: 'Korean',
              href: 'https://www.germanypensionrefund.com/southkorea',
            },
            {
              k: 'a',
              x: 'Filipino',
              href: 'https://www.germanypensionrefund.com/thephilippines',
            },
            {
              k: 'a',
              x: 'Our guide for citizens of other countries',
              href: 'https://www.germanypensionrefund.com/other-countries',
            },
          ],
        },
      ],
    },
    {
      id: 'a-family-members-german-contributions',
      kind: 'family',
      h2: "A family member's German contributions",
      blocks: [
        {
          t: 'p',
          x: "Where a spouse, registered partner or parent has died with German contributions on record, the closest family — the surviving spouse or registered partner and, in the cases the law provides for, the children — can be entitled to a refund of those contributions where no German survivor's pension is payable because the deceased had not met the five-year qualifying period (allgemeine Wartezeit). Checking that period means looking beyond the German months — at foreign periods that count toward it (periods under Argentina's pension system do not — there is no agreement) and at the rules that treat it as met in special cases. Survivors need not wait 24 months, but their claim can become time-barred four years after the end of the year of death. Where the qualifying period was met, a German survivor's pension may be payable instead — worldwide, Argentina included. Our German widow's pension guide and the survivors chapter of the complete guide explain who can claim, in which order and with what evidence.",
          sp: [
            {
              k: 'a',
              x: "Our German widow's pension guide",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
  ],
  faq: [
    {
      q: 'Do Argentine citizens have a limit on refundable German months?',
      a: 'No. Citizens of eleven countries whose social security agreements open voluntary German insurance to them — the USA, Canada, Australia, India, Brazil and Uruguay among them — and Japanese citizens while they live in Japan are capped at 59 German months. Argentina has no such agreement, so Argentine citizenship is uncapped; from 60 German months you have also earned a German old-age pension payable at German retirement age, and the refund replaces it. A second citizenship adds its own rule, and the stricter of the two governs.',
    },
    {
      q: 'My grandparents were Italian or Spanish — does a passport through them affect my refund?',
      a: "It does if you hold the citizenship: Italian, Spanish or any other EU, EEA, Swiss or British citizenship blocks the refund before German retirement age by itself, however it was acquired and whether or not a passport was ever issued (one narrow statutory exception aside). Italian law treats citizenship by descent as existing from birth, recognition merely confirming it, and since 2025 it deems people born abroad who hold another citizenship never to have been Italian unless one of its exceptions applies — the Italian Foreign Ministry's official explanation sets them out. Spanish citizenship by option or naturalisation exists only once granted and registered, so a pending application on those routes is not yet a citizenship. Settle your legal status before you rely on the refund route, and name every citizenship you hold or may hold when you talk to us — we do not provide individual legal advice.",
    },
    {
      q: 'I have become a US, Canadian or German citizen — what changes?',
      a: "The new citizenship's rule binds you from the day you hold it, and your Argentine citizenship stays — Argentine law gives a native-born Argentine no way to give it up, and naturalising elsewhere does not end it — so both are counted and the stricter rule decides. US or Canadian citizenship brings the 60-month limit — at most 59 German months, contribution months plus credited periods such as child-raising or unemployment-benefit months, nothing foreign added; German, EU, EEA, Swiss or British citizenship brings the no-refund-before-retirement-age rule (one narrow exception aside). Everything is measured on the filing date, so a naturalisation completed after a valid application leaves the claim standing and one still pending is not yet a citizenship. We do not provide individual legal advice.",
    },
    {
      q: 'Do my ANSES contributions affect the German refund?',
      a: "No. Argentina's pension system and German pension insurance are separate, so what you pay into the Sistema Integrado Previsional Argentino neither blocks the German refund nor restarts the 24-month wait nor adds to any German month total. Whether the refund is taxable in Argentina is a separate question for a local adviser.",
    },
    {
      q: 'Do I need an escribano to certify my signature?',
      a: 'Not necessarily. Most clients can complete their part of the process digitally; where a certified signature is needed, one certifier is enough — the German Embassy in Buenos Aires by online appointment (the route to try first, usually the cheaper one; it certifies whatever your nationality) or an honorary consul that offers the service, or an escribano público or a bank where the responsible pension office accepts its certification for the document; the document exists in a Spanish version, so an escribano needs no translation.',
    },
    {
      q: 'I came on a Working Holiday visa and then stayed on a contract — which months count?',
      a: "Every month in which an employer paid German pension contributions for you counts, whatever the visa said: a Working Holiday job above the minijob limit is insured like any other employment unless the employer registered it as insurance-free short-term employment, and the contract months that followed are insured from their first month. Refundable money exists only for months with an employee share: travelling months without a job, a scholarship without an employment contract and a minijob whose employee top-up was waived produce none — though the waived-top-up minijob's employer contributions can still earn partial credit toward the five-year qualifying period, which matters for the pension-or-refund comparison, not for the refund amount. Which months were which is a question the insurance record answers; in a managed claim we obtain and review it where required.",
    },
  ],
  close: [
    {
      t: 'p',
      x: 'For the eligibility tables, month counting, survivors, retirement age, forms and objections in full, read the complete 2026 guide. Our eligibility check walks through citizenship, residence and the 60-month and 24-month rules — a preliminary indication in under a minute. Starting your claim takes less than one minute — start here →',
      sp: [
        {
          k: 'a',
          x: 'the complete 2026 guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'a',
          x: 'eligibility check',
          href: 'https://www.germanypensionrefund.com/refund-calculator',
        },
        {
          k: 'a',
          x: 'start here →',
          href: 'https://www.germanypensionrefund.com/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may also apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
  ],
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'what-we-do': 'what-we-do',
    journeys: 'journeys',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Argentine Citizens',
    audienceType: 'Argentine citizens who worked in Germany',
    description:
      'Managed German state pension contribution refunds for Argentine citizens who worked in Germany. Argentine citizenship carries no contribution-month limit; a refund before German retirement age needs residence outside the EU, the UK and India, a 24-month waiting period after the last month of mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state, and no German, EU, EEA, Swiss or British citizenship held alongside (one narrow statutory exception aside) — any other citizenship held alongside brings its own rule, such as a 60-month limit. No upfront or minimum service fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. {{M-04.sentence.schema}}',
  },
};

export default page;
