// Generated by scripts/convert-country-pages.mjs from the 26 August 2026 handoff
// (German Pension Refund for Australian Citizens (2026)). Do not edit copy here — regenerate from the handoff.
// Copy as delivered in the August 2026 handoff — it carries the older service
// wording; the client will send refreshed copy later (regenerate from it then).
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'australia',
  title: 'German Pension Refund for Australian Citizens (2026)',
  meta: 'Australian citizens with under 60 German contribution months can reclaim their contributions. Paper? One envelope, prepared by us. No refund, no fee.',
  h1: '🇦🇺 German Pension Refund for Australian Citizens',
  archetype: 'august',
  version: '26 August 2026',
  hero: [
    {
      t: 'p',
      x: "The German pension system doesn't lose track of money — not even across ten time zones. For Australian citizens, eligibility comes down to three things: fewer than 60 German contribution months, at least 24 months since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country — and a home outside the EU and the UK. Paying superannuation changes nothing. And the famous German paperwork? For some Australian cases it exists — as exactly one envelope, prepared by us.",
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Refunds across all nationalities averaged {{M-04.meanShort}} in our latest quarterly calculation — from {{M-17.range}}',
    'No German bank account required',
    '{{TM-01.sentence.hero}}',
    "Digital for you — when paper is needed, it's one envelope we prepare",
    'Only pay if successful — no refund, no fee',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Do I Qualify for a German Pension Refund as an Australian Citizen?',
      blocks: [
        {
          t: 'p',
          x: 'The Social Security Agreement between Germany and Australia sets the frame, and it is short: under 60 German contribution months (months credited for unemployment benefits or child-raising periods count toward the total), a gap of 24 months since the last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country, and a residence outside the EU and the UK.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Living in Australia never blocks your claim, and neither does paying superannuation — your super and the German pension system simply never meet. (One global quirk to know: living in India blocks refunds for anyone without Indian citizenship. Relevant only if you relocate there.)',
          sp: [],
        },
      ],
    },
    {
      id: 'the-60-month-rule-for-australian',
      kind: 'sixty-month',
      h2: 'The 60-month rule for Australian citizens',
      blocks: [
        {
          t: 'p',
          x: 'Any calendar month with at least one day of paid contributions counts as a full month. Periods of employment, unemployment benefits and parental leave all count toward the 60 months. Stay under the line and the refund stays available; cross it, and the money converts instead into a German old-age pension at retirement age — payable worldwide, Australia included.',
          sp: [],
        },
        {
          t: 'cta',
          items: [
            {
              label: 'Free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: "The one envelope — Australia's paper exception",
      blocks: [
        {
          t: 'p',
          x: "Many Australian refunds are routed to one specific office: Deutsche Rentenversicherung Oldenburg-Bremen, Australia's liaison office among Germany's regional pension carriers. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule. We prepare both documents completely; you sign, one envelope travels (postage is on you), and the rest of your journey stays on screen.",
          sp: [],
        },
        {
          t: 'p',
          x: 'Not every Australian case lands there, though. Accounts held by DRV Bund or Knappschaft-Bahn-See stay with those carriers, and those clients keep a fully online journey on their side. A German pension insurance number beginning with 28 points to Oldenburg-Bremen — but treat it as an indicator, not a verdict, because the responsible carrier can change over a working life. We identify the recommended office as part of every managed claim.',
          sp: [],
        },
      ],
    },
    {
      id: 'when-can-you-file',
      kind: 'waiting-period',
      h2: 'When can you file?',
      blocks: [
        {
          t: 'p',
          x: 'The 24 full calendar months are measured from your last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country — meaning the final month of employment or credited benefits; the deregistration date is irrelevant. If new mandatory insurance in one of those countries starts before you file, the 24 months begin again from its end. Eligibility is checked at the date of your application: you can take up work in the EU again the day after submitting, and a later return does not undo a claim that was valid when filed.',
          sp: [],
        },
        {
          t: 'p',
          x: "Worth stating plainly: the pension office can verify EU and UK insurance periods. A refund obtained while actually living or insured in the EU or UK can be withdrawn retrospectively, reclaimed and enforced. Unsure where you stand? That's what our first, free check is for.",
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-can-you-get-back',
      kind: 'amount',
      h2: 'How much can you get back?',
      blocks: [
        {
          t: 'p',
          x: "Across our retained completed paid cases — all nationalities — refunds averaged {{M-04.mean}}, with a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}), and completed refunds in those records run from {{M-17.range}}. For the local picture: across our retained completed paid cases for clients living in Australia, refunds averaged {{M-09.mean}}, with a median of {{M-09.median}} ({{M-09.period}} calculation) — a residence cohort, not an average for Australian citizens as such. What's refundable:",
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: 'the full 100% of the pension contributions deducted from your pay as an employee in Germany;',
              sp: [],
            },
            {
              x: 'half (50%) of any voluntary contributions — freelance years, for example;',
              sp: [],
            },
            {
              x: 'plus or minus any pension-equalization amounts from a divorce before a German court.',
              sp: [],
            },
          ],
        },
        {
          t: 'p',
          x: 'Since 2018, pension insurance contributions have been set at 9.3% of your gross earnings, up to a monthly income threshold (Beitragsbemessungsgrenze) — €8,450 in 2026 (2025: €8,050). Earnings above the threshold carried no contributions, so there is nothing to refund on them.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Get your own estimate with the free refund calculator.',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'what-does-the-service-cost',
      kind: 'cost',
      h2: 'What does the service cost?',
      blocks: [
        {
          t: 'p',
          x: "Our success fee is 9.75% of the refunded amount and stops at €2,500 no matter how large the refund — VAT is included in both numbers, and the agreed administrative scope covers our partner law firm's support. Separate representation in an objection, appeal or court proceeding is not included automatically. There are no extra charges hiding behind that sentence: you pay nothing upfront, nothing along the way, and nothing at all unless your refund actually arrives.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
      ],
    },
    {
      id: 'what-you-need-to-apply',
      kind: 'intake',
      h2: 'What you need to apply',
      blocks: [
        {
          t: 'p',
          x: "A current passport and your German pension number (Versicherungsnummer) do most of the work — this guide shows where the number is found. Add your rough German employment history (dates and employers), the address and bank details for the payout, and — if the move home didn't swallow it — your deregistration certificate (Abmeldung). Lost the number? We can help recover your pension number, and German deregistration is available as an optional €50 add-on (including VAT). The insurance record itself isn't your job: we obtain and review the relevant account information during the managed process where required.",
          sp: [
            {
              k: 'a',
              x: 'this guide',
              href: 'https://www.germanypensionrefund.com/post/german-social-security-number',
            },
          ],
        },
      ],
    },
    {
      id: 'how-much-of-the-process-is',
      kind: 'certification',
      h2: 'How much of the process is online?',
      blocks: [
        {
          t: 'p',
          x: 'Nearly all of it, for nearly everyone: details and signatures are handled online, and we run the pension-office correspondence within the agreed scope. Two offline moments can occur. The first applies to everyone — a short Certificate of Life and Nationality we prepare, which must be confirmed by a notary or another authority accepted by the responsible pension office; online notarization is often accepted, and any local notary or certification cost is borne by the client. The second is the Oldenburg-Bremen envelope described above — and only when that office is responsible for your refund.',
          sp: [],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Do I need a German bank account?',
      blocks: [
        {
          t: 'p',
          x: 'No. Your refund is paid through the escrow account operated by our German partner law firm; after the agreed fee is deducted, the remaining balance is transferred to the bank account you nominate — Australian accounts included. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-long-before-the-refund-lands',
      kind: 'timing',
      h2: 'How long before the refund lands?',
      blocks: [
        {
          t: 'p',
          x: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission, the median at {{M-19.medianDaysRounded}} days — see the full data and methodology. Individual processing times vary. What we control, we optimize: complete files, the recommended office identified upfront, professional filing and follow-up — a process designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
        {
          t: 'p',
          x: "What we don't control is the office's own queue. Departmental workloads and internal checks stretch some cases; {{M-20.pct}} of our latest {{M-12.total}} completed refunds reached escrow within six months, and the remainder simply needed more patience — the entitlement itself never shrinks. From the seventh calendar month after a complete application, German law can provide 4% annual interest, which makes Germany rare among bureaucracies: the delay can come with compensation.",
          sp: [],
        },
        {
          t: 'p',
          x: "Meanwhile you're not left refreshing your inbox: known response deadlines stay monitored within the managed scope, and a status update reaches you at least every four weeks — sometimes reporting simply that the office is still working. If a decision ever failed to arrive within six months, an inactivity action (Untätigkeitsklage) can become available as a case-dependent last resort; in our operating history, none has yet been required.",
          sp: [],
        },
      ],
    },
    {
      id: 'a-refund-with-german-contributions-left',
      kind: 'family',
      h2: 'A refund with German contributions left behind by a spouse or parent',
      blocks: [
        {
          t: 'p',
          x: "Contributions don't expire with the person who paid them. Where someone died before reaching the five-year qualifying period on their German record, the contributions can be claimed back by the family — the surviving spouse or registered partner first, then the children. There is no waiting period for this claim, but there is a hard deadline: four years after the end of the year of death. A record of five years or more works differently — no refund, but a German widow's or widower's pension may be paid instead, to Australia as to anywhere. How each path works: German widow's pension guide → · survivors chapter of the complete guide →",
          sp: [
            {
              k: 'a',
              x: "German widow's pension guide →",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide →',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
        {
          t: 'reviews',
        },
      ],
    },
  ],
  faq: [],
  schemaFaq: [
    {
      q: 'Do Australians have to mail original documents to Germany?',
      a: "Sometimes — and then it is one envelope. When DRV Oldenburg-Bremen, Australia's liaison office among the regional carriers, is responsible for a refund, we prepare the power of attorney and payment declaration and the client sends us the signed originals. Accounts held by DRV Bund or Knappschaft-Bahn-See stay fully online on the client's side. A pension insurance number beginning with 28 points to Oldenburg-Bremen, but the responsible carrier can change, so it is an indicator rather than a guarantee.",
    },
    {
      q: 'Do I qualify for a German pension refund as an Australian citizen?',
      a: 'You qualify with fewer than 60 German contribution months, at least 24 months since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country, and residence outside the EU and the UK. Living in Australia never blocks the claim, and superannuation has no effect on eligibility.',
    },
    {
      q: 'How much can you get back from the German pension system?',
      a: 'Across our retained completed paid cases — all nationalities — refunds averaged {{M-04.mean}}, with a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}); completed refunds in those records run from {{M-17.range}}. Across our retained completed paid cases for clients living in Australia, refunds averaged {{M-09.mean}}, with a median of {{M-09.median}} ({{M-09.period}} calculation). The refund returns 100% of the contributions withheld from your salary and 50% of voluntary contributions.',
    },
    {
      q: 'How much does the service cost?',
      a: "A success fee of 9.75% of the refunded amount, capped at €2,500 including VAT — nothing upfront and no minimum fee. It covers the agreed managed administrative scope, including our partner law firm's support within that scope; separate representation in an objection, appeal or court proceeding is not included automatically. No refund, no fee.",
    },
    {
      q: 'Do I need a German bank account?',
      a: 'No. Your refund is paid through the escrow account operated by our German partner law firm; after the agreed fee is deducted, the remaining balance is transferred to the bank account you nominate — Australian accounts included. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
    },
    {
      q: 'How long does a German pension refund take for Australians?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission, with the median at {{M-19.medianDaysRounded}} days. In the same {{M-12.total}} completed refunds, {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  close: [
    {
      t: 'p',
      x: "Ten time zones haven't cost you a cent of it. Starting your claim takes less than one minute — one envelope at most, no fee unless the refund arrives.",
      sp: [],
    },
    {
      t: 'cta',
      items: [
        {
          label: 'Make Your Claim Today',
          href: 'https://www.germanypensionrefund.com/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Every rule, form and step, in longform: How to Claim a German Pension Refund: Complete 2026 Guide',
      sp: [
        {
          k: 'a',
          x: 'How to Claim a German Pension Refund: Complete 2026 Guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
      ],
    },
  ],
  closeTitle: 'Claim Your Pension Refund Today',
  closeDisclaimer: false,
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
  },
  schema: {
    serviceName: 'German Pension Refund for Australian Citizens',
    audienceType: 'Australian citizens who worked in Germany',
    description:
      'Managed handling of German state pension contribution refunds for Australian citizens who worked in Germany. No upfront payment and no minimum fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. Across our retained completed paid cases for clients living in Australia, refunds averaged {{M-09.mean}}, with a median of {{M-09.median}} ({{M-09.period}} calculation).',
  },
};

export default page;
