// Generated by scripts/convert-country-pages.mjs from the 26 August 2026 handoff
// (German Pension Refund for Brazilian Citizens (2026)). Do not edit copy here — regenerate from the handoff.
// Copy as delivered in the August 2026 handoff — it carries the older service
// wording; the client will send refreshed copy later (regenerate from it then).
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'brazil',
  title: 'German Pension Refund for Brazilian Citizens (2026)',
  meta: 'Brazilian-only citizens with under 60 German contribution months can claim their contributions back. Careful: an EU second passport blocks it.',
  h1: '🇧🇷 German Pension Refund for Brazilian Citizens',
  archetype: 'august',
  version: '26 August 2026',
  hero: [
    {
      t: 'p',
      x: "As a Brazilian citizen, you qualify for a German pension refund with fewer than 60 German contribution months, a 24-month gap since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country, and a residence outside the EU, the UK and India. One passport matters more than any other rule: this applies if you're a Brazilian-only citizen — an EU passport, even unused, closes the route.",
      sp: [],
    },
    {
      t: 'p',
      x: 'We have handled international German pension-refund matters since 2015 — from Berlin, online, in plain language.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Our retained completed paid cases across all nationalities show an average refund of {{M-04.meanShort}}',
    'Completed refunds on record: from {{M-17.range}}',
    'Pay nothing unless your refund is successful',
    "No German bank account required — payout via our German partner law firm's escrow account",
    '{{TM-01.sentence.hero}}',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Can Brazilians Really Claim a Refund?',
      blocks: [
        {
          t: 'p',
          x: 'Most Brazilians who worked in Germany can reclaim their pension contributions if all of these hold:',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: "You're a Brazilian citizen — and not a dual citizen of an EU country (see the trap below)",
              sp: [],
            },
            {
              x: 'You have fewer than 60 German contribution months',
              sp: [],
            },
            {
              x: 'At least 24 months have passed since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country',
              sp: [],
            },
            {
              x: 'You live outside the European Union, the United Kingdom and India (India is the odd one on that list — residence there blocks every nationality except Indian citizens)',
              sp: [],
            },
          ],
        },
        {
          t: 'p',
          x: 'Living in Brazil never blocks the claim — and neither do your INSS contributions. Unsure where you stand? Our free eligibility check gives you a preliminary indication — no charge, no obligation.',
          sp: [],
        },
        {
          t: 'cta',
          items: [
            {
              label: 'Check Your Eligibility Now',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'the-dual-citizenship-trap-read-this',
      kind: 'dual-citizenship',
      h2: 'The dual-citizenship trap — read this before anything else',
      blocks: [
        {
          t: 'p',
          x: "Brazil has one of the world's highest rates of European ancestry citizenship: an Italian passport through your nonno, a Portuguese one through your avó. Under German refund law, holding any EU citizenship blocks the refund completely — even if the passport has never left the drawer, even if your only time in the EU was Germany itself. Brazilian-only citizens: you're clear. Dual citizens with an EU country: the refund route stays closed until German retirement age.",
          sp: [],
        },
        {
          t: 'p',
          x: "And if you're eligible for an EU passport through ancestry but haven't claimed it yet — sequence matters enormously: eligibility is checked at the date of your application, so claim your German refund first, then pursue the European passport. In that order, you can have both. In the reverse order, the refund waits until German retirement age.",
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-do-brazilians-usually-get',
      kind: 'amount',
      h2: 'How Much Do Brazilians Usually Get?',
      blocks: [
        {
          t: 'p',
          x: 'Our retained completed paid cases across all nationalities show an average refund of {{M-04.mean}} and a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}) — with completed refunds on record from {{M-17.range}}. Your refund may include:',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: '100% of all mandatory pension contributions paid from your salary in Germany',
              sp: [],
            },
            {
              x: '50% of voluntary contributions (including freelance or self-employed work)',
              sp: [],
            },
          ],
        },
        {
          t: 'p',
          x: 'The pension contribution rate is 9.3% of gross salary, up to a monthly ceiling (Beitragsbemessungsgrenze) of €8,450 in 2026 (2025: €8,050). Only income up to this cap counts for your refund.',
          sp: [],
        },
      ],
    },
    {
      id: 'timing-your-application',
      kind: 'waiting-period',
      h2: 'Timing Your Application',
      blocks: [
        {
          t: 'p',
          x: 'The waiting period spans 24 full calendar months from your last mandatory pension contribution in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia — measured from the final month of employment or credited benefits, never from the deregistration date. Eligibility is checked at the date of your application: you can start working in Europe the day after submitting, and a later return does not undo a claim that was valid when filed. The reverse timing bites, though — mandatory insurance in any listed country before you file sets the 24-month counter back to zero from its end, and extra German months can push the account to 60.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Fair warning: the pension office can verify EU and UK insurance periods. A refund obtained while actually living or insured in the EU or UK can be withdrawn retrospectively, reclaimed and enforced. In doubt? One message to us settles it before anything is filed.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-fast-is-the-refund-process',
      kind: 'timing',
      h2: 'How Fast Is the Refund Process?',
      blocks: [
        {
          t: 'p',
          x: 'Recent, audited, ours: {{TM-01.share}} of our {{TM-01.population}} reached the client escrow account within three months — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission — see the full data and methodology. Individual processing times vary. Preparation is our lever: complete files, professional filing and follow-up, a process designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
        {
          t: 'p',
          x: 'The decision itself belongs to the responsible pension office, and their queues are their own. Of our latest {{M-12.total}} completed refunds, {{M-20.pct}} reached escrow within six months; where a case runs longer, the entitlement stays whole — and German law can provide 4% annual interest from the seventh calendar month after a complete application.',
          sp: [],
        },
        {
          t: 'p',
          x: 'During an active claim you get a status update at least every four weeks, quiet stretches included, while we track known response deadlines within the managed scope. If six months ever passed without a decision, an inactivity action (Untätigkeitsklage) can become available as a case-dependent last resort — in our operating history, none has yet been required.',
          sp: [],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'How Will I Receive My Money?',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account needed. Refunds we manage arrive first in the escrow account operated by our German partner law firm; the agreed fee comes off there, and the balance moves to the bank account you nominate — Brazilian accounts included. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Some clients prefer to receive euros — a EUR account with a provider such as Wise can be one option where it is available and suitable for your case — while others take the transfer to a Brazilian account. At payout we request exactly the beneficiary and bank details the current payout provider requires for your route. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
          sp: [],
        },
      ],
    },
    {
      id: 'what-documents-are-needed',
      kind: 'intake',
      h2: 'What Documents Are Needed?',
      blocks: [
        {
          t: 'p',
          x: "Passport first, then the German trail: your pension number (Versicherungsnummer — where to find it), your rough employment dates and employers, the account details for the payout, and the deregistration certificate (Abmeldebescheinigung) if it's still in a folder somewhere. Lost pieces are normal: we can help recover your pension number, German deregistration is available as an optional €50 add-on (including VAT), and the insurance record is handled inside the process — we obtain and review the relevant account information during the managed process where required.",
          sp: [
            {
              k: 'a',
              x: 'where to find it',
              href: 'https://www.germanypensionrefund.com/post/german-social-security-number',
            },
          ],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'How digital is the process, really?',
      blocks: [
        {
          t: 'p',
          x: 'Almost everything happens on a screen: details, signatures, document exchange, and our correspondence with the pension office within the agreed scope. The exception every client meets once is the Certificate of Life and Nationality — we prepare it, and it must be confirmed by a notary or another authority accepted by the responsible pension office. Online notarization is often accepted, and any local notary or certification cost is borne by the client. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule.',
          sp: [],
        },
      ],
    },
    {
      id: 'what-does-it-cost',
      kind: 'cost',
      h2: 'What Does It Cost?',
      blocks: [
        {
          t: 'p',
          x: "You never pay anything until your refund has arrived. Our success fee — 9.75% of the refunded amount, capped at €2,500 even for very large refunds, VAT included — is taken from the refund in escrow, and it covers the agreed managed administrative scope including our partner law firm's support within that scope. We explain and translate ordinary German correspondence and the refund decision into English as part of the service; certified translations require a separate agreement. Separate representation in an objection, appeal or court proceeding is not included automatically.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
        {
          t: 'cta',
          items: [
            {
              label: 'Start Your Application Now',
              href: 'https://www.germanypensionrefund.com/get-your-refund',
            },
          ],
        },
        {
          t: 'p',
          x: 'Starting your claim takes less than one minute — with no upfront payment.',
          sp: [],
        },
      ],
    },
    {
      id: 'faq',
      kind: 'faq',
      h2: 'Frequently Asked Questions',
      blocks: [],
    },
    {
      id: 'more-reviews-from-brazilian-clients',
      kind: 'reviews',
      h2: 'More reviews from Brazilian clients',
      blocks: [
        {
          t: 'reviews',
        },
      ],
    },
  ],
  faq: [
    {
      q: 'Can I claim if I also hold an Italian or Portuguese passport?',
      a: "Not before German retirement age — any EU citizenship blocks the refund, even a passport you've never used. Brazilian-only citizens are clear; if you're eligible for an EU passport but haven't claimed it, file the German refund first.",
    },
    {
      q: 'How do I know if I have 60 months of contributions?',
      a: "Even one day of work in a month counts as a full month. Add up all your months, including credited unemployment and parental-leave periods — under 60, and you're likely eligible.",
    },
    {
      q: 'When can I go back to Europe after applying?',
      a: 'You can start working in Europe the day after your claim is submitted — what matters is your eligibility at the time you apply.',
    },
    {
      q: 'Do my INSS contributions affect the German refund?',
      a: 'No — Brazilian pension contributions never block your German claim and never restart the waiting period.',
    },
    {
      q: 'How much does the service cost?',
      a: '9.75% of the refunded amount, capped at €2,500 including VAT — no upfront payment, no minimum fee, covering the agreed managed administrative scope. Separate objection, appeal or court representation is not included automatically. No refund, no fee.',
    },
    {
      q: 'Is a German bank account required?',
      a: "No — the refund passes through our German partner law firm's escrow account and continues to the account you nominate, Brazilian accounts included. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.",
    },
  ],
  schemaFaq: [
    {
      q: 'Can I claim a German pension refund if I also hold an Italian or Portuguese passport?',
      a: 'Not before German retirement age — any EU citizenship blocks the refund, even a passport that has never been used. Brazilian-only citizens are clear. If you are eligible for an EU passport through ancestry but have not claimed it, eligibility is checked at the date of application: file the German refund first, then pursue the European passport.',
    },
    {
      q: 'Do Brazilians qualify for a German pension refund?',
      a: 'Yes, when all conditions hold: Brazilian-only citizenship (no EU second passport), fewer than 60 German contribution months, at least 24 months since the last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country, and residence outside the EU, the UK and India. Living in Brazil never blocks the claim, and INSS contributions have no effect.',
    },
    {
      q: 'How much can Brazilians get back?',
      a: 'Our retained completed paid cases across all nationalities show an average refund of {{M-04.mean}} and a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}), with completed refunds from {{M-17.range}}. The refund returns 100% of mandatory contributions paid from your salary and 50% of voluntary contributions.',
    },
    {
      q: 'How much does the service cost?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT — no upfront payment and no minimum fee, covering the agreed managed administrative scope including our partner law firm's support within that scope. Separate objection, appeal or court representation is not included automatically. No refund, no fee.",
    },
    {
      q: 'Is a German bank account required?',
      a: 'No. The refund passes through the escrow account operated by our German partner law firm and continues to the bank account you nominate — Brazilian accounts included. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
    },
    {
      q: 'How long does a German pension refund take?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission. In the same {{M-12.total}} completed refunds, {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  close: [
    {
      t: 'p',
      x: 'Try our free eligibility calculator or write to our Berlin team — support in English or German.',
      sp: [],
    },
    {
      t: 'cta',
      items: [
        {
          label: 'Use the Refund Calculator',
          href: '/refund-calculator',
        },
        {
          label: 'Contact Us',
          href: '/contact-us',
        },
        {
          label: 'Claim Your Refund Now',
          href: '/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'All rules, all forms, one guide: How to Claim a German Pension Refund: Complete 2026 Guide',
      sp: [
        {
          k: 'a',
          x: 'How to Claim a German Pension Refund: Complete 2026 Guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'We have handled international German pension refunds since 2015 — Berlin-based, with support in English and German.',
      sp: [
        {
          k: 'b',
          x: 'We have handled international German pension refunds since 2015 — Berlin-based, with support in English and German.',
        },
      ],
    },
  ],
  closeTitle: '✉️ Need Help or Have Questions?',
  closeDisclaimer: false,
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Brazilian Citizens',
    audienceType: 'Brazilian citizens who worked in Germany',
    description:
      'Managed handling of German state pension contribution refunds for Brazilian citizens who worked in Germany. No upfront payment and no minimum fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. Our retained completed paid cases across all nationalities show an average refund of {{M-04.mean}} and a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}).',
  },
};

export default page;
