// Generated by scripts/convert-country-pages.mjs from the v1.2 handoff
// (German Pension Refund for Egyptian Citizens (2026)). Do not edit copy here — regenerate from the handoff.
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'egypt',
  title: 'German Pension Refund for Egyptian Citizens (2026)',
  meta: 'German pension refunds for Egyptian citizens. Check the citizenship rule, waiting period, refund amount, certification in Egypt and how to claim.',
  h1: '🇪🇬 German Pension Refund for Egyptian Citizens',
  archetype: 'citizenship-60-first',
  version: 'v1.2',
  hero: [
    {
      t: 'p',
      x: 'Six years as a hospital doctor in Leipzig, almost four as an engineer in Stuttgart, a Hamburg pharmacy before London — the statutory German pension contributions taken from your salary can be claimed back in one sum once you live outside the EU, the UK and India and the 24-month waiting period has run. Egyptian citizenship puts no cap on the months — only a second citizenship could. Checking your eligibility takes a minute; starting the claim takes less.',
      sp: [],
    },
    {
      t: 'p',
      x: 'We check your eligibility, prepare your application and payment documents, and coordinate your claim with our German partner law firm, which reviews and submits it. Along the way you get plain-English explanations of your pension-office letters, regular updates, and support that continues after the decision. No refund, no service fee.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Egyptian citizenship carries no contribution-month limit — 24 German months or 96, the whole refundable balance',
    'No social security agreement with Germany — so no special rule for Egyptian citizens; the three general conditions are the test',
    '{{M-04.sentence.hero}}',
    '{{TM-01.sentence.hero}}',
    'No German bank account required · No refund, no service fee · No minimum service fee',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Do I qualify for a German pension refund as an Egyptian citizen?',
      blocks: [
        {
          t: 'p',
          x: 'A refund before German retirement age turns on three conditions, each judged on the day the application is filed: which citizenships you hold, where your home is, and whether 24 full months have passed since your last month of mandatory pension insurance in Germany or another listed country. Egyptian citizenship on its own passes the first condition; any second citizenship is examined with it.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'Citizenship — every citizenship you hold counts, the Egyptian one included',
        },
        {
          t: 'p',
          x: "An Egyptian citizen sits in the general group of German refund law: no ceiling on contribution months and no residence rule of its own — ceilings exist only for citizens of eleven named countries and for Japanese citizens while they live in Japan. Where the pension office does look closely is at a second citizenship. A German, EU, EEA, Swiss or British citizenship beside the Egyptian one means no refund before German retirement age (one narrow exception aside) — a German passport acquired by naturalisation brings that rule whether or not you kept the Egyptian one; a US, Canadian or Australian citizenship beside it brings that country's 60-month limit. Acquiring another nationality does not by itself settle whether your Egyptian citizenship continues — Egyptian nationality law ties that to permission, retention and declarations — so where your status is uncertain, confirm it with the Egyptian authorities. For the German claim the test is simple: every citizenship actually held on the filing date counts, and the stricter rule decides.",
          sp: [],
        },
        {
          t: 'p',
          x: "What matters is whether you legally hold a citizenship on the filing date. A naturalisation still pending is not yet a citizenship, and one completed after a valid application does not undo the claim; a citizenship passed down by a parent may already be yours under that country's law even if no passport was ever issued. Before anything is filed, we need to hear about every citizenship you hold or may hold.",
          sp: [],
        },
        {
          t: 'h3',
          x: 'Residence — outside the EU, the UK and India',
        },
        {
          t: 'p',
          x: 'The second condition is your home address on the filing date, and for an Egyptian citizen any home outside the EU, the UK and India qualifies — Cairo, Alexandria, Riyadh, Dubai, Doha, Toronto or New York, and equally Zurich or Oslo, because Switzerland, Norway, Iceland and Liechtenstein lie outside the residence rule. The move worth spelling out is the one to the UK: a home in London or Manchester is a home in the UK, and the refund stays closed for as long as you live there, whatever your passport (one narrow exception aside) — the same is true of a home anywhere in the EU. India shuts the door to everyone but its own citizens. Home means home; a conference in Berlin is not a home.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'The 24-month waiting period — counted from your last month of mandatory insurance in Germany or another listed country',
        },
        {
          t: 'p',
          x: "The third condition is a wait of 24 full months (Deutsche Rentenversicherung sets out the 24-month rule here), and it runs from your last month of mandatory pension insurance — in Germany, in another EU state, in the UK, Türkiye or an ex-Yugoslav state (Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia) — not from your deregistration or your departure. Your earliest filing date is the first day of the 25th month after that month; an earlier filing does not shorten the period and can bring extra confirmation requests. Egyptian social insurance contributions from a job at home leave the clock untouched, as does mandatory insurance in Switzerland, Norway, Iceland or Liechtenstein for citizens outside the no-refund group. What restarts it is new mandatory insurance inside the listed area — and the case to spell out for doctors and pharmacists is the UK: an insured job in London after Germany makes the 24 months run from that job's last contribution month instead, while local employment in Riyadh or Dubai after Germany — with no compulsory German pension insurance continuing under a posting from Germany — changes nothing. No deadline applies to a first application; no interest is paid for the years before it. Type your last contribution month into our waiting-period calculator and it names the date.",
          sp: [
            {
              k: 'a',
              x: 'Deutsche Rentenversicherung sets out the 24-month rule here',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Allgemeine-Informationen/Wissenswertes-zur-Rente/FAQs/International/Erstattung.html',
            },
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'is-there-a-60-month-limit',
      kind: 'sixty-month',
      h2: 'Is there a 60-month limit for Egyptian citizens — and does the missing agreement matter?',
      blocks: [
        {
          t: 'p',
          x: 'No limit — and the absence of an agreement is the reason, not an obstacle. The 60-month rule reaches citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay, and Japanese citizens while they live in Japan: for them a refund before retirement age requires 59 or fewer German months — contribution months plus the German months credited to the account, such as child-raising periods or months on unemployment benefit, though not every line of the insurance record counts — with nothing from any other country added. Every one of those limits comes from a social security agreement that allows the nationality to pay voluntary German contributions, and a right to pay in, used or not, rules out taking the money out early. Egypt has no such agreement with Germany, a person holding Egyptian citizenship alone and living outside the EU, the UK and India holds no such right, and once the 24-month waiting period has run German law refunds the employee share to everyone in that position — 24 months or 96 makes no difference to the entitlement. What 60 German months do change is the alternative: from that point the five-year qualifying period (allgemeine Wartezeit) is met, a German old-age pension at retirement age has been earned as well, payable in Egypt like anywhere else, and the refund replaces it in one payment, after which the refunded months never become pension months again.',
          sp: [
            {
              k: 'a',
              x: 'no such agreement with Germany',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Sozialversicherungsabkommen/sozialversicherungsabkommen_detailseite.html',
            },
          ],
        },
      ],
    },
    {
      id: 'what-we-do',
      kind: 'service',
      h2: 'What we do for you — and what it costs',
      blocks: [
        {
          t: 'p',
          x: 'Before anything is filed. You provide your details, documents and signatures; we do the rest of the preparation. We check your eligibility, obtain and review the relevant DRV account information during the managed process where required, prepare your refund application and payment documents, identify the recommended first pension office from your record and coordinate the claim with our German partner law firm, which reviews and submits it.',
          sp: [
            {
              k: 'b',
              x: 'Before anything is filed.',
            },
          ],
        },
        {
          t: 'p',
          x: 'While the pension office works. Pension-office letters for your claim are received at a German address, scanned to you and explained in plain English. After your claim is submitted, you receive an update at least every four weeks — even when the update is that no pension-office response has arrived. If there is still no decision six months after submission, updates come at least every two weeks, whether or not a formal complaint has been filed. Material requests and developments are communicated sooner. If we are still waiting for a decision three months after submission, we contact the pension office to check where the application stands. We keep track of known response and objection deadlines within the agreed scope; if a letter reaches you directly, forward it to us straight away with the date you received it — only deadlines known to us or our partner law firm can be protected.',
          sp: [
            {
              k: 'b',
              x: 'While the pension office works.',
            },
          ],
        },
        {
          t: 'p',
          x: "After the decision. Our managed service includes checking the pension office's decision against your record and evidence. If contribution periods you can evidence — payslips, for example — are missing from the refund statement, a straightforward objection is included in the service fee: we draft it from our standard template and your evidence, and it goes to the pension office; no extra cost. If the disagreement is a legal question — for example, the office rejects the refund on a legal ground you could not be expected to assess yourself — objection representation is separate work by our partner law firm, agreed directly between you and the firm at its own cost, outside the service scope. If an approved refund does not arrive, we follow it up within the managed scope with the pension office and Renten Service until the payment is resolved.",
          sp: [
            {
              k: 'b',
              x: 'After the decision.',
            },
          ],
        },
        {
          t: 'p',
          x: "Our fee is 9.75% of the refunded amount, capped at €2,500 including VAT, with no upfront service fee and no minimum service fee. No refund, no service fee. The fee covers the agreed managed administrative scope, including our partner law firm's support within that scope. We do not provide legal services, advice or representation; separate representation in an objection, appeal or court proceeding is not included automatically. German deregistration is available as an optional €50 add-on including VAT, payable with the service fee after your refund reaches escrow — and if your German pension insurance number has gone missing, we can help identify or recover it.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
        {
          t: 'p',
          x: '{{TM-01.sentence}} {{M-12.sentence}} Individual processing times vary — see the full data and methodology. Processing and payment dates depend on the responsible pension office and the payment route, so a specific date cannot be guaranteed; the process is designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      id: 'what-you-need-to-start',
      kind: 'intake',
      h2: 'What you need to start',
      blocks: [
        {
          t: 'p',
          x: 'To get started, upload a copy of your passport, a payslip from your time in Germany and your deregistration confirmation (Abmeldebestätigung). Your account guides you through the questions and documents. Missing your German pension number? We help recover it. Not deregistered yet? We offer deregistration assistance for €50 including VAT. If your claim needs additional documents or signed originals by post, we explain exactly what to provide.',
          sp: [],
        },
      ],
    },
    {
      id: 'journeys',
      kind: 'journeys',
      h2: 'Three illustrative journeys — Riyadh, Cairo, Dubai',
      blocks: [
        {
          t: 'note',
          x: 'Worked examples, not client cases.',
        },
        {
          t: 'p',
          x: "The doctor who moved from Leipzig to Riyadh. Six years as an Assistenzarzt at a Leipzig hospital, July 2019 to June 2025 — 72 months at €5,000 gross, compulsory German statutory pension contributions paid throughout, since he never applied for the exemption in favour of the doctors' professional pension scheme (Versorgungswerk) — then a consultant post in Riyadh from July 2025. Every month counts, Egyptian citizenship setting no ceiling: €465 a month, roughly €33,500 in refundable employee contributions, and 1 July 2027 — the first day of the 25th month after June 2025 — is the earliest application date; Saudi Arabia lies outside the EU, the UK and India, so the address is no obstacle. Those six insured years have also brought him a German old-age pension at retirement age, payable in Riyadh, and the refund would replace it — a comparison worth making before he decides.",
          sp: [
            {
              k: 'b',
              x: 'The doctor who moved from Leipzig to Riyadh.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The engineer who went home to Cairo. A Stuttgart supplier from September 2021 to April 2025 — 44 months at €4,200 gross — then Cairo from May 2025. €390.60 a month, roughly €17,200 in refundable employee contributions, claimable from 1 May 2027; the Egyptian social insurance contributions from her new job change nothing on the German side, and with 44 months there is no German pension entitlement to weigh against the refund.',
          sp: [
            {
              k: 'b',
              x: 'The engineer who went home to Cairo.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The pharmacist who moved on to London — and then to Dubai. Four years in a Hamburg pharmacy, January 2018 to December 2021 — 48 months at €3,800 gross, all with compulsory German statutory pension contributions — then an insured job in London from January 2022 to March 2025, then Dubai from April 2025. The German months are refundable, €353.40 a month and roughly €17,000 in all, but two things happened in London: while he lived there, a home in the UK held the refund back, and his insured UK employment restarted the 24 months, which now run from March 2025 — his last UK contribution month — to an earliest application date of 1 April 2027. The UK contributions themselves stay in the UK system and are never part of a German refund.',
          sp: [
            {
              k: 'b',
              x: 'The pharmacist who moved on to London — and then to Dubai.',
            },
          ],
        },
        {
          t: 'p',
          x: 'Try your own months in the free refund calculator.',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'which-of-your-years-in-germany',
      kind: 'years',
      h2: 'Which of your years in Germany actually paid pension contributions?',
      blocks: [
        {
          t: 'p',
          x: 'One question sorts every stretch of your German years before any month is counted: was statutory pension insurance paid for it?',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: "Employment based in Germany under German social insurance — the normal result of a German employment contract, on a hospital payroll as much as in an engineering firm — brings pension insurance from the start: every month counts and the employee share is refundable. Lower pay is the exception: for months in employment covered by the Übergangsbereich rules for the relevant year (in 2026, regular pay between €603.01 and €2,000 a month) the refund is half of the total pension contributions paid for them — 9.3% of gross pay is the wrong sum for those months, so a part-time job at €1,500 a month in 2026 is insured and every month counts, but its refund follows the half-of-total rule (for years before 2023 the band's upper limit was lower, so the year decides).",
              sp: [
                {
                  k: 'b',
                  x: 'Employment based in Germany under German social insurance',
                },
              ],
            },
            {
              x: 'Doctors and pharmacists: check for a Versorgungswerk exemption. An employed doctor or pharmacist who is a compulsory member of a professional pension scheme (Versorgungswerk — the Ärzteversorgung or Apothekerversorgung, a body distinct from the professional chamber itself) can be exempted from statutory pension insurance for that employment on application. For exempted months no DRV contributions exist and nothing is refundable from DRV; the insurance record shows which applied to you.',
              sp: [
                {
                  k: 'b',
                  x: 'Doctors and pharmacists: check for a Versorgungswerk exemption.',
                },
              ],
            },
            {
              x: "Unpaid clinical time carries nothing. A Hospitation or observership without pay, a Famulatur, an unpaid elective — none of these is insured employment, so those months neither count nor block; from the first month on a hospital's payroll as a doctor, the months are insured unless the Versorgungswerk exemption above was granted for that employment.",
              sp: [
                {
                  k: 'b',
                  x: 'Unpaid clinical time carries nothing.',
                },
              ],
            },
            {
              x: "Minijobs turn on one choice made at the time: if the small employee top-up (the default since 2013) was kept, the months count and the top-up is refundable; if it was waived, only the employer's flat-rate contributions were paid, nothing of yours is in the record, and those months neither block nor restart the waiting period, though they can still earn partial credit toward the five-year qualifying period.",
              sp: [
                {
                  k: 'b',
                  x: 'Minijobs',
                },
              ],
            },
            {
              x: 'Werkstudent jobs are pension-insured although students pay no health, care or unemployment insurance through that employment; above the minijob limit the months count and the contributions come back (the Übergangsbereich rule above applies inside its band). Ausbildung contracts are pension-insured too, and the Übergangsbereich rules are not applied to training pay. (Only where training pay was €325 a month or less did the employer bear the whole contribution; those months count, but hold no employee share.)',
              sp: [
                {
                  k: 'b',
                  x: 'Werkstudent jobs',
                },
                {
                  k: 'b',
                  x: 'Ausbildung contracts',
                },
              ],
            },
            {
              x: 'A scholarship or stipend without an employment contract — a DAAD grant or an Egyptian government scholarship — carries no pension insurance however long it ran, whereas a doctoral or postdoc position on an employment contract is insured like any job. Freelance or self-employed work usually falls outside mandatory insurance, and where voluntary or compulsory self-employed contributions were paid, the refund is half of them.',
              sp: [
                {
                  k: 'b',
                  x: 'A scholarship or stipend without an employment contract',
                },
                {
                  k: 'b',
                  x: 'Freelance or self-employed work',
                },
              ],
            },
            {
              x: 'Posted from Egypt for a fixed period with the employment relationship left in Egypt, you may have remained outside German insurance under the Einstrahlung rule — with no agreement between Egypt and Germany, German law alone decides — and then no German contributions exist for those months.',
              sp: [
                {
                  k: 'b',
                  x: 'Posted from Egypt for a fixed period',
                },
              ],
            },
          ],
        },
        {
          t: 'p',
          x: 'Payslips and memory yield an estimate; the refunded months come from the official insurance record (Versicherungsverlauf), which in a managed claim we obtain and review where required.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-comes-back-and-what',
      kind: 'amount',
      h2: 'How much comes back — and what about tax in Egypt?',
      blocks: [
        {
          t: 'p',
          x: "The refund is your own share of the contributions — 9.3% of gross pay since 2018, charged up to the monthly ceiling (Beitragsbemessungsgrenze: €8,450 in 2026, €8,050 in 2025) — and normally the whole of it; the employer's share stays in the system, and pay above the ceiling was never insured. The main exceptions change the calculation: voluntary contributions and the compulsory contributions of self-employed people are refunded at 50%; months in employment covered by the Übergangsbereich rules for the relevant year at half of the total contributions paid for them; and where Deutsche Rentenversicherung once funded a benefit for you — a rehabilitation programme, say — only the contributions paid after it are refundable, while the completed refund still closes the whole record. These are checked before anything is filed. The legal basis is § 210 SGB VI.",
          sp: [
            {
              k: 'a',
              x: '§ 210 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__210.html',
            },
          ],
        },
        {
          t: 'p',
          x: '{{M-04.sentence}} Our refund calculator applies the actual statutory employee contribution rate and monthly ceiling (Beitragsbemessungsgrenze) of every year back to 1975 — including Deutsche-Mark periods and East/West differences — rather than a flat percentage.',
          sp: [
            {
              k: 'a',
              x: 'refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
        {
          t: 'p',
          x: 'On the German side the refund is paid out without income tax; the exemption is written into German law and confirmed by the Federal Fiscal Court. Egypt, or wherever you are tax-resident, is another matter: Egypt taxes its residents on income earned in Egypt and, where Egypt is the centre of their professional or business activity, on income from abroad as well, and whether a German contribution refund is caught by that rule in your case is for a local adviser to say — we do not provide individual tax, pension or legal advice.',
          sp: [],
        },
      ],
    },
    {
      id: 'which-german-pension-office-handles-an',
      kind: 'office',
      h2: "Which German pension office handles an Egyptian citizen's claim?",
      blocks: [
        {
          t: 'p',
          x: "Neither Egypt nor any Gulf state has a German liaison office (Verbindungsstelle), so three questions settle the office — the insurance record, then a second citizenship, then the country of residence. Was DRV Knappschaft-Bahn-See ever your carrier? Then it is responsible. If not, was DRV Bund the last carrier of your account? Then DRV Bund. If neither, a second citizenship with a liaison office of its own comes next (a US or Canadian citizen's claim goes to DRV Nord wherever they live), then a liaison office for your country of residence where one exists (DRV Nord for the USA and Canada, DRV Oldenburg-Bremen for Australia, DRV Braunschweig-Hannover for Japan, South Korea and the Philippines) — and where none exists, as for an Egyptian citizen living in Egypt, Saudi Arabia, the UAE or Qatar, the regional office that holds the account. A claim sent to the wrong office keeps its filing date but loses weeks; the full decision tree and the office finder are in our guide to the responsible pension office. In a managed claim, our German partner law firm files the claim with the recommended office we identify from your record.",
          sp: [
            {
              k: 'a',
              x: 'our guide to the responsible pension office',
              href: 'https://www.germanypensionrefund.com/post/which-german-pension-office-handles-your-claim',
            },
          ],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Getting paid in Egypt — or wherever you live',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account is required. In a claim we manage, your refund is paid through the escrow account operated by our German partner law firm; after the agreed service fee is deducted, the remaining balance is transferred to the bank account you nominate — a third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent, so the route for a transfer to Egypt or elsewhere is checked shortly before the money moves. Eligibility and payment route are separate: a valid refund may require an account in a permitted country if transfers to the residence country are restricted.',
          sp: [],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Digital for most clients — certified signatures in Egypt',
      blocks: [
        {
          t: 'p',
          x: 'Most clients can complete their entire part of the process digitally: you submit your details and sign online. Every client has their identity and signature confirmed using their passport or an accepted equivalent; depending on the route, that confirmation can be completed digitally or, where a certified signature is needed, in person. Where one is needed, we prepare the document and you have it certified by one certifier — no combination of certifiers is ever required. In Egypt that certifier is the German Embassy in Cairo, which certifies signatures on documents for use with a German authority whatever your nationality — only when you appear in person, by appointment booked through its online system under "Beglaubigungen"; bring your passport in the original with a copy (the Embassy\'s certification page) — and the same page says the honorary consul in Alexandria can certify signatures for residents of the northern districts her office covers. Because local certifiers generally cannot read the document, the mission is the route here; a bank is the alternative only where its certification is accepted for the particular document by the responsible pension office, and other local authorities usually want an official translation first, which costs more and takes longer. Required local certification, notary or translation costs are borne by the client. If DRV Oldenburg-Bremen is responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — for an Egyptian citizen that office is the usual result of living in Australia, unless Knappschaft-Bahn-See ever insured you or DRV Bund was the last carrier of your account.',
          sp: [
            {
              k: 'a',
              x: "the Embassy's certification page",
              href: 'https://kairo.diplo.de/eg-de/service/1495766-1495766',
            },
          ],
        },
        {
          t: 'p',
          x: 'You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. From Egypt or the Gulf, that means form V0901 on paper and in the post — ordinary email is not accepted for identity reasons, and fax has been discontinued. In a self-filed claim, the official application form provides for your personal data to be certified on the form itself — so the application travels to the certifying body, from Egypt in practice the Embassy or the honorary consul in Alexandria, or a bank where its certification is accepted for that form. In a managed claim, the analog step is a single page we prepare for you. Our V0901 guide explains the form section by section.',
          sp: [
            {
              k: 'a',
              x: 'V0901 guide',
              href: 'https://www.germanypensionrefund.com/v0901-pension-refund-form-english',
            },
          ],
        },
      ],
    },
    {
      id: 'living-in-egypt-with-another-citizenship',
      kind: 'dual-citizenship',
      h2: 'Living in Egypt with another citizenship?',
      blocks: [
        {
          t: 'p',
          x: "For anyone living in Egypt on another passport the address side is settled — Egypt lies outside the EU, the UK and India — and Egyptian social insurance has no bearing on a German refund: it never blocks the claim, never restarts the 24 months and never adds to any German month total, whatever your citizenship. What decides the rest is the citizenship, and the same 24-month wait applies to all. No limit for most nationalities; the 60-month limit, counting German months only, for citizens of the eleven countries named above — US, Canadian, Australian, Indian, Korean and Filipino citizens among them; no refund before German retirement age for German and other EU, EEA, Swiss and British citizens (one narrow exception aside); no limit for Japanese citizens outside Japan. Hold two citizenships and both rules apply — the stricter one wins. Our guide for citizens of other countries has every nationality's rule in one table.",
          sp: [
            {
              k: 'a',
              x: 'US',
              href: 'https://www.germanypensionrefund.com/usa',
            },
            {
              k: 'a',
              x: 'Canadian',
              href: 'https://www.germanypensionrefund.com/canada',
            },
            {
              k: 'a',
              x: 'Australian',
              href: 'https://www.germanypensionrefund.com/australia',
            },
            {
              k: 'a',
              x: 'Indian',
              href: 'https://www.germanypensionrefund.com/india',
            },
            {
              k: 'a',
              x: 'Korean',
              href: 'https://www.germanypensionrefund.com/southkorea',
            },
            {
              k: 'a',
              x: 'Filipino',
              href: 'https://www.germanypensionrefund.com/thephilippines',
            },
            {
              k: 'a',
              x: 'Our guide for citizens of other countries',
              href: 'https://www.germanypensionrefund.com/other-countries',
            },
          ],
        },
      ],
    },
    {
      id: 'a-family-members-german-contributions',
      kind: 'family',
      h2: "A family member's German contributions",
      blocks: [
        {
          t: 'p',
          x: "Where a spouse, registered partner or parent has died with German contributions on record, the closest family — the surviving spouse or registered partner and, in the cases the law provides for, the children — can be entitled to a refund of those contributions where no German survivor's pension is payable because the deceased had not met the five-year qualifying period (allgemeine Wartezeit). Checking that period means looking beyond the German months — at foreign periods that count toward it (periods under Egyptian social insurance never do; there is no agreement) and at the rules that treat it as met in special cases. Survivors need not wait 24 months, but their claim can become time-barred four years after the end of the year of death. Where the qualifying period was met, a German survivor's pension may be payable instead — worldwide, Egypt included. Our German widow's pension guide and the survivors chapter of the complete guide explain who can claim, in which order and with what evidence.",
          sp: [
            {
              k: 'a',
              x: "Our German widow's pension guide",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
  ],
  faq: [
    {
      q: 'Do Egyptian citizens have a limit on refundable German months?',
      a: "No. The cap exists for citizens of eleven countries — the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay — and for Japanese citizens while they live in Japan, because their countries' social security agreements with Germany create it. Egypt has no agreement with Germany, so there is no cap for Egyptian citizenship; once you have 60 German months you have also earned a German old-age pension payable at German retirement age, which the refund replaces. Hold a second citizenship and its rule applies too — the stricter of the two decides.",
    },
    {
      q: 'I have become a German, US or Canadian citizen — what changes?',
      a: "The new citizenship's rule applies from the day you hold it. German, EU, EEA, Swiss or British citizenship means no refund before German retirement age (one narrow exception aside), whether or not you kept the Egyptian one; US or Canadian citizenship means the 60-month limit — 59 German months at most, contribution months plus credited periods such as child-raising or unemployment-benefit months, nothing foreign added. Whether your Egyptian citizenship continues is not settled by the new one alone — Egyptian nationality law ties it to permission, retention and declarations — so confirm your status with the Egyptian authorities if it is uncertain; every citizenship you actually hold on the filing date is counted, and the stricter rule decides. Everything is judged on the filing date — a naturalisation completed after a valid application leaves the claim standing, while one still pending is not yet a citizenship. We do not provide individual legal advice.",
    },
    {
      q: 'I moved from Germany to the UK — does that change anything?',
      a: 'Two things. While your home is in the UK the refund is closed, exactly as it is while you live in Germany or elsewhere in the EU. And if you are employed there under mandatory UK National Insurance, that employment restarts the 24-month waiting period, which then runs from your last UK contribution month rather than your last German one. Once you live outside the EU, the UK and India — in Egypt, the Gulf, the USA or Canada — and the 24 months have run, the German months are claimable, provided no other citizenship you hold introduces a further restriction; the UK contributions are not part of the German refund.',
    },
    {
      q: 'Do my Egyptian social insurance contributions affect the German refund?',
      a: 'No. Egyptian social insurance and German pension insurance are separate systems: what you or your employer paid to the National Organization for Social Insurance neither blocks the German refund nor restarts the 24-month wait nor adds to any German month total. The only insurance that restarts the wait, and blocks the refund while it lasts, is mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state.',
    },
    {
      q: 'Do I need an Egyptian notary?',
      a: 'Normally not. Most clients can complete their part of the process digitally; where a certified signature is needed, one certifier is enough, and in Egypt it is the German Embassy in Cairo by online appointment — it certifies whatever your nationality — or the honorary consul in Alexandria for residents of the districts her office covers; a bank is the alternative only where its certification is accepted for the document by the responsible pension office, and other local authorities usually want an official translation first. Required local certification, notary or translation costs are borne by the client.',
    },
    {
      q: 'I was a student first, then a doctor — which months count?',
      a: "The unpaid months carry nothing: a scholarship without an employment contract, an unpaid Hospitation or Famulatur, an unpaid elective — none is insured employment, so those months neither count nor block. A Werkstudent job above the minijob limit is pension-insured and every such month counts; from the first month on a hospital's payroll as a doctor the contributions run and every one of those months is refundable — unless you were exempted from statutory pension insurance in favour of the professional pension scheme (Versorgungswerk) for that employment, in which case no DRV contributions exist for it. Which is which, the insurance record shows; in a managed claim we obtain and review it where required.",
    },
  ],
  close: [
    {
      t: 'p',
      x: 'For the eligibility tables, month counting, survivors, retirement age, forms and objections in full, read the complete 2026 guide. Our eligibility check walks through citizenship, residence and the 60-month and 24-month rules — a preliminary indication in under a minute. Starting your claim takes less than one minute — start here →',
      sp: [
        {
          k: 'a',
          x: 'the complete 2026 guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'a',
          x: 'eligibility check',
          href: 'https://www.germanypensionrefund.com/refund-calculator',
        },
        {
          k: 'a',
          x: 'start here →',
          href: 'https://www.germanypensionrefund.com/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may also apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
  ],
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'what-we-do': 'what-we-do',
    journeys: 'journeys',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Egyptian Citizens',
    audienceType: 'Egyptian citizens who worked in Germany',
    description:
      'Managed German state pension contribution refunds for Egyptian citizens who worked in Germany. Egyptian citizenship carries no contribution-month limit; a refund before German retirement age needs residence outside the EU, the UK and India, a 24-month waiting period after the last month of mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state, and no German, EU, EEA, Swiss or British citizenship held alongside (one narrow statutory exception aside) — any other citizenship held alongside brings its own rule, such as a 60-month limit. No upfront or minimum service fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. {{M-04.sentence.schema}}',
  },
};

export default page;
