// Generated by scripts/convert-country-pages.mjs from the 26 August 2026 handoff
// (German Pension Refund for Japanese Citizens (2026)). Do not edit copy here — regenerate from the handoff.
// Copy as delivered in the August 2026 handoff — it carries the older service
// wording; the client will send refreshed copy later (regenerate from it then).
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'japan',
  title: 'German Pension Refund for Japanese Citizens (2026)',
  meta: "Japan's rule is unique: the 60-month cap applies only while you live in Japan. Under it — or outside Japan — your German contributions are claimable.",
  h1: '🇯🇵 German Pension Refund for Japanese Citizens',
  archetype: 'august',
  version: '26 August 2026',
  hero: [
    {
      t: 'p',
      x: 'Japan negotiated a rule no other agreement country has: whether the famous 60-month cap applies to you depends on where you live when you file. As a Japanese citizen you can claim your German pension contributions back once at least 24 months have passed since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia, and you live outside the EU, the UK and India — living in Japan is fine. The cap only enters the picture at home: from Japan you can claim with up to 59 contribution months, while from anywhere else there is no month limit at all.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Among our retained completed paid cases across all nationalities, the average refund was {{M-04.mean}}',
    'Retained records show completed refunds from {{M-17.range}}',
    '{{TM-01.sentence.hero}}',
    'No German bank account required',
    'No refund, no fee — nothing upfront',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'One cap, two maps',
      blocks: [
        {
          t: 'p',
          x: 'The Germany–Japan agreement ties the 60-month rule to your address, not just your passport:',
          sp: [],
        },
        {
          t: 'p',
          x: 'Living in Japan: the refund is available while your German record holds fewer than 60 contribution months. At 60 or more, no lump sum can be claimed from Japan — the account has instead earned a German old-age pension, payable at retirement age, in Japan as anywhere. (The same address rule applies to recognized refugees and stateless persons living in Japan.)',
          sp: [
            {
              k: 'b',
              x: 'Living in Japan:',
            },
          ],
        },
        {
          t: 'p',
          x: 'Living outside Japan — and outside the EU, the UK and India: no month limit exists. One year of contributions or fifteen, the full employee share is claimable once the waiting period has run. Eligibility is checked at the date of your application, so what counts is your address on the day you file.',
          sp: [
            {
              k: 'b',
              x: 'Living outside Japan',
            },
          ],
        },
      ],
    },
    {
      id: 'the-rest-of-the-checklist',
      kind: 'qualify',
      h2: 'The rest of the checklist',
      blocks: [
        {
          t: 'p',
          x: 'Beyond the address logic, two conditions and one non-issue:',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: 'The waiting period: at least 24 full calendar months since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia — counted from the final contribution month, not your deregistration date, with a single insured day filling a month. New mandatory insurance in a listed country restarts the count from its end.',
              sp: [
                {
                  k: 'b',
                  x: 'The waiting period:',
                },
              ],
            },
            {
              x: 'Your passports: a German, EU, EEA, Swiss or UK citizenship blocks the refund — a second passport blocks even if never used.',
              sp: [
                {
                  k: 'b',
                  x: 'Your passports:',
                },
              ],
            },
            {
              x: "The non-issue: your Japanese pension. Contributions to the National Pension or Employees' Pension Insurance in Japan never block the German claim and never restart the 24-month wait.",
              sp: [
                {
                  k: 'b',
                  x: 'The non-issue:',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'what-the-refund-contains',
      kind: 'amount',
      h2: 'What the refund contains',
      blocks: [
        {
          t: 'p',
          x: "Among our retained completed paid cases across all nationalities, the average refund was {{M-04.mean}} and the median {{M-04.median}} (calculated {{M-04.calculatedOn}}) — retained records show completed refunds from {{M-17.range}}. The composition is set by law: 100% of the mandatory contributions deducted from your salary in Germany, 50% of voluntary or self-employed contributions, and none of the employer's matching share. The deduction ran at 9.3% of gross salary since 2018, up to the monthly ceiling of €8,450 in 2026 (2025: €8,050); earnings above the ceiling carried no deductions and add nothing to the refund.",
          sp: [],
        },
        {
          t: 'p',
          x: 'Estimate yours with the free refund calculator →',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'sixty-months-and-beyond-a-real',
      kind: 'sixty-month',
      h2: 'Sixty months and beyond — a real decision',
      blocks: [
        {
          t: 'p',
          x: "For Japanese citizens abroad with 60+ months, two doors stand open, and only one can be used: the full refund of the employee share now, or a German old-age pension at retirement age. They are strict alternatives — a completed refund pays out the entire refundable balance and dissolves the old insurance relationship, so the refunded months never count toward a pension again. We won't make that choice for you; our free eligibility check shows which doors your record opens.",
          sp: [
            {
              k: 'a',
              x: 'free eligibility check',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'the-fee',
      kind: 'cost',
      h2: 'The fee',
      blocks: [
        {
          t: 'p',
          x: "9.75% of the refunded amount, capped at €2,500 including VAT — payable only after the refund has actually arrived, with no upfront payment and no minimum fee. The cap covers the agreed managed administrative scope, including our partner law firm's support within that scope; ordinary German correspondence and the decision are explained and translated into English as part of the service, while certified translations require a separate agreement. Separate representation in an objection, appeal or court proceeding is not included automatically.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
      ],
    },
    {
      id: 'what-to-have-ready',
      kind: 'intake',
      h2: 'What to have ready',
      blocks: [
        {
          t: 'p',
          x: "Your Japanese passport; your German pension number (Versicherungsnummer — our guide shows where it appears); approximate employment dates and employers; your current address and the payout account; and the Abmeldung (deregistration certificate), if the move home didn't misplace it. Gaps close along the way: we can help recover your pension number, German deregistration is available as an optional €50 add-on (including VAT), and we obtain and review the relevant account information during the managed process where required.",
          sp: [
            {
              k: 'a',
              x: 'our guide',
              href: 'https://www.germanypensionrefund.com/post/german-social-security-number',
            },
          ],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Where paper enters the process',
      blocks: [
        {
          t: 'p',
          x: 'Rarely, on your side. Most clients complete their entire part of the managed process digitally, while we handle the pension-office correspondence within the agreed scope. The one universal exception is the Certificate of Life and Nationality we prepare, which must be confirmed by a notary or another authority accepted by the responsible pension office — online notarization is often accepted, and any local notary or certification cost is borne by the client. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule. Self-filing from abroad is more paper-bound: the office then generally requires originals, because ordinary email is not an identity-safe filing route.',
          sp: [],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Receiving the money in Japan',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account at any stage: the refund is paid into the escrow account operated by our German partner law firm, the agreed fee is deducted there, and the balance is transferred to the bank account you nominate — Japanese accounts included. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
          sp: [],
        },
      ],
    },
    {
      id: 'pace-measured-quarterly',
      kind: 'timing',
      h2: 'Pace, measured quarterly',
      blocks: [
        {
          t: 'p',
          x: 'The current dataset: {{TM-01.share}} of our {{TM-01.population}} reached the client escrow account within three months — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission — see the full data and methodology. Individual processing times vary. The deciding office sets the pace; {{M-20.pct}} of our latest {{M-12.total}} completed refunds reached escrow within six months, the slower remainder lost nothing, and German law can provide 4% annual interest from the seventh calendar month after a complete application.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
        {
          t: 'p',
          x: 'What we add is discipline: files prepared to be decided without avoidable queries — a process designed to avoid preventable delays — a status update at least every four weeks during an active claim, and known response deadlines tracked within the managed scope. An inactivity action (Untätigkeitsklage) can become available after six months as a case-dependent last resort; in our operating history, none has yet been required.',
          sp: [],
        },
      ],
    },
    {
      id: 'when-a-family-member-paid-in',
      kind: 'family',
      h2: 'When a family member paid in',
      blocks: [
        {
          t: 'p',
          x: "German contributions left behind by a late spouse, registered partner or parent can be reclaimed if their record stayed under the five-year qualifying period — spouse or registered partner first in line, children after. Survivors face no waiting period, only a deadline: four years after the end of the year of death. Records of five years or more follow the pension path instead — a German widow's or widower's pension may be payable, to Japan as to anywhere. Both paths in detail: German widow's pension guide → · survivors chapter of the complete guide →",
          sp: [
            {
              k: 'a',
              x: "German widow's pension guide →",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide →',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
    {
      id: 'faq',
      kind: 'faq',
      h2: 'Frequently asked questions',
      blocks: [],
    },
  ],
  faq: [
    {
      q: 'I live in Japan — can I claim?',
      a: 'Yes, while your German record holds fewer than 60 contribution months and the 24-month waiting period has passed. Living in Japan itself never blocks the claim.',
    },
    {
      q: 'I live in Japan and have 60+ months — what now?',
      a: 'No lump sum can be claimed from Japan; those months have earned a German old-age pension at retirement age instead, payable in Japan. The cap is tied to residence at the date of application — for a Japanese citizen living outside Japan (and outside the EU, the UK and India), no month limit applies.',
    },
    {
      q: 'Do my Japanese pension contributions affect the German claim?',
      a: "No. Contributions to Japan's National Pension or Employees' Pension Insurance neither block the German refund nor restart the 24-month waiting period.",
    },
    {
      q: 'With 60+ months claimed from abroad — refund or pension?',
      a: 'Strictly one or the other: a completed refund dissolves the old insurance relationship, so the refunded months never become pension months. Our free check shows which doors your record opens.',
    },
    {
      q: 'Can I take a job in Europe right after filing?',
      a: "Yes. Eligibility is checked at the date of your application — a validly filed claim isn't undone by new employment the day after. Before filing, the reverse applies: mandatory insurance in a listed country restarts the 24-month count.",
    },
    {
      q: 'What is the fee?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT — nothing upfront, no minimum fee, covering the agreed managed administrative scope including our partner law firm's support within that scope. Separate representation in an objection, appeal or court proceeding is not included automatically. No refund, no fee.",
    },
    {
      q: 'Do I need a German bank account?',
      a: 'No — the refund reaches you via the escrow account operated by our German partner law firm, then the account you nominate, Japanese accounts included. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
    },
  ],
  schemaFaq: [
    {
      q: 'Can Japanese citizens living in Japan claim a German pension refund?',
      a: 'Yes — while the German record holds fewer than 60 contribution months and at least 24 months have passed since the last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country. Living in Japan itself never blocks the claim; at 60 or more months, no lump sum can be claimed from Japan — a German old-age pension at retirement age takes its place.',
    },
    {
      q: 'Does the 60-month limit apply to Japanese citizens outside Japan?',
      a: 'No. For a Japanese citizen living outside Japan — and outside the EU, the UK and India — no month limit applies: the full employee share is claimable regardless of the length of the German record, once the 24-month waiting period has passed. Eligibility, including the address rule, is checked at the date of application.',
    },
    {
      q: 'Do Japanese pension contributions affect the German claim?',
      a: "No. Contributions to Japan's National Pension or Employees' Pension Insurance neither block the German refund nor restart the 24-month waiting period.",
    },
    {
      q: 'With more than 60 months, is it refund or pension?',
      a: 'Strictly one or the other: a completed refund pays out the entire refundable balance and dissolves the old insurance relationship, so the refunded months no longer count toward a pension at retirement age.',
    },
    {
      q: 'How much does the service cost?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT — nothing upfront and no minimum fee, covering the agreed managed administrative scope including our partner law firm's support within that scope. Separate representation in an objection, appeal or court proceeding is not included automatically. No refund, no fee.",
    },
    {
      q: 'How long does a German pension refund take?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission; {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  close: [
    {
      t: 'p',
      x: 'Wherever the map puts you, the arithmetic is the same: starting your claim takes less than one minute, and you pay only when your money arrives.',
      sp: [],
    },
    {
      t: 'cta',
      items: [
        {
          label: 'free refund calculator',
          href: '/refund-calculator',
        },
        {
          label: 'Claim your refund now',
          href: '/get-your-refund',
        },
      ],
    },
  ],
  closeTitle: 'Claim your pension refund today',
  closeDisclaimer: false,
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Japanese Citizens',
    audienceType:
      'Japanese citizens who contributed to the German pension system',
    description:
      'Managed handling of German state pension contribution refunds for Japanese citizens. The 60-month cap applies only while living in Japan; outside Japan no month limit applies. No upfront payment and no minimum fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. Among our retained completed paid cases across all nationalities, the average refund was {{M-04.mean}} (calculated {{M-04.calculatedOn}}).',
  },
};

export default page;
