// Generated by scripts/convert-country-pages.mjs from the 26 August 2026 handoff
// (German Pension Refund for Moroccan Citizens (2026)). Do not edit copy here — regenerate from the handoff.
// Copy as delivered in the August 2026 handoff — it carries the older service
// wording; the client will send refreshed copy later (regenerate from it then).
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'morocco',
  title: 'German Pension Refund for Moroccan Citizens (2026)',
  meta: 'No cap on contribution months for Moroccan citizens — the full employee share of your German pension is claimable. No refund, no fee.',
  h1: '🇲🇦 German Pension Refund for Moroccan Citizens',
  archetype: 'august',
  version: '26 August 2026',
  hero: [
    {
      t: 'p',
      x: 'Morocco sits in a category shared by very few nationalities: no cap on contribution months, no regional residence restriction, and a direct path to a refund once the waiting period has run. If you paid into the German pension system — for any length of time — the contributions are very likely recoverable.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Our retained completed paid cases across all nationalities show an average refund of {{M-04.meanRounded}}',
    'Completed refunds on record run from {{M-17.range}}',
    'No refund, no fee — nothing upfront',
    '{{TM-01.sentence.hero}}',
    'No German bank account required',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Are you eligible?',
      blocks: [
        {
          t: 'p',
          x: 'Three things determine whether a refund is available to you:',
          sp: [],
        },
        {
          t: 'p',
          x: 'Residence. You must currently live outside the EU, the UK and India. Morocco qualifies — as does the Gulf, North America, or anywhere else beyond those borders. (India blocks every nationality except Indian citizens — a one-off agreement quirk.)',
          sp: [
            {
              k: 'b',
              x: 'Residence.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The waiting period. At least 24 full calendar months must have elapsed since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia. The count runs from the contribution month itself — not from your Abmeldung date or your departure from Germany. One day of insured work makes the whole month count, and new mandatory insurance in a listed country restarts the count from its end.',
          sp: [
            {
              k: 'b',
              x: 'The waiting period.',
            },
          ],
        },
        {
          t: 'p',
          x: 'Your passport. Holding a German, EU, EEA, Swiss or UK passport — including one you have never used — blocks the refund entirely.',
          sp: [
            {
              k: 'b',
              x: 'Your passport.',
            },
          ],
        },
        {
          t: 'p',
          x: 'All three conditions met: you can claim. There is no minimum contribution period. There is no penalty for having worked in Germany for a long time.',
          sp: [],
        },
      ],
    },
    {
      id: 'no-60-month-ceiling-the-full',
      kind: 'sixty-month',
      h2: 'No 60-month ceiling — the full record is claimable',
      blocks: [
        {
          t: 'p',
          x: 'Germany caps the refund for citizens of several countries once contributions reach 60 months. Moroccan citizens are exempt from that restriction. Whether your German work history spans six months or fifteen years, the entire employee share is refundable once you satisfy the residence and waiting-period conditions.',
          sp: [],
        },
        {
          t: 'p',
          x: 'One point deserves precision: 60 or more months also earn a German old-age pension at retirement age, payable worldwide including Morocco — but pension and refund are alternatives, not a pair. A completed refund pays out the entire refundable balance and dissolves the old insurance relationship, so the refunded months no longer count toward any pension. Which door to take is your decision; our free eligibility check shows which ones stand open.',
          sp: [
            {
              k: 'a',
              x: 'free eligibility check',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'what-is-the-refund-worth',
      kind: 'amount',
      h2: 'What is the refund worth?',
      blocks: [
        {
          t: 'p',
          x: 'Germany deducted pension contributions at 9.3% of gross salary from 2018 onward, applied up to a monthly income ceiling — €8,450 in 2026, €8,050 in 2025. Earnings above the ceiling carried no pension deduction and form no part of the refund calculation.',
          sp: [],
        },
        {
          t: 'p',
          x: "The refund covers 100% of the employee share taken from your salary during employment. Voluntary contributions made separately — for example during a period of self-employment — are refunded at 50%. The employer's matching contributions are not refundable.",
          sp: [],
        },
        {
          t: 'p',
          x: 'Our retained completed paid cases across all nationalities show an average refund of {{M-04.mean}} and a median of {{M-04.median}} (calculated {{M-04.calculatedOn}}), with completed refunds on record from {{M-17.range}}. The spread reflects differences in salary, contribution years, and personal work history.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Use our free refund calculator →',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'our-fee',
      kind: 'cost',
      h2: 'Our fee',
      blocks: [
        {
          t: 'p',
          x: "Success-based, nothing upfront. We charge 9.75% of the refunded amount, with a ceiling of €2,500 including VAT regardless of the refund size. Included: the agreed managed administrative scope, with our partner law firm's support inside that scope, and plain-English explanations and translations of ordinary German correspondence and the decision — certified translations require a separate agreement. Separate representation in an objection, appeal or court proceeding is not included automatically.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
      ],
    },
    {
      id: 'documents-you-will-need',
      kind: 'intake',
      h2: 'Documents you will need',
      blocks: [
        {
          t: 'p',
          x: 'A valid Moroccan passport, your Versicherungsnummer (German pension insurance number) — our guide covers how to locate it — your approximate employment periods and employer names, your current address and bank details, and your Abmeldung if you still have it. Gaps are not a problem: we can help recover a missing insurance number, German deregistration is available as an optional €50 add-on (including VAT), and we obtain and review the relevant account information during the managed process where required.',
          sp: [
            {
              k: 'a',
              x: 'our guide',
              href: 'https://www.germanypensionrefund.com/post/german-social-security-number',
            },
          ],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Digital process — what that actually means',
      blocks: [
        {
          t: 'p',
          x: 'Claiming through us keeps most clients fully on screen for their entire part of the managed process: details online, electronic signatures, and our contact with the pension office within the agreed scope from that point forward.',
          sp: [],
        },
        {
          t: 'p',
          x: 'One step involves certification. We draft a Certificate of Life and Nationality — a short document confirming your identity — which a notary or another authority accepted by the responsible pension office must confirm. Online notarization is often accepted; any local notary or certification cost is borne by the client. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Contrast this with self-filing: from abroad, the pension office then generally requires paper originals, because ordinary email is not an identity-safe filing route.',
          sp: [],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Where is the refund paid?',
      blocks: [
        {
          t: 'p',
          x: 'The answer depends on where you are living when you claim.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Living outside Morocco: payment routes through the escrow account operated by our German partner law firm; after the agreed fee is deducted, the balance is transferred to the bank account you nominate. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
          sp: [
            {
              k: 'b',
              x: 'Living outside Morocco:',
            },
          ],
        },
        {
          t: 'p',
          x: 'Living in Morocco: Article 35 of the German–Moroccan social insurance agreement routes the payment via a Moroccan bank, in dirham, to an account held in your own name — residents cannot insist on payment elsewhere, and the escrow route is not available. In a bereavement claim, the account belongs to the surviving claimant. We confirm the exact route for your case before payout.',
          sp: [
            {
              k: 'b',
              x: 'Living in Morocco:',
            },
          ],
        },
      ],
    },
    {
      id: 'timeline-what-to-expect',
      kind: 'timing',
      h2: 'Timeline — what to expect',
      blocks: [
        {
          t: 'p',
          x: 'The audited picture first: {{TM-01.share}} of our {{TM-01.population}} reached the client escrow account within three months — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission — see the full data and methodology. Individual processing times vary.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
        {
          t: 'p',
          x: 'The pace is ultimately set by whichever pension office handles your case; backlogs and internal review are normal and no sign of a problem. In our latest {{M-12.total}} completed refunds, {{M-20.pct}} reached escrow within six months — and for anything slower, German law can provide 4% annual interest from the seventh calendar month after a complete application.',
          sp: [],
        },
        {
          t: 'p',
          x: 'What we contribute: files prepared to be decided without avoidable queries — a process designed to avoid preventable delays — plus a status update at least every four weeks during an active claim and known response deadlines tracked within the managed scope. Should six months ever pass without any decision, an inactivity action (Untätigkeitsklage) can become available as a case-dependent last resort; in our operating history, none has yet been required.',
          sp: [],
        },
      ],
    },
    {
      id: 'my-late-spouse-worked-in-germany',
      kind: 'family',
      h2: 'My late spouse worked in Germany — can I claim their pension refund?',
      blocks: [
        {
          t: 'p',
          x: 'In many cases, yes. Where the deceased contributed for fewer than five years, the right to claim the refund passes to the closest surviving family: spouse or registered partner first, children if no partner survives. There is no waiting period for survivors — but the right to claim expires four years after the end of the calendar year in which the death occurred. That deadline is the only hard expiry in the entire refund system, and it passes quietly if no one acts.',
          sp: [],
        },
        {
          t: 'p',
          x: "Where the deceased contributed for five years or more, the lump-sum refund is not available. A German widow's or widower's pension may be payable instead, including to recipients living in Morocco.",
          sp: [],
        },
        {
          t: 'p',
          x: "Survivors resident in Morocco at the time of claim follow the Article 35 payment rule: payment via a Moroccan bank, in dirham, to an account in the claimant's own name.",
          sp: [],
        },
        {
          t: 'p',
          x: "Full detail: our German widow's pension guide → · survivors section of the complete guide →",
          sp: [
            {
              k: 'a',
              x: "our German widow's pension guide →",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors section of the complete guide →',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
    {
      id: 'when-exactly-can-you-apply',
      kind: 'waiting-period',
      h2: 'When exactly can you apply?',
      blocks: [
        {
          t: 'p',
          x: 'The 24-month clock runs from the last month in which a mandatory contribution was made anywhere in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia — not from the date you left, not from when you cancelled your registration. Eligibility is assessed at the moment of application: taking up EU employment the day after submitting a valid claim does not undo it.',
          sp: [],
        },
        {
          t: 'p',
          x: 'A practical caution: the pension office can verify EU and UK insurance periods. A refund obtained while actually living or insured in the EU or UK can be withdrawn retrospectively, reclaimed and enforced. If there is any uncertainty about your current insurance position, ask us before filing.',
          sp: [],
        },
      ],
    },
    {
      id: 'returning-to-germany-after-your-refund',
      kind: 'other',
      h2: 'Returning to Germany after your refund',
      blocks: [
        {
          t: 'p',
          x: 'The refund settles your past record. You can move back to Germany, take up work there, and build a new pension record starting from zero.',
          sp: [],
        },
      ],
    },
    {
      id: 'faq',
      kind: 'faq',
      h2: 'Frequently asked questions',
      blocks: [],
    },
  ],
  faq: [
    {
      q: 'How is Morocco different from countries where the refund is capped at 60 months?',
      a: 'Citizens of the USA, Canada, Australia and South Korea, among others, lose access to the lump-sum refund once contributions reach 60 months. Moroccan citizens have no such restriction — the entire contribution record is refundable regardless of length, provided the other eligibility conditions are met.',
    },
    {
      q: 'Is there a minimum number of months required?',
      a: 'There is no legal minimum — a single contribution month is claimable. Our calculator gives you an estimate in under a minute.',
    },
    {
      q: 'Do local pension contributions in Morocco affect the German claim?',
      a: 'No. Contributions to any pension scheme in Morocco have no bearing on German eligibility and do not restart the 24-month waiting period.',
    },
    {
      q: 'I live in Morocco — how will my refund actually reach me?',
      a: 'Under Article 35 of the German–Moroccan agreement, the German pension office pays via a Moroccan bank, in dirham, to an account in your own name. The escrow arrangement used for claimants living elsewhere does not apply to Moroccan residents, and residents cannot insist on payment elsewhere.',
    },
    {
      q: 'What if I have lost my German insurance number or deregistration certificate?',
      a: 'Neither stops you from starting. We can help recover the Versicherungsnummer, German deregistration is available as an optional €50 add-on (including VAT), and we obtain and review the relevant account information during the managed process where required.',
    },
    {
      q: 'What is the fee, and when is it charged?',
      a: '9.75% of the refunded amount, capped at €2,500 including VAT, charged only after your refund has been paid — no upfront payment, no minimum fee, covering the agreed managed administrative scope. Separate representation in an objection, appeal or court proceeding is not included automatically.',
    },
    {
      q: 'My late spouse passed away — does the four-year deadline apply to me?',
      a: 'Yes. The right to claim a survivors refund expires four years after the end of the calendar year of death. If that window has not yet closed, contact us promptly.',
    },
  ],
  schemaFaq: [
    {
      q: 'Do Moroccan citizens have a 60-month limit for the German pension refund?',
      a: 'No. Moroccan citizens face no cap on contribution months — the entire employee share is refundable regardless of length, provided residence is outside the EU, the UK and India and at least 24 months have passed since the last mandatory pension contribution in Germany, the EU, the UK, Türkiye or an ex-Yugoslav country.',
    },
    {
      q: 'How is the refund paid to residents of Morocco?',
      a: "Under Article 35 of the German–Moroccan social insurance agreement, the German pension office pays via a Moroccan bank, in dirham, to an account held in the claimant's own name; residents cannot insist on payment elsewhere, and the partner law firm's escrow route does not apply. Claimants living outside Morocco are paid through the escrow route to the account they nominate.",
    },
    {
      q: 'Do Moroccan pension contributions affect the German claim?',
      a: 'No. Contributions to any pension scheme in Morocco have no bearing on German eligibility and do not restart the 24-month waiting period.',
    },
    {
      q: 'What about a pension instead of a refund?',
      a: 'With 60 or more contribution months a German old-age pension at retirement age is the alternative — but refund and pension are alternatives, not a pair: a completed refund pays out the entire refundable balance and dissolves the old insurance relationship, so the refunded months no longer count toward a pension.',
    },
    {
      q: 'How much does the service cost?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT, charged only after the refund is paid — no upfront payment and no minimum fee. It covers the agreed managed administrative scope including our partner law firm's support within that scope; separate objection, appeal or court representation is not included automatically. No refund, no fee.",
    },
    {
      q: 'How long does a German pension refund take?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission; {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  close: [
    {
      t: 'p',
      x: 'No cap on months, no upfront cost, one clear promise: you pay only when your money arrives. Starting your claim takes less than one minute.',
      sp: [],
    },
    {
      t: 'cta',
      items: [
        {
          label: 'free refund calculator',
          href: '/refund-calculator',
        },
        {
          label: 'Claim your refund now',
          href: '/get-your-refund',
        },
      ],
    },
  ],
  closeTitle: 'Claim your pension refund today',
  closeDisclaimer: false,
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Moroccan Citizens',
    audienceType:
      'Moroccan citizens who contributed to the German pension system',
    description:
      'Managed handling of German state pension contribution refunds for Moroccan citizens, who face no 60-month contribution cap. No upfront payment and no minimum fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. Our retained completed paid cases across all nationalities show an average refund of {{M-04.mean}} (calculated {{M-04.calculatedOn}}).',
  },
};

export default page;
