// Generated by scripts/convert-country-pages.mjs from the 26 August 2026 handoff
// (German Pension Refund for North Macedonian Citizens (2026)). Do not edit copy here — regenerate from the handoff.
// Copy as delivered in the August 2026 handoff — it carries the older service
// wording; the client will send refreshed copy later (regenerate from it then).
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'north-macedonia',
  title: 'German Pension Refund for North Macedonian Citizens (2026)',
  meta: 'Under 60 German contribution months? North Macedonian citizens can claim them back — living at home is fine, only mandatory local insurance delays.',
  h1: '🇲🇰 German Pension Refund for North Macedonian Citizens',
  archetype: 'august',
  version: '26 August 2026',
  hero: [
    {
      t: 'p',
      x: 'As a North Macedonian citizen, you can claim a German pension refund if you contributed for fewer than 60 months in total, at least 24 months have passed since your last mandatory pension contribution in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia, you live outside the EU, the UK and India — and you are not currently paying mandatory pension contributions in North Macedonia. Living at home itself is no obstacle: unlike neighbors from Bosnia, Serbia or Montenegro, you are only paused while mandatory local insurance runs.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'Among our retained completed paid cases across all nationalities, the average refund was {{M-04.meanShort}}',
    'Retained records hold completed refunds from {{M-17.range}}',
    'No German bank account required',
    'No refund, no fee — success-based only',
    '{{TM-01.sentence.hero}}',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Who can claim as a North Macedonian citizen?',
      blocks: [
        {
          t: 'p',
          x: 'All of the following must hold:',
          sp: [],
        },
        {
          t: 'p',
          x: 'You are not currently paying mandatory pension contributions in North Macedonia. Unlike citizens of Bosnia, Serbia or Montenegro — blocked simply by living in those countries — North Macedonian citizens are only blocked while subject to mandatory pension insurance there. Living in North Macedonia without mandatory local contributions leaves the route open once the waiting period has passed.',
          sp: [
            {
              k: 'b',
              x: 'You are not currently paying mandatory pension contributions in North Macedonia.',
            },
          ],
        },
        {
          t: 'p',
          x: 'You contributed for fewer than 60 months in total. Every worked month counts, including months credited for unemployment benefits or child-raising periods. At 60 or more, the lump sum gives way to a German old-age pension at retirement age — payable worldwide, North Macedonia included.',
          sp: [
            {
              k: 'b',
              x: 'You contributed for fewer than 60 months in total.',
            },
          ],
        },
        {
          t: 'p',
          x: 'At least 24 months have passed since your last mandatory contribution. The clock starts from the last contribution month itself — not your deregistration date. Mandatory contributions in North Macedonia restart this clock from the month they end, exactly like contributions in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro or Serbia.',
          sp: [
            {
              k: 'b',
              x: 'At least 24 months have passed since your last mandatory contribution.',
            },
          ],
        },
        {
          t: 'p',
          x: "You live outside the EU, the UK and India — and you hold no German, EU, EEA, Swiss or UK passport; a second passport blocks even unused. (India's spot on the residence list is a quirk: living there blocks every nationality except Indian citizens.)",
          sp: [
            {
              k: 'b',
              x: 'You live outside the EU, the UK and India',
            },
          ],
        },
      ],
    },
    {
      id: 'the-60-month-line',
      kind: 'sixty-month',
      h2: 'The 60-month line',
      blocks: [
        {
          t: 'p',
          x: 'Below 60 contribution months, the full employee share is refundable once the insurance and waiting conditions are met; from 60, the account has instead earned a pension at retirement age, wherever you then live. Counting favors you — one insured day fills a month, and credited unemployment or child-raising periods add to the total. Our free eligibility check gives a preliminary reading in about a minute; we review the official record during the managed process where required.',
          sp: [
            {
              k: 'a',
              x: 'free eligibility check',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'one-important-exception-voluntary-contributions-1969',
      kind: 'other',
      h2: 'One important exception — voluntary contributions 1969–2004',
      blocks: [
        {
          t: 'p',
          x: 'If you made even a single voluntary contribution to the German pension system for any period between September 1969 and December 2004 while abroad, German law treats those contributions as preserving ongoing voluntary-insurance rights — and the lump-sum refund closes regardless of your total months. If this could apply to you, ask us before applying; the pension-at-retirement route may remain open.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-is-in-it',
      kind: 'amount',
      h2: 'How much is in it?',
      blocks: [
        {
          t: 'p',
          x: "Among our retained completed paid cases across all nationalities, the average refund was {{M-04.mean}} and the median {{M-04.median}} (calculated {{M-04.calculatedOn}}) — retained records hold completed refunds from {{M-17.range}}. The composition is fixed: 100% of the mandatory contributions deducted from your salary, 50% of voluntary or self-employed contributions, and none of the employer's matching share. Rate and ceiling: 9.3% of gross salary since 2018, up to €8,450 per month in 2026 (2025: €8,050); income above the ceiling carried no deductions.",
          sp: [],
        },
        {
          t: 'p',
          x: 'Use our free refund calculator →',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'what-we-charge',
      kind: 'cost',
      h2: 'What we charge',
      blocks: [
        {
          t: 'p',
          x: "9.75% of the refunded amount, capped at €2,500 including VAT, due only after your refund has been transferred — nothing upfront, no minimum fee. The cap covers the agreed managed administrative scope, our partner law firm's support within that scope included, and ordinary German correspondence and the decision are explained and translated into English as part of the service; certified translations need a separate agreement. Separate representation in an objection, appeal or court proceeding is not included automatically.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
      ],
    },
    {
      id: 'the-document-list',
      kind: 'intake',
      h2: 'The document list',
      blocks: [
        {
          t: 'p',
          x: 'Your North Macedonian passport; the German pension number (Versicherungsnummer — where it hides); rough employment dates and employers; address and payout account; Abmeldung if you kept it. Nothing fatal is missing if something is: we can help recover the pension number, German deregistration is available as an optional €50 add-on (including VAT), and we obtain and review the relevant account information during the managed process where required.',
          sp: [
            {
              k: 'a',
              x: 'where it hides',
              href: 'https://www.germanypensionrefund.com/post/german-social-security-number',
            },
          ],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Online, except one stamp',
      blocks: [
        {
          t: 'p',
          x: 'For most clients, the entire client side of the managed process is digital, with the pension-office correspondence handled by us within the agreed scope. One document leaves the screen: the Certificate of Life and Nationality we prepare, to be confirmed by a notary or another authority accepted by the responsible pension office — online notarization is often accepted, and any local notary or certification cost is borne by the client. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule. Going it alone from abroad usually means paper, because ordinary email is not an identity-safe filing route.',
          sp: [],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Payment without a German account',
      blocks: [
        {
          t: 'p',
          x: 'Not needed at any point: the refund lands in the escrow account operated by our German partner law firm, the agreed fee comes off, and the remainder is transferred to the bank account you nominate — North Macedonian accounts included. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-fast-does-it-move',
      kind: 'timing',
      h2: 'How fast does it move?',
      blocks: [
        {
          t: 'p',
          x: 'Measured, not promised: {{TM-01.share}} of our {{TM-01.population}} reached the client escrow account within three months — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission — see the full data and methodology. Individual processing times vary with the office deciding your case; {{M-20.pct}} of our latest {{M-12.total}} completed refunds reached escrow within six months, and slower cases lose nothing — German law can provide 4% annual interest from the seventh calendar month after a complete application.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
        {
          t: 'p',
          x: 'Our end never goes quiet: files built to be decided without avoidable queries — a process designed to avoid preventable delays — a status update at least every four weeks during an active claim, and known response deadlines tracked within the managed scope. After six months without any decision, an inactivity action (Untätigkeitsklage) can become available as a case-dependent last resort; in our operating history, none has yet been required.',
          sp: [],
        },
      ],
    },
    {
      id: 'a-late-spouses-or-parents-contributions',
      kind: 'family',
      h2: "A late spouse's or parent's contributions",
      blocks: [
        {
          t: 'p',
          x: "Where the deceased stayed under the five-year qualifying period, the closest surviving family can reclaim the contributions — spouse or registered partner first, then children — with no waiting period and one hard deadline: four years after the end of the year of death. At five years or more, no contribution refund — a German widow's or widower's pension may be payable instead, worldwide, North Macedonia included. Both paths: German widow's pension guide → · survivors chapter of the complete guide →",
          sp: [
            {
              k: 'a',
              x: "German widow's pension guide →",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide →',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
    {
      id: 'the-application-date-decides',
      kind: 'waiting-period',
      h2: 'The application date decides',
      blocks: [
        {
          t: 'p',
          x: "Eligibility is assessed on the day you file. A validly filed claim survives a move back to Europe the very next day; conversely, mandatory insurance in a listed country — North Macedonia's included — before filing restarts the 24 months from its end. And openly: the pension office can verify EU and UK insurance periods. A refund obtained while actually living or insured in the EU or UK can be withdrawn retrospectively, reclaimed and enforced. Uncertain? One question to us costs nothing and settles it.",
          sp: [],
        },
      ],
    },
    {
      id: 'faq',
      kind: 'faq',
      h2: 'Frequently asked questions',
      blocks: [],
    },
  ],
  faq: [
    {
      q: 'I live in North Macedonia — am I blocked from claiming?',
      a: 'Not automatically. Unlike citizens of Bosnia, Serbia or Montenegro, you are only blocked while paying mandatory pension contributions locally. Without mandatory local insurance, the route can be open once the 24-month waiting period has passed.',
    },
    {
      q: 'Does paying into the North Macedonian pension restart the 24-month clock?',
      a: 'Yes. Mandatory contributions in North Macedonia restart the waiting period from the month they end — the same as contributions in Germany, the EU or the UK.',
    },
    {
      q: 'What if I made voluntary German contributions between 1969 and 2004?',
      a: 'Even one voluntary contribution for a period between September 1969 and December 2004, paid from abroad, closes the lump-sum route regardless of your total months. Ask us before applying — the pension at retirement age may remain available.',
    },
    {
      q: 'What happens at 60 months or more?',
      a: 'The lump sum closes; in its place stands a German old-age pension at retirement age, payable wherever you live — North Macedonia included.',
    },
    {
      q: 'What is the fee?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT — nothing upfront, no minimum, covering the agreed managed administrative scope including our partner law firm's support within that scope. Separate representation in an objection, appeal or court proceeding is not included automatically. No refund, no fee.",
    },
    {
      q: 'Do I need a German bank account?',
      a: 'No — escrow first (operated by our German partner law firm), then the account you nominate, North Macedonian accounts included. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
    },
    {
      q: 'How long does it take?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission; {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  schemaFaq: [
    {
      q: 'Can North Macedonian citizens living at home claim a German pension refund?',
      a: 'Living in North Macedonia is not itself a block — unlike citizens of Bosnia, Serbia or Montenegro, North Macedonian citizens are only blocked while paying mandatory pension contributions locally. Without mandatory local insurance, the route can be open once the 24-month waiting period has passed, with fewer than 60 German contribution months and residence outside the EU, the UK and India.',
    },
    {
      q: 'Does the North Macedonian state pension restart the waiting period?',
      a: 'Yes. Mandatory pension contributions in North Macedonia restart the 24-month waiting period from the month they end — the same as contributions in Germany, the EU, the UK, Türkiye or the other ex-Yugoslav states.',
    },
    {
      q: 'What is the 1969–2004 voluntary-contribution exception?',
      a: 'Even a single voluntary contribution to the German pension system for a period between September 1969 and December 2004, paid from abroad, preserves voluntary-insurance rights and closes the lump-sum refund regardless of total months. The pension at retirement age may remain available.',
    },
    {
      q: 'What happens at 60 contribution months or more?',
      a: 'The lump-sum refund is no longer available; instead the account has earned a German old-age pension payable at retirement age worldwide, including in North Macedonia.',
    },
    {
      q: 'How much does the service cost?',
      a: "9.75% of the refunded amount, capped at €2,500 including VAT — nothing upfront and no minimum fee, covering the agreed managed administrative scope including our partner law firm's support within that scope. Separate representation in an objection, appeal or court proceeding is not included automatically. No refund, no fee.",
    },
    {
      q: 'How long does a German pension refund take?',
      a: '{{TM-01.sentence.hero}} — {{M-12.count}} of {{M-12.total}} ({{M-12.pct}}) within {{M-12.days}} days of complete submission; {{M-20.pct}} reached escrow within six months. Individual processing times vary; the responsible pension office controls processing.',
    },
  ],
  close: [
    {
      t: 'p',
      x: 'You pay only when your money arrives — and starting your claim takes less than one minute.',
      sp: [],
    },
    {
      t: 'cta',
      items: [
        {
          label: 'free refund calculator',
          href: '/refund-calculator',
        },
        {
          label: 'Claim your refund now',
          href: '/get-your-refund',
        },
      ],
    },
  ],
  closeTitle: 'Claim your pension refund today',
  closeDisclaimer: false,
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for North Macedonian Citizens',
    audienceType:
      'North Macedonian citizens who contributed to the German pension system',
    description:
      'Managed handling of German state pension contribution refunds for North Macedonian citizens. No upfront payment and no minimum fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. Among our retained completed paid cases across all nationalities, the average refund was {{M-04.mean}} (calculated {{M-04.calculatedOn}}).',
  },
};

export default page;
