// Generated by scripts/convert-country-pages.mjs from the v1.2 handoff
// (German Pension Refund for Pakistani Citizens (2026)). Do not edit copy here — regenerate from the handoff.
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'pakistan',
  title: 'German Pension Refund for Pakistani Citizens (2026)',
  meta: 'No 60-month limit for Pakistani citizens: claim your German pension contributions back from Pakistan, the Gulf or almost anywhere outside the EU and UK.',
  h1: '🇵🇰 German Pension Refund for Pakistani Citizens',
  archetype: 'citizenship',
  version: 'v1.2',
  hero: [
    {
      t: 'p',
      x: 'Worked in Germany, now back in Pakistan or living in the Gulf? The pension contributions deducted from your German salary can be paid back to you in one sum — and for Pakistani citizens there is no contribution-month limit: 20 German months or 120, the refund route stays open. Three conditions decide it: no German, EU, EEA, Swiss or British citizenship alongside your Pakistani one; a home outside the EU, the UK and India; and 24 full calendar months since your last mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state.',
      sp: [],
    },
    {
      t: 'p',
      x: 'We check your eligibility, prepare your application and payment documents, and coordinate your claim with our German partner law firm, which reviews and submits it. Along the way you get plain-English explanations of your pension-office letters, regular updates, and support that continues after the decision. No refund, no service fee.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'No contribution-month limit for Pakistani citizens — 60 German months or more stay refundable',
    '{{M-04.sentence.hero}}',
    '{{TM-01.sentence.hero}}',
    'No German bank account required · No refund, no service fee · No minimum service fee',
  ],
  sections: [
    {
      id: 'do-i-qualify',
      kind: 'qualify',
      h2: 'Do I qualify for a German pension refund as a Pakistani citizen?',
      blocks: [
        {
          t: 'p',
          x: 'Short answer: yes, if three things are true on the day your application is filed — and none of them is the length of your German record. Pakistan and Germany have no social security agreement, and that is good news: agreements are what create limits, and without one plain German law applies — the three conditions below are the whole test.',
          sp: [
            {
              k: 'a',
              x: 'social security agreement',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Sozialversicherungsabkommen/sozialversicherungsabkommen_detailseite.html',
            },
          ],
        },
        {
          t: 'h3',
          x: 'Citizenship — every passport you hold counts',
        },
        {
          t: 'p',
          x: "The refund is open to you as a Pakistani citizen as long as you hold no German, EU, EEA, Swiss or British citizenship alongside it. One such citizenship — with or without a passport in the drawer — blocks the refund before German retirement age on its own. It deserves a hard look in Pakistan's case: Pakistan allows dual nationality with the United Kingdom, Germany and a dozen other European countries, so British citizenship from years in Manchester or German citizenship taken by naturalization closes the refund route, whatever your Pakistani passport says. A second citizenship from one of the eleven 60-month countries — the USA, Canada or Australia, for example — does not block the refund but brings that country's 60-month limit with it. (One narrow exception exists for people who left mandatory German insurance as civil servants or in a similar status; the complete guide covers it.)",
          sp: [
            {
              k: 'a',
              x: 'complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
        {
          t: 'p',
          x: 'The date that counts is the day your application is filed: the pension office assesses your citizenship, residence and waiting period as they stand on that date, and later changes are not taken into account. A naturalization completed after filing therefore leaves a valid claim untouched; one completed before filing blocks it. The test is the citizenship itself, not the passport — citizenship by descent can exist from birth whether or not a passport was ever issued. If a second citizenship is anywhere in your plans or your family tree, raise it with us before anything is filed; we check the sequence with you first.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'Residence — outside the EU, the UK and India',
        },
        {
          t: 'p',
          x: 'Where you live on the filing date is the second test, and for a Pakistani citizen almost every address in the world passes it: Pakistan itself, the Gulf states, North America, Australia, East Asia — and Norway, Iceland, Liechtenstein and Switzerland, which count as outside the EU for this purpose. Two regions fail it. Living in the EU or the UK blocks the refund for as long as you live there (a visit is fine; living there is not; one narrow exception aside). And living in India blocks it too: under the Germany–India agreement, one German contribution month gives anyone living in India the right to voluntary German insurance, and that right closes the refund for every nationality except Indian citizens — a Pakistani citizen living in India waits until moving on (our India page explains the rule). Living in Türkiye or an ex-Yugoslav state passes, but mandatory state pension insurance there blocks the refund while it lasts and restarts the 24 months.',
          sp: [
            {
              k: 'a',
              x: 'our India page',
              href: 'https://www.germanypensionrefund.com/india',
            },
          ],
        },
        {
          t: 'h3',
          x: 'The 24-month waiting period — counted from your last contribution month, not from the day you left',
        },
        {
          t: 'p',
          x: 'The third test is time: 24 full calendar months must lie between your last mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state (Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia) and your application — Deutsche Rentenversicherung states the rule the same way. What starts that clock is your last contribution month — not your deregistration (Abmeldung), not your flight home, not the end of your residence permit. Count 24 full months from the end of that month; the first day of the 25th month is the earliest filing date; filing earlier gains nothing — the period does not shorten, and extra confirmation requests can follow.',
          sp: [
            {
              k: 'a',
              x: 'states the rule the same way',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Allgemeine-Informationen/Wissenswertes-zur-Rente/FAQs/International/Erstattung.html',
            },
          ],
        },
        {
          t: 'p',
          x: 'What restarts the clock is new mandatory insurance in one of the listed places — and the UK is on that list. A Pakistani engineer who leaves Berlin for a job in London is insured in the UK from the first payslip: the refund is blocked while they live there, and the 24 months only begin after their last UK contribution month. A local job in Pakistan, the Gulf, the USA or Canada — with no compulsory German pension insurance continuing under a posting from Germany — does nothing to the clock, and for a Pakistani citizen, mandatory insurance in Switzerland, Norway, Iceland or Liechtenstein does not restart it either. No deadline applies to a first application; no interest is paid for the years before it. Our waiting-period calculator gives you the exact date.',
          sp: [
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'what-we-do',
      kind: 'service',
      h2: 'What we do for you — and what it costs',
      blocks: [
        {
          t: 'p',
          x: 'Before anything is filed. You provide your details, documents and signatures; we do the rest of the preparation. We check your eligibility, obtain and review the relevant DRV account information during the managed process where required, prepare your refund application and payment documents, identify the recommended first pension office from your record and coordinate the claim with our German partner law firm, which reviews and submits it.',
          sp: [
            {
              k: 'b',
              x: 'Before anything is filed.',
            },
          ],
        },
        {
          t: 'p',
          x: 'While the pension office works. Pension-office letters for your claim are received at a German address, scanned to you and explained in plain English. After your claim is submitted, you receive an update at least every four weeks — even when the update is that no pension-office response has arrived. If there is still no decision six months after submission, updates come at least every two weeks, whether or not a formal complaint has been filed. Material requests and developments are communicated sooner. If we are still waiting for a decision three months after submission, we contact the pension office to check where the application stands. We keep track of known response and objection deadlines within the agreed scope; if a letter reaches you directly, forward it to us straight away with the date you received it — only deadlines known to us or our partner law firm can be protected.',
          sp: [
            {
              k: 'b',
              x: 'While the pension office works.',
            },
          ],
        },
        {
          t: 'p',
          x: "After the decision. Our managed service includes checking the pension office's decision against your record and evidence. If contribution periods you can evidence — payslips, for example — are missing from the refund statement, a straightforward objection is included in the service fee: we draft it from our standard template and your evidence, and it goes to the pension office; no extra cost. If the disagreement is a legal question — for example, the office rejects the refund on a legal ground you could not be expected to assess yourself — objection representation is separate work by our partner law firm, agreed directly between you and the firm at its own cost, outside the service scope. If an approved refund does not arrive, we follow it up within the managed scope with the pension office and Renten Service until the payment is resolved.",
          sp: [
            {
              k: 'b',
              x: 'After the decision.',
            },
          ],
        },
        {
          t: 'p',
          x: "Our fee is 9.75% of the refunded amount, capped at €2,500 including VAT, with no upfront service fee and no minimum service fee. No refund, no service fee. The fee covers the agreed managed administrative scope, including our partner law firm's support within that scope. We do not provide legal services, advice or representation; separate representation in an objection, appeal or court proceeding is not included automatically. German deregistration is available as an optional €50 add-on including VAT, payable with the service fee after your refund reaches escrow — and if your German pension insurance number has gone missing, we can help identify or recover it.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
        {
          t: 'p',
          x: '{{TM-01.sentence}} {{M-12.sentence}} Individual processing times vary — see the full data and methodology. Processing and payment dates depend on the responsible pension office and the payment route, so a specific date cannot be guaranteed; the process is designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      id: 'what-you-need-to-start',
      kind: 'intake',
      h2: 'What you need to start',
      blocks: [
        {
          t: 'p',
          x: 'To get started, upload a copy of your passport, a payslip from your time in Germany and your deregistration confirmation (Abmeldebestätigung). Your account guides you through the questions and documents. Missing your German pension number? We help recover it. Not deregistered yet? We offer deregistration assistance for €50 including VAT. If your claim needs additional documents or signed originals by post, we explain exactly what to provide.',
          sp: [],
        },
      ],
    },
    {
      id: 'is-there-a-60-month-limit',
      kind: 'sixty-month',
      h2: 'Is there a 60-month limit for Pakistani citizens?',
      blocks: [
        {
          t: 'p',
          x: "No. Citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay — and Japanese citizens, recognized refugees and stateless persons living in Japan — can claim a refund before retirement age only with 59 or fewer German months — contribution months plus the German months credited to the account (child-raising periods, for instance, or months on unemployment benefit, though not every line of the insurance record counts) — and nothing from any other country counts toward those 60; for Pakistani citizens that limit does not exist, because no agreement between Germany and Pakistan grants voluntary German insurance rights. Three German years or twelve: once the three conditions hold, the whole refundable balance comes back. Two groups should read that list twice: a Pakistani citizen who also holds a citizenship of one of those eleven countries carries that country's limit, and a recognized refugee or stateless person is treated like a citizen of the country where they live.",
          sp: [],
        },
        {
          t: 'p',
          x: 'A long record changes your decision rather than your eligibility. From 60 German contribution months, a Pakistani citizen has also earned a German old-age pension, payable anywhere in the world — Pakistan included — at German retirement age, and the refund is strictly the alternative to it: one payment of the entire refundable balance, after which the old insurance relationship is dissolved and the refunded months never turn back into pension months (later German work builds new entitlements from new contribution periods). With many German years, compare both before you choose — a lifelong pension can be worth more than one payment now. At German retirement age, under five qualifying years (allgemeine Wartezeit) a refund is possible without any waiting period; with five years or more you have a pension, and the refund option that formally stays open to Pakistani citizens would trade it away for good — ask us before deciding.',
          sp: [],
        },
      ],
    },
    {
      id: 'does-your-eobi-pension-or-any',
      kind: 'local-scheme',
      h2: 'Does your EOBI pension — or any other Pakistani scheme — affect the refund?',
      blocks: [
        {
          t: 'p',
          x: "No. Contributions to Pakistan's Employees' Old-Age Benefits Institution (EOBI), to a provincial social security institution, to a provident fund or to any private retirement plan never block the German refund, never restart the 24 months, and never count toward any German month total. The only foreign insurance that blocks a refund or restarts the waiting period is mandatory pension insurance in the EU, the UK, Türkiye or an ex-Yugoslav state — a scheme matters because it is on that list, not because it is compulsory. So an EOBI-registered employee in Karachi with four German years behind them has four German years for the refund and a clock that started with the last German contribution month; nothing needs to be certified, transferred or added up between the two systems.",
          sp: [],
        },
      ],
    },
    {
      id: 'journeys',
      kind: 'journeys',
      h2: 'Two illustrative journeys — on to the Gulf, on to the UK',
      blocks: [
        {
          t: 'note',
          x: 'Worked examples, not client cases.',
        },
        {
          t: 'p',
          x: 'The software engineer. Six years in Berlin on an EU Blue Card (72 months, 2019–2024) at €5,500 gross, then a move to Dubai. For a citizen of one of the eleven 60-month countries — the USA or India, say — 72 German contribution months would close the refund route before retirement age; for a Pakistani citizen it stays open — €511.50 a month, roughly €36,800 in refundable employee contributions — and living in the UAE has no effect on the claim. What 72 months do change is the choice: a German pension at retirement age has also been earned, and a completed refund gives it up for good. Worth a calculation before signing anything.',
          sp: [
            {
              k: 'b',
              x: 'The software engineer.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The doctor. Four years of specialist training at a hospital in North Rhine-Westphalia with German pension contributions throughout, then a hospital post in Birmingham from 2024. While she lives in the UK the refund is blocked, and her UK contributions restart the 24 months — so if she moves on to Riyadh in 2027, her earliest application date is the first day of the 25th month after her last UK contribution month. The German months themselves keep: nothing expires while she waits.',
          sp: [
            {
              k: 'b',
              x: 'The doctor.',
            },
          ],
        },
        {
          t: 'p',
          x: 'Run your own months through the free refund calculator.',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'which-of-your-years-in-germany',
      kind: 'years',
      h2: 'Which of your years in Germany actually paid pension contributions?',
      blocks: [
        {
          t: 'p',
          x: 'The question for every stretch in Germany is whether statutory pension insurance applied. For the common paths — study, skilled work, medicine, self-employment:',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: 'Employment based in Germany — on an EU Blue Card, a skilled-worker permit or any other work permit — or an Ausbildung contract: pension insurance from the first day; each month counts and its employee share comes back.',
              sp: [
                {
                  k: 'b',
                  x: 'Employment based in Germany — on an EU Blue Card, a skilled-worker permit or any other work permit — or an Ausbildung contract:',
                },
              ],
            },
            {
              x: "A Werkstudent job alongside a degree: students are spared health, care and unemployment insurance — not pension insurance. Above the minijob limit your months count and the contributions are refundable; for pay inside the reduced-contribution band (the Übergangsbereich, up to €2,000 a month, where many Werkstudent jobs sit) the refund follows a special rule — half of the total pension contributions paid for those months — so do not simply multiply your gross pay by 9.3% (for years before 2023 the band's upper limit was lower, so the year decides).",
              sp: [
                {
                  k: 'b',
                  x: 'A Werkstudent job alongside a degree:',
                },
              ],
            },
            {
              x: "A minijob: if you paid the small employee top-up (the default since 2013), that share is refundable; if you opted out, only your employer's flat-rate contributions flowed, so there is nothing of yours to refund — and such months neither block nor restart the 24-month waiting period, though they can still earn partial credit toward the five-year qualifying period.",
              sp: [
                {
                  k: 'b',
                  x: 'A minijob:',
                },
              ],
            },
            {
              x: 'A scholarship — a DAAD- or HEC-funded PhD stipend without an employment contract, for example: no employment, no pension contributions, nothing to count from those months.',
              sp: [
                {
                  k: 'b',
                  x: 'A scholarship — a DAAD- or HEC-funded PhD stipend without an employment contract, for example:',
                },
              ],
            },
            {
              x: "Specialist training as an employed doctor: insured like any other employee — unless you were exempted from the German pension insurance in favour of a doctors' pension fund (Versorgungswerk). Exempted months sit with that fund, not with Deutsche Rentenversicherung, and are not part of this refund.",
              sp: [
                {
                  k: 'b',
                  x: 'Specialist training as an employed doctor:',
                },
              ],
            },
            {
              x: 'Freelance or self-employed work: usually no mandatory pension insurance at all; voluntary contributions and the compulsory contributions of self-employed people are refunded at 50%.',
              sp: [
                {
                  k: 'b',
                  x: 'Freelance or self-employed work:',
                },
              ],
            },
          ],
        },
        {
          t: 'p',
          x: "Memory is a poor witness here — the official insurance record (Versicherungsverlauf) decides, and you don't need to obtain it yourself first: we obtain and review the relevant DRV account information during the managed process where required.",
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-comes-back-and-what',
      kind: 'amount',
      h2: 'How much comes back — and what about tax in Pakistan?',
      blocks: [
        {
          t: 'p',
          x: "What comes back is your employee share: since 2018, 9.3% of gross pay up to the monthly contribution ceiling (Beitragsbemessungsgrenze — €8,450 in 2026, €8,050 in 2025), and as a rule all of it. Pay above the ceiling was never charged, so there is nothing to refund on it; the employer's half stays in the system. Three exceptions are worth knowing before you count: voluntary contributions and the compulsory contributions of self-employed people come back at 50%; months in the Übergangsbereich (monthly pay up to €2,000) are refunded at half of the total contributions paid for them; and if you ever received a benefit funded by Deutsche Rentenversicherung — a rehabilitation programme, for example — only the contributions paid after it are refundable, while the completed refund still closes the whole record. We check these before anything is filed. The legal basis is § 210 SGB VI.",
          sp: [
            {
              k: 'a',
              x: '§ 210 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__210.html',
            },
          ],
        },
        {
          t: 'p',
          x: '{{M-04.sentence}} Our refund calculator applies the actual statutory employee contribution rate and monthly ceiling (Beitragsbemessungsgrenze) of every year back to 1975 — including Deutsche-Mark periods and East/West differences — rather than a flat percentage.',
          sp: [
            {
              k: 'a',
              x: 'refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
        {
          t: 'p',
          x: 'Germany takes no income tax off the refund — German law exempts pension contribution refunds, and the Federal Fiscal Court has confirmed it. How Pakistan treats money arriving from abroad, and what you may need to report there, is a question for a local adviser; we cannot advise on tax.',
          sp: [],
        },
      ],
    },
    {
      id: 'which-german-pension-office-handles-a',
      kind: 'office',
      h2: "Which German pension office handles a Pakistani citizen's claim?",
      blocks: [
        {
          t: 'p',
          x: 'Not one fixed office — and not automatically Berlin. The responsible office follows a fixed order: insurance record first, then citizenship, then residence. DRV Knappschaft-Bahn-See if you were ever insured there; otherwise DRV Bund if it was the last office holding your account; otherwise the liaison office assigned to a second citizenship where you hold one (DRV Nord for a US or Canadian citizen) — Pakistan itself has none, so a Pakistani citizen with no other citizenship skips this step; otherwise the liaison office for your country of residence, if that country has one — a Pakistani citizen living in the USA or Canada starts with DRV Nord, one living in Australia with DRV Oldenburg-Bremen; otherwise the regional office that holds your account, wherever in the world you live. Send the claim to the wrong office and the filing date survives, but the forwarding costs weeks.',
          sp: [],
        },
        {
          t: 'p',
          x: 'Our guide to the responsible pension office walks through the rules and includes the office finder. In a managed claim we identify the recommended office from your record, and our German partner law firm files the claim there.',
          sp: [
            {
              k: 'a',
              x: 'Our guide to the responsible pension office',
              href: 'https://www.germanypensionrefund.com/post/which-german-pension-office-handles-your-claim',
            },
          ],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Getting paid in Pakistan — or wherever you live now',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account is required. In a claim we manage, your refund is paid through the escrow account operated by our German partner law firm; after the agreed service fee is deducted, the remaining balance is transferred to the bank account you nominate — a third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent, so the route for a transfer to Pakistan or elsewhere is checked shortly before the money moves.',
          sp: [],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Digital for most clients — and the paper route if you apply yourself',
      blocks: [
        {
          t: 'p',
          x: 'Most clients can complete their entire part of the process digitally: you submit your details and sign online. Every client has their identity and signature confirmed using their passport or an accepted equivalent; depending on the route, that confirmation can be completed digitally or, where a certified signature is needed, in person. Where one is needed, we prepare the document and you have it certified by one certifier — no combination of certifiers is ever required. The German Embassy in Islamabad or the Consulate General in Karachi certifies signatures on documents for use with a German authority whatever your nationality, by appointment, and is the route to try first — usually the cheaper one; the alternative is a notary public or another local authority whose certification the responsible pension office accepts for that particular document. Required local certification, notary or translation costs are borne by the client. If DRV Oldenburg-Bremen is responsible for your refund — for a Pakistani citizen that is the usual result of living in Australia, unless Knappschaft-Bahn-See ever insured you or DRV Bund was the last carrier of your account — we prepare the power of attorney and payment declaration and ask you to send us the signed originals. For everyone else this is a limited exception rather than the rule.',
          sp: [],
        },
        {
          t: 'p',
          x: 'You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. From Pakistan or the Gulf that route is paper: form V0901 travels by post, because ordinary email is not accepted for identity reasons and fax is no longer available. In a self-filed claim, the official application form provides for your personal data to be certified on the form itself — so the application travels to the certifying body: the German mission, or a notary or other authority whose certification the pension office accepts for that form. In a managed claim, the analog step is a single page we prepare for you. Our V0901 guide walks through the form section by section, and the pension-office guide tells you where to send it.',
          sp: [
            {
              k: 'a',
              x: 'V0901 guide',
              href: 'https://www.germanypensionrefund.com/v0901-pension-refund-form-english',
            },
            {
              k: 'a',
              x: 'pension-office guide',
              href: 'https://www.germanypensionrefund.com/post/which-german-pension-office-handles-your-claim',
            },
          ],
        },
      ],
    },
    {
      id: 'a-family-members-german-contributions',
      kind: 'family',
      h2: "A family member's German contributions",
      blocks: [
        {
          t: 'p',
          x: "If a spouse, registered partner or parent died with German contributions on record and their German record stayed under the five-year qualifying period (allgemeine Wartezeit), the closest family — the surviving spouse or registered partner and, in the cases the law provides for, the children — can claim a refund of those contributions. Survivors skip the 24-month wait, but the claim can become time-barred four years after the end of the year of death. A record of five years or more leaves no refund for anyone; what may exist instead is a German survivor's pension, payable worldwide, Pakistan included. Who can claim, in which order and with what evidence: our German widow's pension guide and the survivors chapter of the complete guide.",
          sp: [
            {
              k: 'a',
              x: "our German widow's pension guide",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
  ],
  faq: [
    {
      q: 'Is there a 60-month limit on the German pension refund for Pakistani citizens?',
      a: 'No. The 60-month limit binds citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay, and Japanese citizens, recognized refugees and stateless persons living in Japan — and even for them only German months count toward the 60 (contribution months plus credited months such as child-raising or unemployment-benefit months; nothing from any other country). A Pakistani citizen who also holds one of those eleven citizenships carries that limit; a recognized refugee or stateless person is treated like a citizen of the country of residence. Otherwise Pakistani citizens have no limit: 60 German months or more stay refundable once the three general conditions hold (no German, EU, EEA, Swiss or UK citizenship alongside; residence outside the EU, the UK and India; 24 full calendar months since the last mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state). From 60 months a Pakistani citizen has also earned a German pension at retirement age, so the refund becomes a choice: a completed refund pays out the whole refundable balance and dissolves the pension entitlement.',
    },
    {
      q: 'I am a Pakistani citizen with British, German or another European citizenship as well — can I still claim?',
      a: "Not before German retirement age. Any German, EU, EEA, Swiss or UK citizenship you hold blocks the refund on its own, whether or not you have ever used its passport (apart from a narrow exception for people who left mandatory German insurance as civil servants or in a similar status — see the complete guide) — and Pakistan's dual-nationality arrangements with the UK, Germany and a dozen other European countries make this the first thing to check. The pension office assesses your citizenship on the day the application is filed and does not take later changes into account: a naturalization completed after filing leaves a valid claim untouched; one completed before filing blocks it. If a second citizenship is in your plans or your family tree, raise it with us before anything is filed.",
    },
    {
      q: 'Can I claim while living in Pakistan — or from the UAE or Saudi Arabia?',
      a: "Yes. Living in Pakistan, the Gulf states, North America, Australia or anywhere else outside the EU and the UK has no effect on a Pakistani citizen's claim; Norway, Iceland, Liechtenstein and Switzerland are fine too. Two things still matter: living in India blocks the refund for every nationality except Indian citizens, so a Pakistani citizen living in India waits until moving on; and mandatory state pension insurance in Türkiye or an ex-Yugoslav state blocks the refund while it lasts and restarts the 24 months.",
    },
    {
      q: 'Do my EOBI contributions block or reduce the German refund?',
      a: 'No. Contributions to EOBI, a provincial social security institution, a provident fund or a private retirement plan never block the refund, never restart the 24-month waiting period, and never count toward any German month total. The only foreign insurance that blocks a refund or restarts the waiting period is mandatory pension insurance in the EU, the UK, Türkiye or an ex-Yugoslav state.',
    },
    {
      q: 'Does the 24-month waiting period start when I leave Germany or deregister?',
      a: 'No. It starts after your last mandatory contribution month in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state — never with your deregistration or departure date — and the earliest application date is the first day of the 25th month after that contribution month. New mandatory insurance in one of those places before you apply restarts the count from the month it ends: a job in the UK does, a job in Pakistan, the Gulf, the USA or Canada does not.',
    },
    {
      q: 'Can the refund be paid to a bank account in Pakistan?',
      a: 'No German bank account is required: the refund is paid through the escrow account operated by our German partner law firm, and the remaining balance is transferred to the account you nominate. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent, so the route for a transfer to Pakistan or elsewhere is checked shortly before the transfer.',
    },
    {
      q: 'Can I apply for the German pension refund myself from Pakistan?',
      a: 'Yes. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. From abroad the do-it-yourself route runs on paper using form V0901 — ordinary email is not accepted for identity reasons — and a free section-by-section English guide to the form is on our site. In the managed route, the application is reviewed and submitted by our German partner law firm, and the service fee is due only after a successful refund.',
      inSchema: false,
    },
  ],
  close: [
    {
      t: 'p',
      x: 'The complete rules — both eligibility tables, month counting, survivors, retirement age, forms and objections — are in the complete 2026 guide. Our eligibility check walks through citizenship, residence and the 60-month and 24-month rules — a preliminary indication in under a minute. Starting your claim takes less than one minute — start here →',
      sp: [
        {
          k: 'a',
          x: 'the complete 2026 guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'a',
          x: 'eligibility check',
          href: 'https://www.germanypensionrefund.com/refund-calculator',
        },
        {
          k: 'a',
          x: 'start here →',
          href: 'https://www.germanypensionrefund.com/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may also apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
  ],
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'what-we-do': 'what-we-do',
    journeys: 'journeys',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Pakistani Citizens',
    audienceType: 'Pakistani citizens who worked in Germany',
    description:
      "Managed German state pension contribution refunds for Pakistani citizens who worked in Germany. Pakistani citizenship carries no contribution-month limit; a refund before German retirement age needs residence outside the EU, the UK and India, a 24-month waiting period after the last month of mandatory pension insurance in Germany, the EU, the UK, Türkiye or an ex-Yugoslav state, and no German, EU, EEA, Swiss or British citizenship held alongside (one narrow statutory exception aside) — every citizenship held is checked and the stricter rule decides; a US, Canadian or Australian citizenship held alongside brings that country's 60-month limit. No upfront or minimum service fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. {{M-04.sentence.schema}}",
  },
};

export default page;
