// Generated by scripts/convert-country-pages.mjs from the v1.2 handoff
// (German Pension Refund for Singapore Residents (2026)). Do not edit copy here — regenerate from the handoff.
import type { CountryPageData } from '../types';

const page: CountryPageData = {
  slug: 'singapore',
  title: 'German Pension Refund for Singapore Residents (2026)',
  meta: 'Worked in Germany, now in Singapore? The address passes and CPF changes nothing — your citizenship sets the rule: no limit for most, 60 months for eleven.',
  h1: '🇸🇬 German Pension Refund for Residents of Singapore',
  archetype: 'residence',
  version: 'v1.2',
  hero: [
    {
      t: 'p',
      x: 'Worked in Germany, now living in Singapore? A Singapore address never blocks a German pension refund or restarts its waiting period. The passport decides the rest: most nationalities, Singaporean included, have no contribution-month limit; citizens of eleven countries have a 60-month limit; German, EU, EEA, Swiss and British citizens have — one narrow exception aside — no refund before German retirement age. Your row is in the table below; checking your eligibility takes a minute, starting the claim less.',
      sp: [],
    },
    {
      t: 'p',
      x: 'We check your eligibility, prepare your application and payment documents, and coordinate your claim with our German partner law firm, which reviews and submits it. Along the way you get plain-English explanations of your pension-office letters, regular updates, and support that continues after the decision. No refund, no service fee.',
      sp: [],
    },
  ],
  trust: '{{M-15.sentence}}',
  bullets: [
    'A Singapore address never blocks the refund and never restarts the 24 months — your citizenship sets the rule',
    'CPF savings never count, and a work pass or permanent residence is residence status, not a citizenship',
    '{{M-04.sentence.hero}}',
    '{{TM-01.sentence.hero}}',
    'No German bank account required · No refund, no service fee · No minimum service fee',
  ],
  sections: [
    {
      id: 'what-a-singapore-address-decides-and',
      kind: 'residence',
      h2: 'What a Singapore address decides — and what it leaves to your passport',
      blocks: [
        {
          t: 'p',
          x: 'A German pension refund before retirement age turns on three checks made on the day the application is filed: which citizenships you hold, where your home is, and whether 24 full months have passed since your last month of mandatory pension insurance in Germany or another listed country. Singapore answers the second for you. Germany has no social security agreement with Singapore, and for a refund that is the convenient case: a home in Singapore is a home outside the EU, the UK and India, and for anyone living in Singapore that is the whole residence check. Your retirement savings here are just as neutral. Singapore citizens and permanent residents employed here pay into the Central Provident Fund; foreigners on an Employment Pass, S Pass or Work Permit have been outside the CPF since 2003 and pay nothing into it. Either way, CPF contributions never block a German refund, never restart its 24-month waiting period and never count toward any German month total. Permanent residence and a work pass are residence status, not citizenship. A Singapore address cannot, however, create an entitlement that your citizenship denies — so find your row below.',
          sp: [
            {
              k: 'a',
              x: 'no social security agreement',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Sozialversicherungsabkommen/sozialversicherungsabkommen_detailseite.html',
            },
          ],
        },
      ],
    },
    {
      id: 'do-i-qualify',
      kind: 'citizenship-table',
      h2: 'Your citizenship decides — find your row',
      blocks: [
        {
          t: 'table',
          rows: [
            ['Your citizenship', 'Refund before German retirement age?'],
            [
              'German, EU, EEA, Swiss or British — held alone or beside any other citizenship',
              'No — not before German retirement age (one narrow exception for people who left mandatory German insurance as civil servants or in a similar status — the complete guide explains it)',
            ],
            [
              'USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia or Uruguay',
              'Yes, with 59 or fewer German months — contribution and credited months, German ones only',
            ],
            [
              'Every other citizenship — Singaporean, Malaysian, Chinese, Indonesian, Thai, Vietnamese, Bangladeshi, Sri Lankan, Burmese, Nepali, Pakistani, Turkish and the rest, including Japanese, Israeli, Bosnian, Kosovar, Montenegrin and Serbian citizens while they live in Singapore',
              'Yes — no contribution-month limit',
            ],
          ],
        },
        {
          t: 'p',
          x: 'Two or more citizenships are all examined, and the stricter rule decides. The third row carries Japanese, Israeli, Bosnian, Kosovar, Montenegrin and Serbian citizens because their home rules bind only at home — in Japan, in Israel, or in one of Bosnia and Herzegovina, Kosovo, Montenegro and Serbia — and a Singapore address takes them out of reach. Each "Yes" is subject to the 24-month wait described further down.',
          sp: [],
        },
        {
          t: 'h3',
          x: 'No refund before German retirement age — German, EU, EEA, Swiss and British citizens',
        },
        {
          t: 'p',
          x: 'The block travels with the citizenship: a German engineer with Singapore permanent residence and a British banker in Tanjong Pagar are in the same position as if they had moved back to Stuttgart or London (our Brexit guide explains the UK rule). The exception covers people who left mandatory German insurance as civil servants or in a similar status; the complete guide explains it. From German retirement age a refund becomes possible again where the five-year qualifying period — German months plus EU, UK and agreement-country periods, never Singapore years — has not been met.',
          sp: [
            {
              k: 'a',
              x: 'our Brexit guide',
              href: 'https://www.germanypensionrefund.com/post/brexit',
            },
            {
              k: 'a',
              x: 'complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
        {
          t: 'h3',
          x: 'A 60-month limit — citizens of the eleven countries in the second row',
        },
        {
          t: 'p',
          x: "The 60 counts German months only — contribution months plus credited months such as child-raising periods or months on unemployment benefit (not every line of the insurance record counts) — with nothing from the CPF or any other country's scheme added. A Singapore address leaves the limit where it is: an Indian data scientist with 50 German months is inside it in Singapore as in Chennai; at 60 or more she has a German old-age pension at retirement age instead. Several of these countries have a page of their own: India, USA, Canada, Australia, Brazil, South Korea, the Philippines.",
          sp: [
            {
              k: 'a',
              x: 'India',
              href: 'https://www.germanypensionrefund.com/india',
            },
            {
              k: 'a',
              x: 'USA',
              href: 'https://www.germanypensionrefund.com/usa',
            },
            {
              k: 'a',
              x: 'Canada',
              href: 'https://www.germanypensionrefund.com/canada',
            },
            {
              k: 'a',
              x: 'Australia',
              href: 'https://www.germanypensionrefund.com/australia',
            },
            {
              k: 'a',
              x: 'Brazil',
              href: 'https://www.germanypensionrefund.com/brazil',
            },
            {
              k: 'a',
              x: 'South Korea',
              href: 'https://www.germanypensionrefund.com/southkorea',
            },
            {
              k: 'a',
              x: 'the Philippines',
              href: 'https://www.germanypensionrefund.com/thephilippines',
            },
          ],
        },
        {
          t: 'h3',
          x: 'No limit — Singaporean citizens and everyone else in the third row',
        },
        {
          t: 'p',
          x: "Singaporean citizenship carries no contribution-month limit and no special rule: Singapore has no agreement with Germany, so nothing gives someone holding Singaporean citizenship alone and living in Singapore a right to pay voluntary German contributions, and it is that right — not its use — that creates the second row's 60-month limits. Whether you paid in for 18 German months or 108, the whole employee share is refundable after the 24-month wait; from 60 months a German old-age pension at retirement age has been earned as well, which the refund replaces — a choice, not a bar. Singapore generally does not permit adults to retain dual citizenship, and a Singaporean who acquires another citizenship is liable to lose the Singapore one; for the German claim every citizenship actually held on the filing date counts and the stricter rule decides, so a Singaporean who has become, say, Australian or German is placed by that row — where your status is uncertain, confirm it with the Singapore authorities. A citizenship acquired after a valid application does not undo the claim, and a pending application is not yet a citizenship; mention every citizenship you hold or may hold before anything is filed.",
          sp: [],
        },
      ],
    },
    {
      id: 'what-we-do',
      kind: 'service',
      h2: 'What we do for you — and what it costs',
      blocks: [
        {
          t: 'p',
          x: 'Before anything is filed. You provide your details, documents and signatures; we do the rest of the preparation. We check your eligibility, obtain and review the relevant DRV account information during the managed process where required, prepare your refund application and payment documents, identify the recommended first pension office from your record and coordinate the claim with our German partner law firm, which reviews and submits it.',
          sp: [
            {
              k: 'b',
              x: 'Before anything is filed.',
            },
          ],
        },
        {
          t: 'p',
          x: 'While the pension office works. Pension-office letters for your claim are received at a German address, scanned to you and explained in plain English. After your claim is submitted, you receive an update at least every four weeks — even when the update is that no pension-office response has arrived. If there is still no decision six months after submission, updates come at least every two weeks, whether or not a formal complaint has been filed. Material requests and developments are communicated sooner. If we are still waiting for a decision three months after submission, we contact the pension office to check where the application stands. We keep track of known response and objection deadlines within the agreed scope; if a letter reaches you directly, forward it to us straight away with the date you received it — only deadlines known to us or our partner law firm can be protected.',
          sp: [
            {
              k: 'b',
              x: 'While the pension office works.',
            },
          ],
        },
        {
          t: 'p',
          x: "After the decision. Our managed service includes checking the pension office's decision against your record and evidence. If contribution periods you can evidence — payslips, for example — are missing from the refund statement, a straightforward objection is included in the service fee: we draft it from our standard template and your evidence, and it goes to the pension office; no extra cost. If the disagreement is a legal question — for example, the office rejects the refund on a legal ground you could not be expected to assess yourself — objection representation is separate work by our partner law firm, agreed directly between you and the firm at its own cost, outside the service scope. If an approved refund does not arrive, we follow it up within the managed scope with the pension office and Renten Service until the payment is resolved.",
          sp: [
            {
              k: 'b',
              x: 'After the decision.',
            },
          ],
        },
        {
          t: 'p',
          x: "Our fee is 9.75% of the refunded amount, capped at €2,500 including VAT, with no upfront service fee and no minimum service fee. No refund, no service fee. The fee covers the agreed managed administrative scope, including our partner law firm's support within that scope. We do not provide legal services, advice or representation; separate representation in an objection, appeal or court proceeding is not included automatically. German deregistration is available as an optional €50 add-on including VAT, payable with the service fee after your refund reaches escrow — and if your German pension insurance number has gone missing, we can help identify or recover it.",
          sp: [
            {
              k: 'a',
              x: '9.75% of the refunded amount',
              href: 'https://www.germanypensionrefund.com/pricing',
            },
          ],
        },
        {
          t: 'p',
          x: '{{TM-01.sentence}} {{M-12.sentence}} Individual processing times vary — see the full data and methodology. Processing and payment dates depend on the responsible pension office and the payment route, so a specific date cannot be guaranteed; the process is designed to avoid preventable delays.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: 'https://www.germanypensionrefund.com/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      id: 'what-you-need-to-start',
      kind: 'intake',
      h2: 'What you need to start',
      blocks: [
        {
          t: 'p',
          x: 'To get started, upload a copy of your passport, a payslip from your time in Germany and your deregistration confirmation (Abmeldebestätigung). Your account guides you through the questions and documents. Missing your German pension number? We help recover it. Not deregistered yet? We offer deregistration assistance for €50 including VAT. If your claim needs additional documents or signed originals by post, we explain exactly what to provide.',
          sp: [],
        },
      ],
    },
    {
      id: 'the-24-month-waiting-period-moving',
      kind: 'waiting-period',
      h2: 'The 24-month waiting period — moving to Singapore does not restart it',
      blocks: [
        {
          t: 'p',
          x: "Twenty-four full calendar months must lie between your last month of mandatory pension insurance — in Germany, another EU state, the UK, Türkiye or an ex-Yugoslav state (Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia) — and the application (Deutsche Rentenversicherung sets out the rule here). The contribution month is the anchor, not the day you deregistered or the day you cleared immigration at Changi; the first day of the 25th month after it is your earliest filing date, and filing earlier gains nothing — the period does not shorten, and extra confirmation requests can follow. Years of local employment in Singapore — with no compulsory German pension insurance continuing under a posting from Germany — leave the count where it is, whatever the CPF position, and for citizens outside the no-refund group so does mandatory insurance in Switzerland, Norway, Iceland or Liechtenstein. Two things do move the count. A fixed-period posting to Singapore by your German employer under which German insurance continued produces German contribution months, so the count runs from the last of them; and an insured job in a listed country between Germany and Singapore — a year in London or Amsterdam, say — restarts the 24 months from that job's last contribution month. No deadline applies to a first application; no interest is paid for the years before it. Our waiting-period calculator works out the date from your last contribution month.",
          sp: [
            {
              k: 'a',
              x: 'Deutsche Rentenversicherung sets out the rule here',
              href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Allgemeine-Informationen/Wissenswertes-zur-Rente/FAQs/International/Erstattung.html',
            },
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'journeys',
      kind: 'journeys',
      h2: 'Three illustrative journeys — one address, three citizenships',
      blocks: [
        {
          t: 'note',
          x: 'Worked examples, not client cases.',
        },
        {
          t: 'p',
          x: "The Australian marketing manager. Hamburg from April 2021 to December 2024 — 45 months at €4,600 gross — then a local job in Singapore on an Employment Pass from February 2025. Her Australian citizenship caps her at 59 German months, and 45 is comfortably inside: €427.80 a month, roughly €19,300 in refundable employee contributions, with 1 January 2027 — the first day of the 25th month after December 2024 — as her earliest filing date. Her address plays no part in the limit, but it does not change her office either: an Australian citizen's claim normally goes to DRV Oldenburg-Bremen, so we prepare her power of attorney and payment declaration and she sends us the signed originals by post — the rest of her part stays digital.",
          sp: [
            {
              k: 'b',
              x: 'The Australian marketing manager.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The Singaporean engineer. Munich from January 2019 to June 2025 — 78 months at €5,200 gross, statutory pension contributions paid throughout — then home to Singapore in July 2025. No limit: €483.60 a month, roughly €37,700 in refundable employee contributions, claimable from 1 July 2027, counted from his last Munich contribution month, not from the flight. With 78 months he has also earned a German old-age pension at retirement age, which the refund would replace — worth comparing before he decides; his CPF account has no bearing on either.',
          sp: [
            {
              k: 'b',
              x: 'The Singaporean engineer.',
            },
          ],
        },
        {
          t: 'p',
          x: 'The German project lead with permanent residence. Six years in Berlin, then Singapore on an Employment Pass and, later, permanent residence. Nothing is refundable before German retirement age (the narrow exception for people who left mandatory German insurance as civil servants or in a similar status aside): the German citizenship rules, and permanent residence in Singapore is an address status with no vote in the matter. Nor are the contributions gone — with six years he has more than the five-year qualifying period, so at retirement age they pay a German pension.',
          sp: [
            {
              k: 'b',
              x: 'The German project lead with permanent residence.',
            },
          ],
        },
        {
          t: 'p',
          x: 'Your own months go through the free refund calculator in a minute.',
          sp: [
            {
              k: 'a',
              x: 'free refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
      ],
    },
    {
      id: 'which-of-your-years-in-germany',
      kind: 'years',
      h2: 'Which of your years in Germany actually paid pension contributions?',
      blocks: [
        {
          t: 'p',
          x: 'Refunds cover only months that statutory pension insurance actually covered, so the sorting comes first:',
          sp: [],
        },
        {
          t: 'ul',
          items: [
            {
              x: "Employment based in Germany under German social insurance — the normal result of a German employment contract, whether on an EU Blue Card, a skilled-worker permit or any other work permit — brings pension insurance from the start: every month counts and the employee share is refundable. Lower pay is the exception: for months in employment covered by the Übergangsbereich rules for the relevant year (in 2026, regular pay between €603.01 and €2,000 a month) the refund is half of the total pension contributions paid for them — 9.3% of gross pay is the wrong sum for those months, so a part-time job at €1,500 a month in 2026 is insured and every month counts, but its refund follows the half-of-total rule (for years before 2023 the band's upper limit was lower, so the year decides).",
              sp: [
                {
                  k: 'b',
                  x: 'Employment based in Germany under German social insurance',
                },
              ],
            },
            {
              x: 'Posted to Germany by a Singapore employer — a fixed-term assignment with the employment relationship left in Singapore — is the case to check first: under the Einstrahlung rule such months may have stayed outside German insurance (German law alone decides, there being no agreement), and then there is nothing to refund for them, whereas employment taken up with the German entity, based in Germany, brings ordinary insurance.',
              sp: [
                {
                  k: 'b',
                  x: 'Posted to Germany by a Singapore employer',
                },
              ],
            },
            {
              x: 'Werkstudent jobs are pension-insured although students pay no health, care or unemployment insurance through that employment; above the minijob limit the months count and the contributions come back. Ausbildung contracts are pension-insured too, and the Übergangsbereich rules are not applied to training pay. (Only where training pay was €325 a month or less did the employer bear the whole contribution; those months count, but hold no employee share.)',
              sp: [
                {
                  k: 'b',
                  x: 'Werkstudent jobs',
                },
                {
                  k: 'b',
                  x: 'Ausbildung contracts',
                },
              ],
            },
            {
              x: "Minijobs turn on one choice: if the small employee top-up (the default since 2013) was kept, the months count and the top-up is refundable; if it was waived, only the employer's flat-rate contributions were paid: nothing of yours is in the record and those months neither block nor restart the waiting period, though they can still earn partial credit toward the five-year qualifying period.",
              sp: [
                {
                  k: 'b',
                  x: 'Minijobs',
                },
              ],
            },
            {
              x: 'A scholarship or stipend without an employment contract — a DAAD-funded stay, say — carries no pension insurance, whereas a doctoral or postdoc position on an employment contract is insured like any job. Freelance or self-employed work usually falls outside mandatory insurance, and where voluntary or compulsory self-employed contributions were paid, the refund is half of them.',
              sp: [
                {
                  k: 'b',
                  x: 'A scholarship or stipend without an employment contract',
                },
                {
                  k: 'b',
                  x: 'Freelance or self-employed work',
                },
              ],
            },
          ],
        },
        {
          t: 'p',
          x: 'Memory and old payslips produce an estimate; the months actually refunded are those in the official insurance record (Versicherungsverlauf), which we obtain and review in a managed claim where required.',
          sp: [],
        },
      ],
    },
    {
      id: 'how-much-comes-back-and-what',
      kind: 'amount',
      h2: 'How much comes back — and what about tax in Singapore?',
      blocks: [
        {
          t: 'p',
          x: "The refund is your own share of the contributions — 9.3% of gross pay since 2018, charged up to the monthly ceiling (Beitragsbemessungsgrenze: €8,450 in 2026, €8,050 in 2025) — and normally the whole of it; the employer's share stays in the system, and pay above the ceiling was never insured. The main exceptions change the calculation: voluntary contributions and the compulsory contributions of self-employed people are refunded at 50%; months in employment covered by the Übergangsbereich rules for the relevant year at half of the total contributions paid for them; and where Deutsche Rentenversicherung once funded a benefit for you — a rehabilitation programme, say — only the contributions paid after it are refundable, while the completed refund still closes the whole record. These are checked before anything is filed. The legal basis is § 210 SGB VI.",
          sp: [
            {
              k: 'a',
              x: '§ 210 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__210.html',
            },
          ],
        },
        {
          t: 'p',
          x: '{{M-04.sentence}} Our refund calculator applies the actual statutory employee contribution rate and monthly ceiling (Beitragsbemessungsgrenze) of every year back to 1975 — including Deutsche-Mark periods and East/West differences — rather than a flat percentage.',
          sp: [
            {
              k: 'a',
              x: 'refund calculator',
              href: 'https://www.germanypensionrefund.com/refund-calculator',
            },
          ],
        },
        {
          t: 'p',
          x: 'On the German side the refund is paid out without income tax; the exemption is written into German law and confirmed by the Federal Fiscal Court. Singapore taxes individuals on income earned in Singapore, and foreign-sourced income received by individuals is exempt unless it arrives through a Singapore partnership — but a Singapore address does not settle the question by itself: whether a German contribution refund falls under that exemption in your case, and whether another country can tax or require reporting of it, is for a local adviser to say — we do not provide individual tax, pension or legal advice.',
          sp: [
            {
              k: 'a',
              x: 'foreign-sourced income received by individuals',
              href: 'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/what-is-taxable-what-is-not/income-received-from-overseas',
            },
          ],
        },
      ],
    },
    {
      id: 'which-german-pension-office-handles-a',
      kind: 'office',
      h2: "Which German pension office handles a Singapore resident's claim?",
      blocks: [
        {
          t: 'p',
          x: 'With no liaison office (Verbindungsstelle) for Singapore, the responsible office is read off your insurance record first and your citizenship second: DRV Knappschaft-Bahn-See if it ever insured you; otherwise DRV Bund if it was the last carrier of your account; otherwise the liaison office attached to your citizenship where Germany has an agreement with that country — DRV Nord for Indian, US and Canadian citizens, DRV Oldenburg-Bremen for Australians, DRV Braunschweig-Hannover for Japanese, South Korean and Filipino citizens, the other agreement countries in our guide; otherwise the regional office that holds your account, where Singaporean, Malaysian, Chinese, Indonesian and every other citizenship without a liaison office lands. Our guide to the responsible pension office has the full decision tree and the office finder. In a managed claim, our German partner law firm files the claim with the recommended office we identify from your record.',
          sp: [
            {
              k: 'a',
              x: 'Our guide to the responsible pension office',
              href: 'https://www.germanypensionrefund.com/post/which-german-pension-office-handles-your-claim',
            },
          ],
        },
      ],
    },
    {
      id: 'getting-paid',
      kind: 'payout',
      h2: 'Getting paid in Singapore — or wherever you live next',
      blocks: [
        {
          t: 'p',
          x: 'No German bank account is required. In a claim we manage, your refund is paid through the escrow account operated by our German partner law firm; after the agreed service fee is deducted, the remaining balance is transferred to the bank account you nominate — a third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent, so the route for a transfer to Singapore or elsewhere is checked shortly before the money moves. Eligibility and payment route are separate: a valid refund may require an account in a permitted country if transfers to the residence country are restricted.',
          sp: [],
        },
      ],
    },
    {
      id: 'certified-signatures',
      kind: 'certification',
      h2: 'Digital for most clients — certified signatures in Singapore',
      blocks: [
        {
          t: 'p',
          x: "Most clients can complete their entire part of the process digitally: you submit your details and sign online. Every client has their identity and signature confirmed using their passport or an accepted equivalent; depending on the route, that confirmation can be completed digitally or, where a certified signature is needed, in person. Where one is needed, we prepare the document and you have it certified by one certifier — no combination of certifiers is ever required. In Singapore the route to try first, and usually the cheaper one, is the German Embassy: it certifies signatures on documents for use with a German authority whatever your nationality, in person after an appointment booked through its online system — bring the document to be signed, your passport and your Singapore pass (the Embassy's signature-certification page lists what to bring). The Embassy itself points to a Singapore notary public as the usual alternative, subject to acceptance by the German recipient — so a notary public or a bank is the alternative for a particular document where the responsible pension office accepts that certification; a certifier that does not read the document's language may ask for a translation first, which costs more and takes longer. Required local certification, notary or translation costs are borne by the client. If DRV Oldenburg-Bremen is responsible for your refund — where an Australian citizen living in Singapore usually lands unless Knappschaft-Bahn-See ever insured you or DRV Bund was the last carrier of your account — we prepare the power of attorney and payment declaration and ask you to send us the signed originals; for everyone else this is a limited exception rather than the rule.",
          sp: [
            {
              k: 'a',
              x: "the Embassy's signature-certification page",
              href: 'https://singapur.diplo.de/sg-de/service/2276830-2276830',
            },
          ],
        },
        {
          t: 'p',
          x: 'You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. Self-filing from Singapore means paper — form V0901 in the post, since ordinary email is not accepted for identity reasons and fax has been discontinued. In a self-filed claim, the official application form provides for your personal data to be certified on the form itself, so the application travels to the certifying body — the Embassy, or a notary public or bank where its certification is accepted for that form. In a managed claim, the analog step is a single page we prepare for you. The form is walked through section by section in our V0901 guide.',
          sp: [
            {
              k: 'a',
              x: 'V0901 guide',
              href: 'https://www.germanypensionrefund.com/v0901-pension-refund-form-english',
            },
          ],
        },
      ],
    },
    {
      id: 'a-family-members-german-contributions',
      kind: 'family',
      h2: "A family member's German contributions",
      blocks: [
        {
          t: 'p',
          x: "Where a spouse, registered partner or parent has died with German contributions on record, the closest family — the surviving spouse or registered partner and, in the cases the law provides for, the children — can be entitled to a refund of those contributions where no German survivor's pension is payable because the deceased had not met the five-year qualifying period (allgemeine Wartezeit). Checking that period means looking beyond the German months — at foreign periods that count toward it (CPF years do not — there is no agreement) and at the rules that treat it as met in special cases. Survivors need not wait 24 months, but their claim can become time-barred four years after the end of the year of death. Where the qualifying period was met, a German survivor's pension may be payable instead — worldwide, Singapore included. Our German widow's pension guide and the survivors chapter of the complete guide explain who can claim, in which order and with what evidence.",
          sp: [
            {
              k: 'a',
              x: "Our German widow's pension guide",
              href: 'https://www.germanypensionrefund.com/post/german-widow-pension',
            },
            {
              k: 'a',
              x: 'survivors chapter of the complete guide',
              href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
            },
          ],
        },
      ],
    },
  ],
  faq: [
    {
      q: 'Is living in Singapore a plus or a minus for a German pension refund?',
      a: "It does neither. Living in Singapore satisfies the residence condition — outside the EU, the UK and India — and cannot restart the 24-month waiting period; the Central Provident Fund is Singapore's own scheme rather than German pension insurance, so nothing paid into it counts toward a German month total. What the address cannot supply is a route of its own: whether there is no limit, a 60-month limit or — one narrow exception aside — no refund before German retirement age depends on your citizenship.",
    },
    {
      q: 'Can a British or German citizen living in Singapore claim?',
      a: 'Generally, not before German retirement age. For British, German, EU, EEA and Swiss citizens the refund is closed before then — the narrow exception for people who left mandatory German insurance as civil servants or in a similar status aside (see the complete guide) — and a Singapore address or permanent residence does not reopen it; the citizenship carries the rule. From retirement age the contributions can be refunded where the five-year qualifying period has not been met, EU, UK and agreement-country periods included in that count — CPF years are not.',
    },
    {
      q: 'I am an Australian citizen living in Singapore — does the 60-month limit apply, and why the originals by post?',
      a: "The limit follows Australian citizenship wherever you live: a refund before retirement age needs 59 or fewer German months — contribution months plus credited periods such as child-raising or unemployment-benefit months, nothing from Singapore added — and with 60 or more you have a German old-age pension at retirement age instead — provided no other citizenship you hold brings a stricter rule (an Australian who is also British has no refund before German retirement age). The originals follow the office, not the address: an Australian citizen's claim normally goes to DRV Oldenburg-Bremen, and for that office we prepare the power of attorney and payment declaration and ask you to post us the signed originals; if Knappschaft-Bahn-See ever insured you or DRV Bund was the last carrier of your account, that office takes the claim instead and the step falls away.",
    },
    {
      q: 'I am a Singaporean citizen — is there a limit on refundable German months?',
      a: "No. Singapore has no social security agreement with Germany, so Singaporean citizenship carries no contribution-month limit and no special rule: after the 24-month wait the whole employee share is refundable, whether the record shows 18 German months or 108, and from 60 months a German old-age pension at retirement age has been earned as well, which the refund replaces. Singapore generally does not permit adults to retain dual citizenship, and a Singaporean who acquires another citizenship is liable to lose the Singapore one; for the German claim every citizenship actually held counts and the stricter rule decides, so the other citizenship's row applies either way — where your status is uncertain, confirm it with the Singapore authorities. We do not provide individual legal advice.",
    },
    {
      q: 'Do my CPF contributions, my permanent residence or my Employment Pass affect the refund?',
      a: 'No. CPF contributions — mandatory for Singapore citizens and permanent residents, not payable for foreigners on work passes since 2003 — never block the German refund, never restart the 24-month waiting period and never count toward any German month total; the only foreign insurance that blocks a refund or restarts the wait is mandatory pension insurance in the EU, the UK, Türkiye or an ex-Yugoslav state, and German insurance continuing through a posting from Germany produces German months, which is a different matter. Permanent residence and a work pass are residence status, not citizenship: a Singapore address already passes the residence check for every nationality, and only a citizenship you actually hold enters the citizenship check.',
    },
    {
      q: 'Which nationalities in Singapore have no contribution-month limit?',
      a: 'All but two groups. German, EU, EEA, Swiss and British citizens are shut out before German retirement age (the narrow exception for people who left mandatory German insurance as civil servants or in a similar status aside); citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay are held to 59 German months. Every other citizenship living in Singapore — Singaporean, Malaysian, Chinese, Indonesian, Thai, Vietnamese, Bangladeshi, Sri Lankan and the rest — has no contribution-month limit, and so, from Singapore, do Japanese, Israeli, Bosnian, Kosovar, Montenegrin and Serbian citizens, whose home rules bind only at home. Two or more citizenships: every one counts, and the stricter rule decides.',
    },
  ],
  close: [
    {
      t: 'p',
      x: 'For the eligibility tables, month counting, survivors, retirement age, forms and objections in full, read the complete 2026 guide. Our eligibility check walks through citizenship, residence and the 60-month and 24-month rules — a preliminary indication in under a minute. Starting your claim takes less than one minute — start here →',
      sp: [
        {
          k: 'a',
          x: 'the complete 2026 guide',
          href: 'https://www.germanypensionrefund.com/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'a',
          x: 'eligibility check',
          href: 'https://www.germanypensionrefund.com/refund-calculator',
        },
        {
          k: 'a',
          x: 'start here →',
          href: 'https://www.germanypensionrefund.com/get-your-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may also apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
  ],
  anchors: {
    'do-i-qualify': 'do-i-qualify',
    'what-we-do': 'what-we-do',
    journeys: 'journeys',
    'getting-paid': 'getting-paid',
    'certified-signatures': 'certified-signatures',
    faq: 'faq',
  },
  schema: {
    serviceName: 'German Pension Refund for Residents of Singapore',
    audienceType: 'Residents of Singapore who worked in Germany',
    description:
      'Managed German state pension contribution refunds for people living in Singapore who worked in Germany. A Singapore address never blocks a refund or restarts the 24-month waiting period, counted from the last month of mandatory pension insurance in Germany or another listed country; CPF contributions never count. Every citizenship held is checked and the rules follow it: no contribution-month limit for most nationalities, a 60-month limit for citizens of eleven countries, and — one narrow statutory exception aside — no refund before German retirement age for German, EU, EEA, Swiss and British citizens. No upfront or minimum service fee — the service fee is 9.75% of the refund, capped at €2,500 including VAT, within the agreed managed administrative scope. {{M-04.sentence.schema}}',
  },
};

export default page;
