// Generated by scripts/build-guides.mjs from GPR_Brexit_Post_Refresh_Content_Handoff_2026-09-10.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/post/brexit',
  kind: 'post',
  lang: 'en',
  title: 'German Pension Refund After Brexit: UK Nationals and UK Residents',
  meta: 'Why UK citizens and anyone living in the UK generally cannot get a German pension refund before retirement age after Brexit — and the three exceptions.',
  h1: 'German Pension Refund After Brexit: Rules for UK Nationals and UK Residents',
  headline: 'German Pension Refund After Brexit: UK Nationals and UK Residents',
  eyebrow: 'Article · UK nationals and UK residents',
  rail: 'Article',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'News',
      href: '/blog',
    },
    {
      label: 'Brexit',
    },
  ],
  reviewLine: 'Updated: 11 September 2026',
  showReviewer: false,
  datePublished: '2026-04-21',
  dateModified: '2026-09-11',
  imageUrl:
    'https://static.wixstatic.com/media/4a4b7f_b8d9b8e7933143f09d8d9ce68aed35b5~mv2.png',
  blocks: [
    {
      t: 'h2',
      x: 'The short answer',
      id: 'the-short-answer',
    },
    {
      t: 'p',
      x: 'Generally no. If you are a UK citizen (a UK national), you cannot get a German pension refund before German retirement age — wherever you live now and whenever you worked in Germany. The same applies to anyone who lives in the UK, whatever their citizenship, for as long as they live there. Brexit did not change this, and there is no "partial" refund either: a German pension refund is all or nothing.',
      sp: [
        {
          k: 'b',
          x: 'Generally no.',
        },
      ],
    },
    {
      t: 'p',
      x: 'Three situations are different:',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'At German retirement age. If your record — including UK and other foreign periods that must be combined — stays under the five-year qualifying period (allgemeine Wartezeit), a refund becomes possible then, even while you live in the UK.',
          sp: [
            {
              k: 'b',
              x: 'At German retirement age.',
            },
          ],
        },
        {
          x: 'The exemption route. If you are a German civil servant or otherwise exempt from German mandatory pension insurance when you apply, § 210 Abs. 1a SGB VI can allow a refund of your earlier contributions. It is a separate statutory route with its own exclusions and needs an individual check.',
          sp: [
            {
              k: 'b',
              x: 'The exemption route.',
            },
          ],
        },
        {
          x: 'Non-UK citizens who leave the UK. The residence block ends when you move to a qualifying country; the rules for your citizenship then decide.',
          sp: [
            {
              k: 'b',
              x: 'Non-UK citizens who leave the UK.',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Why the refund is blocked: the voluntary-insurance right',
      id: 'why-the-refund-is-blocked-the-voluntary',
    },
    {
      t: 'p',
      x: 'For most former employees, a refund before retirement age needs three things: no current mandatory pension insurance in Germany or in a foreign system that Germany treats the same way; at least 24 full calendar months since that insurance ended; and no legal right to pay voluntary contributions into the German pension system. The third point decides UK cases: a right that exists blocks the refund even if you never use it.',
      sp: [],
    },
    {
      t: 'p',
      x: 'UK citizens have that right under the EU–UK coordination rules once they have previous German insurance — a single German contribution month is enough — and it stays with them wherever they live. Anyone living in the UK has it through residence there once German law has applied to them through their work. So the length of your German employment does not change the answer: three months or ten years, the ordinary refund is blocked either way.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Did Brexit change anything?',
      id: 'did-brexit-change-anything',
    },
    {
      t: 'p',
      x: 'For refund eligibility, no. The legal basis changed; the result did not.',
      sp: [],
    },
    {
      t: 'p',
      x: 'Until 31 December 2020, EU social security coordination under Regulation (EC) No 883/2004 applied to the UK: UK citizens could pay voluntary German contributions from abroad on the same footing as other EU citizens — once they had a single German contribution month — and residence in the UK gave non-UK citizens the same right. Since 1 January 2021, two instruments share the field:',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: "The Withdrawal Agreement protects situations that existed before 2021. People who were in a cross-border EU–UK situation at the end of 2020 and remain in one without interruption stay under the old coordination rules in full, voluntary insurance included. UK citizens and UK residents who were subject to an EU country's law before 2021 — and EU citizens who were subject to UK law — also keep the protection of those earlier insurance periods for pension purposes, so German and UK periods can still be combined.",
          sp: [
            {
              k: 'b',
              x: 'The Withdrawal Agreement',
            },
          ],
        },
        {
          x: "The Trade and Cooperation Agreement covers newer situations through its Protocol on Social Security Coordination. For voluntary insurance it matters mainly for UK citizens living outside the EU and for non-UK citizens living in the UK who are not covered by the Withdrawal Agreement's full rules. Its Annex SSC-6 ties the German voluntary-insurance right to previous German insurance, which every former employee in Germany has.",
          sp: [
            {
              k: 'b',
              x: 'The Trade and Cooperation Agreement',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: "Whichever instrument applies to you, a UK citizen keeps the voluntary-insurance right and the ordinary refund stays closed before retirement age. Deutsche Rentenversicherung's guidance on both instruments is linked at the end of this article.",
      sp: [],
    },
    {
      t: 'h2',
      x: 'What this means for you',
      id: 'what-this-means-for-you',
    },
    {
      t: 'h3',
      x: 'UK citizens',
    },
    {
      t: 'p',
      x: 'Your right to pay voluntary German contributions prevents an ordinary refund before German retirement age — whether your German employment started before or after 2021, and whether you live in the UK, in Australia or anywhere else. The block comes with your citizenship.',
      sp: [],
    },
    {
      t: 'p',
      x: 'Result: no refund before German retirement age, unless the exemption route applies to you. Your contributions are not lost: they stay in your German account, and the retirement-age rule below explains what they become.',
      sp: [
        {
          k: 'b',
          x: 'Result: no refund before German retirement age, unless the exemption route applies to you.',
        },
      ],
    },
    {
      t: 'h3',
      x: 'Non-UK citizens who live in the UK',
    },
    {
      t: 'p',
      x: 'Your residence in the UK gives you the same voluntary-insurance right, and it blocks the ordinary refund for as long as you live there.',
      sp: [],
    },
    {
      t: 'p',
      x: 'Result: no refund before German retirement age while you live in the UK, unless the exemption route applies to you. At retirement age, the retirement-age rule applies wherever you live.',
      sp: [
        {
          k: 'b',
          x: 'Result: no refund before German retirement age while you live in the UK, unless the exemption route applies to you.',
        },
      ],
    },
    {
      t: 'p',
      x: 'This block is attached to your address, not your passport. If you move to a qualifying country before applying, the residence block ends and the rules for your citizenship decide — the complete guide to German pension refunds and our country pages set them out. Two things to check before you count on it:',
      sp: [
        {
          k: 'a',
          x: 'complete guide to German pension refunds',
          href: '/post/how-to-get-a-german-pension-refund',
        },
      ],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Every citizenship you hold counts. A second citizenship you hold can add restrictions: a British passport — or a German, Irish, other EU, EEA or Swiss one — blocks the refund on its own, even one you have never used.',
          sp: [
            {
              k: 'b',
              x: 'Every citizenship you hold counts.',
            },
          ],
        },
        {
          x: 'The 24-month waiting period runs from your last mandatory pension insurance in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia. A job in the UK restarts the clock: the 24 months begin only after that insurance ends. Our free waiting-period calculator checks the waiting-period date; overall eligibility still depends on the relevant rules.',
          sp: [
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: '/post/german-pension-refund-waiting-period',
            },
            {
              k: 'b',
              x: 'The 24-month waiting period',
            },
          ],
        },
      ],
    },
    {
      t: 'h3',
      x: 'If you hold more than one citizenship',
    },
    {
      t: 'p',
      x: 'Every citizenship counts, and one blocking citizenship is enough. A British-Australian or British-Canadian dual citizen is treated like a UK citizen: no ordinary refund before German retirement age, even if you have never lived in the UK or used the British passport. The retirement-age rule and the exemption route remain open.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'When a refund is still possible',
      id: 'when-a-refund-is-still-possible',
    },
    {
      t: 'h3',
      x: 'At German retirement age — the retirement-age rule',
    },
    {
      t: 'p',
      x: 'Once you reach German retirement age, the question is no longer whether you may take your contributions out but whether you have earned a pension — decided by the five-year qualifying period (allgemeine Wartezeit). It counts more than your German salary months: child-raising periods, months of unemployment benefit and insurance periods in the UK and other countries that must be combined under the coordination rules or a social security agreement all count toward the five years.',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Five qualifying years or more, counting the combined periods: as a UK citizen, or while you live in the UK, you have earned a pension entitlement, not a refund. Usually that is a German pension, payable in the UK or anywhere else. If your German periods add up to less than one year, the coordination rules can instead let the UK or another coordinating country take those months into account rather than Germany paying a separate pension.',
          sp: [
            {
              k: 'b',
              x: 'Five qualifying years or more, counting the combined periods:',
            },
          ],
        },
        {
          x: 'Fewer than five qualifying years, even after combining: you can apply for the refund at that point. Your UK citizenship or UK address no longer blocks it, current mandatory insurance does not block it, and there is no 24-month waiting period.',
          sp: [
            {
              k: 'b',
              x: 'Fewer than five qualifying years, even after combining:',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'Whether paying voluntary contributions before then makes sense for you is a pension-planning question outside our service; Deutsche Rentenversicherung provides information on voluntary insurance directly.',
      sp: [],
    },
    {
      t: 'h3',
      x: 'The exemption route: German civil servants and others exempt from mandatory insurance',
    },
    {
      t: 'p',
      x: 'If you are a German civil servant or are otherwise exempt from German mandatory pension insurance at the time you apply, § 210 Abs. 1a SGB VI can allow a refund of the contributions you paid before that. Typical cases are civil servants with permanent status, professionals exempted for their current employment through a professional pension scheme, and staff of international organisations in Germany exempted under a headquarters agreement. The route does not turn on your citizenship or your address, but it has its own conditions and exclusions:',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'the exempt status still exists when you apply;',
          sp: [],
        },
        {
          x: 'your record, including periods that must be combined internationally, stays under the five-year qualifying period (allgemeine Wartezeit);',
          sp: [],
        },
        {
          x: 'the 24-month waiting period has passed — it applies to this route as well;',
          sp: [],
        },
        {
          x: 'the status is permanent: no refund while you are a civil servant or judge on probation or for a fixed term, a trainee civil servant in preparatory service, a fixed-term soldier, or only temporarily exempt — the refund can follow once the status becomes permanent;',
          sp: [],
        },
        {
          x: 'an exemption based solely on marginal employment (a minijob) does not qualify;',
          sp: [],
        },
        {
          x: 'paying voluntary contributions during the exemption ends the claim; a voluntary contribution paid during an earlier temporary status does not count against you if you apply once your status is permanent.',
          sp: [],
        },
      ],
    },
    {
      t: 'p',
      x: 'It is a specific rule for people who have left the insured system through an exemption, not a general refund route for UK citizens. If it may apply to you, your case needs an individual check before anything is filed.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Need to check your own case?',
      id: 'need-to-check-your-own-case',
    },
    {
      t: 'p',
      x: 'Most UK cases are as clear as this article. If yours is one of the exceptions — you have reached German retirement age, you are exempt from mandatory insurance, or you are a non-UK citizen who has left the UK — we check your eligibility individually before anything is filed. Contact us for an individual review, or use the free eligibility check for a preliminary indication based on the standard rules.',
      sp: [
        {
          k: 'a',
          x: 'Contact us',
          href: '/contact-us',
        },
        {
          k: 'a',
          x: 'eligibility check',
          href: '/refund-calculator',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a service operated by ATLAES GmbH, Berlin. Germany Pension Refund is a private service. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. This article gives general information, not an individual decision or legal or pension advice. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
    {
      t: 'faq',
    },
    {
      t: 'h2',
      x: 'Legal sources and further reading',
      id: 'legal-sources-and-further-reading',
    },
    {
      t: 'ul',
      items: [
        {
          x: '§ 7 SGB VI — voluntary insurance',
          sp: [
            {
              k: 'a',
              x: '§ 7 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__7.html',
            },
          ],
        },
        {
          x: '§ 210 SGB VI — contribution refund: the ordinary route (Abs. 1 Nr. 1), the retirement-age rule (Abs. 1 Nr. 2) and the exemption route (Abs. 1a)',
          sp: [
            {
              k: 'a',
              x: '§ 210 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__210.html',
            },
          ],
        },
        {
          x: 'Regulation (EC) No 883/2004 — EU social security coordination, including Annex XI (Germany) on voluntary insurance',
          sp: [
            {
              k: 'a',
              x: 'Regulation (EC) No 883/2004',
              href: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32004R0883',
            },
          ],
        },
        {
          x: 'EU–UK Withdrawal Agreement — Articles 30 to 32',
          sp: [
            {
              k: 'a',
              x: 'EU–UK Withdrawal Agreement',
              href: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12020W/TXT',
            },
          ],
        },
        {
          x: 'EU–UK Trade and Cooperation Agreement — Protocol on Social Security Coordination, including Article SSC.52 and Annex SSC-6',
          sp: [
            {
              k: 'a',
              x: 'EU–UK Trade and Cooperation Agreement',
              href: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:22021A0430%2801%29',
            },
          ],
        },
        {
          x: 'Deutsche Rentenversicherung guidance (in German): voluntary insurance under § 7 SGB VI, including UK citizens and UK residents · who the Withdrawal Agreement covers · legal bases between Germany and the UK',
          sp: [
            {
              k: 'a',
              x: 'voluntary insurance under § 7 SGB VI, including UK citizens and UK residents',
              href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/01_GRA_SGB/06_SGB_VI/pp_0001_25/gra_sgb006_p_0007.html',
            },
            {
              k: 'a',
              x: 'who the Withdrawal Agreement covers',
              href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/02_GRA_EU_SVA/03_Europarecht/06_Abkommen_euvk/06_Austrittsabkommen_EU_und_VK/gra_erfasste_pers_sonderfaelle_austrittsabkommen.html',
            },
            {
              k: 'a',
              x: 'legal bases between Germany and the UK',
              href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/02_GRA_EU_SVA/04_Laender/Vereinigtes_Koenigreich/gra_vereinigtes_koenigreich_00_rcgd.html',
            },
          ],
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Can UK nationals get a German pension refund after Brexit?',
      a: 'Generally no. UK citizens keep the right to pay voluntary German pension contributions after Brexit, and that right blocks a refund before German retirement age, wherever they live. Two routes remain: the retirement-age rule, if the record stays under the five-year qualifying period after all periods are combined, and the exemption route of § 210 Abs. 1a SGB VI for people who are German civil servants or otherwise exempt from German mandatory insurance when they apply.',
      inSchema: true,
    },
    {
      q: 'Did Brexit make German pension refunds possible from the UK?',
      a: "No. Under the Withdrawal Agreement's full coordination rules and under the Trade and Cooperation Agreement alike, a UK citizen keeps the voluntary-insurance right that blocks the ordinary early refund; the Withdrawal Agreement's separate protection of earlier insurance periods matters for pensions, not refunds. For UK citizens and for anyone living in the UK, the outcome is the same as before Brexit.",
      inSchema: true,
    },
    {
      q: 'Can a non-British person living in the UK get a German pension refund?',
      a: 'Not before German retirement age while living in the UK: residence there gives the right to voluntary German insurance, which blocks the ordinary refund. The retirement-age rule and the exemption route do not depend on where you live. After a move to a qualifying country, the rules for your citizenship decide — every citizenship you hold counts, and a UK job restarts the 24-month waiting period, which begins only after that insurance ends.',
      inSchema: true,
    },
    {
      q: 'Does it matter whether I worked in Germany before or after 2021?',
      a: "Not for the refund answer. Whether the Withdrawal Agreement's full rules or the Trade and Cooperation Agreement applies to you, a UK citizen keeps the voluntary-insurance right, and only the retirement-age rule and the exemption route remain. The date can matter for which instrument applies to you, not for the refund outcome.",
      inSchema: true,
    },
    {
      q: 'Can I at least get part of my German contributions back?',
      a: 'No. A German pension refund covers the entire refundable balance in your account and dissolves the German insurance relationship — all or nothing, never a partial payout. If one of the exceptions applies to you, the refund is the full balance; if none applies, there is no refund, not "part".',
      inSchema: true,
    },
    {
      q: 'What happens to my German contributions if I cannot get a refund?',
      a: 'They stay in your German pension account. At German retirement age, with at least five qualifying years — combined UK and other foreign periods count toward them — you have a pension entitlement, usually a German pension payable anywhere; German periods of less than one year can be taken into account by the UK or another coordinating country instead. With fewer than five qualifying years even after combining, you can apply for the refund then, without a 24-month waiting period.',
      inSchema: true,
    },
    {
      q: 'I am a UK citizen and also hold another citizenship — does that help?',
      a: 'No. Every citizenship you hold counts, and one blocking citizenship is enough: UK citizenship blocks the ordinary refund before retirement age even if your other citizenship would qualify on its own and you have never lived in the UK. The retirement-age rule and the exemption route remain open to dual citizens as to anyone else.',
      inSchema: true,
    },
    {
      q: 'Why does voluntary insurance matter so much?',
      a: 'Because the ordinary early refund under § 210 Abs. 1 Nr. 1 SGB VI is reserved for people who have no right to pay voluntary contributions into the German pension system. If the law gives you that right — through your citizenship or through where you live — that route is blocked, whether or not you ever use it. The retirement-age rule and the exemption route are separate routes in the same section and are not blocked by merely having that right; for the exemption route, actually paying voluntary contributions during the exemption can end the claim.',
      inSchema: true,
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source:
    'GPR_Brexit_Post_Refresh_Content_Handoff_2026-09-10.md (v1.1 refresh)',
};

export default page;
