// Generated by scripts/build-guides.mjs from GPR_Article_Which_Pension_Office_v1.2_2026-08-27.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/post/which-german-pension-office-handles-your-claim',
  kind: 'post',
  lang: 'en',
  title: 'Which DRV Office Handles Your German Pension Refund?',
  meta: 'DRV Bund, Knappschaft-Bahn-See or a regional carrier? See which Deutsche Rentenversicherung office decides your refund claim and where to send it. Free office finder.',
  h1: 'Which German Pension Office Handles Your Refund Claim?',
  headline: 'Which DRV Office Handles Your German Pension Refund?',
  eyebrow: 'Routing guide',
  rail: 'Routing guide',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'News',
      href: '/blog',
    },
    {
      label: 'Which pension office',
    },
  ],
  reviewLine:
    'Source-law review: 7 August 2026 (Canonical Rule Sheet) · Routing facts verified against the official VKVV area-number schedule and the DRV liaison-office table: 25 August 2026',
  showReviewer: true,
  datePublished: '2026-08-27',
  dateModified: '2026-08-27',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: '“The DRV” is not one office. Deutsche Rentenversicherung is a network of 16 carriers: DRV Bund, DRV Knappschaft-Bahn-See, and 14 regional pension offices across Germany. Your contributions sit in an account at exactly one of them — and the office that holds your account is not always the office that decides your international refund claim.',
      sp: [
        {
          k: 'b',
          x: '“The DRV” is not one office.',
        },
      ],
    },
    {
      t: 'p',
      x: 'Which office is in charge is not something you choose, and not something the pension system asks you about. German law sets the framework (§§ 126–128a SGB VI; for Knappschaft-Bahn-See, §§ 129, 130 and 136), and for claims from abroad the DRV assigns specialized liaison offices by country. From three facts — your insurance history, your citizenship and where you live — you can work out the office your claim should go to first.',
      sp: [],
    },
    {
      t: 'p',
      x: 'Short answer — work through these questions from the top. They give you your recommended first office:',
      sp: [
        {
          k: 'b',
          x: 'Short answer — work through these questions from the top. They give you your recommended first office:',
        },
      ],
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Ever insured with Knappschaft-Bahn-See — even one contribution? Then KBS handles your claim, whatever your citizenship or residence. Insurance numbers beginning 38, 39 or 80–89 make this certain: only KBS issues numbers in these ranges.',
          sp: [
            {
              k: 'b',
              x: 'Ever insured with Knappschaft-Bahn-See — even one contribution?',
            },
          ],
        },
        {
          x: 'Was DRV Bund your last carrier? Then DRV Bund handles it. Numbers beginning 40–79 were issued by DRV Bund — a strong indicator, though the issuing office is not always the last carrier.',
          sp: [
            {
              k: 'b',
              x: 'Was DRV Bund your last carrier?',
            },
          ],
        },
        {
          x: 'Otherwise: which country connection fits your case? Where your citizenship connects you to a treaty or EU country with a specialized liaison office, that office is your recommended first address — the table below lists the assignments. If your citizenship has none, the office for your country of residence takes its place.',
          sp: [
            {
              k: 'b',
              x: 'Otherwise: which country connection fits your case?',
            },
          ],
        },
        {
          x: 'More than one connection? If citizenship and residence point to two different treaty countries, more than one liaison office may be relevant. Treat the result as a recommendation and confirm before sending — or ask us.',
          sp: [
            {
              k: 'b',
              x: 'More than one connection?',
            },
          ],
        },
        {
          x: 'No connection at all? Your claim belongs at the regional carrier holding your account — and with no insurance number and no old letters, the office identifies you from your personal data. Your German health insurer (Krankenkasse) is often how an account is found.',
          sp: [
            {
              k: 'b',
              x: 'No connection at all?',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'Our free office finder below applies exactly these rules in a few questions and returns a recommended first office. This guide explains what each rule means, why the deciding office and the account-holding office can be two different places, and what actually happens when a claim lands at the wrong address.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Why the right first office matters',
      id: 'why-the-right-first-office-matters',
    },
    {
      t: 'p',
      x: 'A wrongly addressed claim is not lost. If a German social-benefit office receives your application but is not responsible, it must forward it, and your original filing date is preserved (§ 16 SGB I). That safety net is real — but forwarding is slow: in our operating experience, internal transit has cost weeks, sometimes months, that the right first address would have saved.',
      sp: [
        {
          k: 'a',
          x: '§ 16 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__16.html',
        },
      ],
    },
    {
      t: 'p',
      x: 'And one consequence matters for money: under § 44 SGB I, German law can provide 4% annual interest from the seventh calendar month after a complete application reaches a German pension-insurance carrier. Receipt by an unrelated public-benefit office preserves your application date, but it does not start the interest clock. The best first office is therefore not a formality — it is the most direct route to the carrier that can actually work your file.',
      sp: [
        {
          k: 'a',
          x: '§ 44 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__44.html',
        },
        {
          k: 'b',
          x: 'complete',
        },
        {
          k: 'b',
          x: 'pension-insurance',
        },
      ],
    },
    {
      t: 'src',
      x: 'Official basis: § 16 SGB I · § 44 SGB I · DRV interest guidance',
      sp: [
        {
          k: 'a',
          x: '§ 16 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__16.html',
        },
        {
          k: 'a',
          x: '§ 44 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__44.html',
        },
        {
          k: 'a',
          x: 'DRV interest guidance',
          href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/01_GRA_SGB/01_SGB_I/pp_0026_50/gra_sgb001_p_0044.html',
        },
        {
          k: 'b',
          x: 'Official basis:',
        },
      ],
    },
    {
      t: 'h2',
      x: 'One network, sixteen carriers — and two different jobs',
      id: 'one-network-sixteen-carriers-and-two-different',
    },
    {
      t: 'p',
      x: 'Every insured person’s German pension account is held by one carrier: DRV Bund, DRV Knappschaft-Bahn-See, or one of the 14 regional offices. For claims from abroad, the system adds a second layer: certain regional carriers act as international liaison offices (Verbindungsstellen), each specialized in the social-security connection with particular countries.',
      sp: [
        {
          k: 'b',
          x: 'international liaison offices',
        },
      ],
    },
    {
      t: 'p',
      x: 'The account carrier and the deciding office can be different. A liaison office can be responsible for deciding your claim while a different carrier holds your pension account. Before the deciding office can calculate or approve anything, it must request your digital account or physical file from the carrier that has it.',
      sp: [
        {
          k: 'b',
          x: 'The account carrier and the deciding office can be different.',
        },
      ],
    },
    {
      t: 'p',
      x: 'A real example: an Indian citizen’s regional account sits at DRV Berlin-Brandenburg, while DRV Nord handles the India connection. DRV Nord cannot work the refund until Berlin-Brandenburg releases the file. In some of our managed cases, a period of silence has resulted from exactly this — the account or file being transferred between carriers. Other causes are also possible, so silence alone tells you neither that something is wrong nor that nothing is happening: it is a reason to ask the status questions below, not to panic.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'The six rules, in order (§§ 126–128a SGB VI)',
      id: 'the-six-rules-in-order-126-128a',
    },
    {
      t: 'p',
      x: 'Work from the top: the first rule that fits your case gives your recommended first office. In most cases that is also the office that decides — but where several country connections exist, responsibility can need confirmation (see the note under the table). The Knappschaft-Bahn-See rules sit in §§ 129, 130 and 136 SGB VI.',
      sp: [],
    },
    {
      t: 'h3',
      x: '1. Knappschaft-Bahn-See — if you were ever insured there',
    },
    {
      t: 'p',
      x: 'If you ever paid even one contribution to DRV Knappschaft-Bahn-See — the carrier for mining, railway and maritime employment — KBS is responsible for your entire account. This rule outranks everything else, whatever your citizenship or residence (§§ 129, 130, 136 SGB VI). Insurance numbers beginning 38, 39 or 80–89 settle it: only KBS issues numbers in these ranges. But the reverse is not safe — an older number issued by another office won’t reveal a later KBS period. Your work history does.',
      sp: [
        {
          k: 'b',
          x: '38, 39 or 80–89',
        },
      ],
    },
    {
      t: 'h3',
      x: '2. DRV Bund — if it was your last carrier',
    },
    {
      t: 'p',
      x: 'If your last German contributions ran through DRV Bund, DRV Bund handles the claim. Numbers beginning 40–79 were issued by DRV Bund — a strong indicator, with one honest caveat: the first two digits show which office issued your number, not necessarily the office legally responsible today. That is why the office finder calls its result the recommended first office, not a legal determination.',
      sp: [
        {
          k: 'b',
          x: '40–79',
        },
      ],
    },
    {
      t: 'h3',
      x: '3. The liaison office for your country connection',
    },
    {
      t: 'p',
      x: 'Neither KBS nor Bund? Then your case runs through a country connection. Where your citizenship links you to a treaty or EU country with a specialized liaison office, that office is the recommended first address for the international claim — wherever in the world you live. Indian cases go to DRV Nord: an Indian citizen living in Nepal still starts there, because Nepal adds no connection of its own. The verified assignments for the countries most refund claims involve:',
      sp: [],
    },
    {
      t: 'table',
      rows: [
        ['Country connection', 'Specialized regional liaison office'],
        [
          'United States, Canada, India, United Kingdom, Denmark, Finland, Norway, Sweden',
          'DRV Nord',
        ],
        ['Japan, South Korea, Philippines', 'DRV Braunschweig-Hannover'],
        ['Australia', 'DRV Oldenburg-Bremen'],
        ['Türkiye, Brazil, Portugal, Romania, Moldova', 'DRV Nordbayern'],
        [
          'Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia, Croatia, Slovenia, Austria, Czechia, Slovakia',
          'DRV Bayern Süd',
        ],
        ['Chile, Israel, Uruguay, Belgium, Spain', 'DRV Rheinland'],
        ['Morocco, Tunisia, Italy, Malta', 'DRV Schwaben'],
        ['Albania', 'DRV Rheinland-Pfalz'],
        ['Iceland', 'DRV Westfalen'],
        ['Poland', 'DRV Berlin-Brandenburg'],
        ['Greece, Switzerland, Liechtenstein', 'DRV Baden-Württemberg'],
      ],
    },
    {
      t: 'note',
      x: 'This table shows which regional DRV carrier specializes in each country connection. It does not by itself determine which connection controls a particular case: residence, citizenship, foreign insurance periods and the current German account carrier can all affect responsibility, and rules 1 and 2 outrank every row. Where you have connections to more than one treaty or EU country — an Indian citizen living in Brazil, say — more than one liaison office may come into consideration: treat the table’s answer as your recommended first office and confirm before sending. The EU rows matter mostly at retirement age, because EU citizens cannot claim a refund before then (see the eligibility guide). Further verified assignments — Ireland and the Baltic states → DRV Nord; the Netherlands → DRV Westfalen; France and Luxembourg → DRV Rheinland-Pfalz; Hungary, Ukraine and Bulgaria → DRV Mitteldeutschland; Cyprus → DRV Baden-Württemberg — are in the official DRV list and our office finder.',
      sp: [],
    },
    {
      t: 'h3',
      x: '4. The liaison office for your residence',
    },
    {
      t: 'p',
      x: 'If your citizenship has no dedicated liaison office, the office assigned to your country of residence takes its place. This is the rule that catches most “no-agreement” nationalities: a Nigerian living in Canada starts with DRV Nord, because Canada is the residence connection. A Vietnamese citizen in Australia starts with DRV Oldenburg-Bremen — the Australia office. And if both your citizenship and your residence carry a connection, see the note above: more than one office may be relevant.',
      sp: [],
    },
    {
      t: 'h3',
      x: '5. The regional carrier holding your account',
    },
    {
      t: 'p',
      x: 'No liaison connection through citizenship or residence? Then your claim belongs at the regional office shown by your insurance number or your latest pension-office letter — the carrier that holds your account decides directly.',
      sp: [],
    },
    {
      t: 'h3',
      x: '6. No number, no letters — identification by personal data',
    },
    {
      t: 'p',
      x: 'If you worked in Germany, an insurance number exists — a lost number is not the same as a number that was never assigned. Write to the most likely original regional office and give it everything that identifies you: full name and former names, date and place of birth, your last German address, your German employers — and your health insurer, which is often how an account is found. An unidentified application to DRV Bund is rarely the best first move when your account exists at another carrier. (German law does make DRV Bund responsible until an insurance number has been assigned — § 127 SGB VI — but that covers people who never received a number, which hardly ever applies to someone with German work history.) In a managed claim, we can help identify or recover a missing German pension insurance number; if no number can be found, the claim can still be submitted using other identifiers, such as your full name, date of birth and last registered address in Germany. Processing may take longer without the number, and recovery cannot be guaranteed in every case.',
      sp: [
        {
          k: 'a',
          x: '§ 127 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__127.html',
        },
      ],
    },
    {
      t: 'src',
      x: 'Official basis: §§ 126–128a SGB VI · § 127 SGB VI · §§ 129, 130, 136 SGB VI · DRV guidance (GRA) on § 126 · DRV guidance (GRA) on § 128 · DRV liaison-office overview · DRV carrier addresses',
      sp: [
        {
          k: 'a',
          x: '§§ 126–128a SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__126.html',
        },
        {
          k: 'a',
          x: '§ 127 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__127.html',
        },
        {
          k: 'a',
          x: '§§ 129, 130, 136 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__129.html',
        },
        {
          k: 'a',
          x: 'DRV guidance (GRA) on § 126',
          href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/01_GRA_SGB/06_SGB_VI/pp_0126_150/gra_sgb006_p_0126.html',
        },
        {
          k: 'a',
          x: 'DRV guidance (GRA) on § 128',
          href: 'https://rvrecht.deutsche-rentenversicherung.de/SharedDocs/rvRecht/01_GRA_SGB/06_SGB_VI/pp_0126_150/gra_sgb006_p_0128.html',
        },
        {
          k: 'a',
          x: 'DRV liaison-office overview',
          href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Ansprechpartner-und-Verbindungsstellen/ansprechpartner-und-verbindungsstellen_node.html',
        },
        {
          k: 'a',
          x: 'DRV carrier addresses',
          href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Beratung-und-Kontakt/Kontakt/Anschriften-Uebersicht/anschriften-uebersicht_node.html',
        },
        {
          k: 'b',
          x: 'Official basis:',
        },
      ],
    },
    {
      t: 'h2',
      x: 'What the first two digits of your number can — and can’t — tell you',
      id: 'what-the-first-two-digits-of-your',
    },
    {
      t: 'p',
      x: 'Your German insurance number (Versicherungsnummer, on payslips often SVNR) starts with two digits identifying the office that issued it (§ 147 SGB VI; the assignments are set in the official schedule to the VKVV). Three ranges are worth knowing by heart:',
      sp: [
        {
          k: 'a',
          x: '§ 147 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__147.html',
        },
        {
          k: 'a',
          x: 'official schedule to the VKVV',
          href: 'https://www.gesetze-im-internet.de/vkvv/anlage.html',
        },
      ],
    },
    {
      t: 'ul',
      items: [
        {
          x: '38, 39 and 80–89: issued only by Knappschaft-Bahn-See — KBS was involved, and KBS decides. This one is certain.',
          sp: [
            {
              k: 'b',
              x: '38, 39 and 80–89:',
            },
          ],
        },
        {
          x: '40–79: issued by DRV Bund — your account is most likely held there. (The schedule forms these numbers by adding 40 to a regional district number.)',
          sp: [
            {
              k: 'b',
              x: '40–79:',
            },
          ],
        },
        {
          x: 'All other valid prefixes: issued by a regional carrier — the table below maps each district number to today’s carrier. The digits point to the office that opened your account: useful as a first address when no rule above applies, but not proof of who is responsible today.',
          sp: [
            {
              k: 'b',
              x: 'All other valid prefixes:',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'Some numbers within these ranges are not allocated. The ranges above apply to valid German pension insurance numbers. (One look-alike to avoid: a number beginning 40 on Riester paperwork is a Zulagenstelle number, not a pension insurance number.)',
      sp: [],
    },
    {
      t: 'table',
      rows: [
        [
          'First two digits (issuing district)',
          'Issuing office — today’s carrier',
        ],
        [
          '02 Mecklenburg-Vorpommern · 19 Hamburg · 26 Schleswig-Holstein',
          'DRV Nord',
        ],
        [
          '03 Thüringen · 08 Sachsen-Anhalt · 09 Sachsen',
          'DRV Mitteldeutschland',
        ],
        ['04 Brandenburg · 25 Berlin', 'DRV Berlin-Brandenburg'],
        ['10 Hannover · 29 Braunschweig', 'DRV Braunschweig-Hannover'],
        ['11 Westfalen', 'DRV Westfalen'],
        ['12 Hessen', 'DRV Hessen'],
        ['13 Rheinprovinz', 'DRV Rheinland'],
        ['14 Oberbayern · 15 Niederbayern-Oberpfalz', 'DRV Bayern Süd'],
        ['16 Rheinland-Pfalz', 'DRV Rheinland-Pfalz'],
        ['17 Saarland', 'DRV Saarland'],
        ['18 Ober- und Mittelfranken · 20 Unterfranken', 'DRV Nordbayern'],
        ['21 Schwaben', 'DRV Schwaben'],
        ['23 Württemberg · 24 Baden', 'DRV Baden-Württemberg'],
        ['28 Oldenburg-Bremen', 'DRV Oldenburg-Bremen'],
        [
          '38 Bahn · 39 Seefahrt · 80–89 Knappschaft districts',
          'DRV Knappschaft-Bahn-See',
        ],
        ['40–79 (regional district number + 40)', 'DRV Bund'],
      ],
    },
    {
      t: 'note',
      x: 'Source: Anlage to § 2 Abs. 2 VKVV. The schedule names historical insurance districts; the right-hand column shows the merged carrier that holds those accounts today.',
      sp: [],
    },
    {
      t: 'p',
      x: 'The issuing office is far more likely to find your record than an unrelated office — that is the digits’ real value. → German social security number If responsibility turns out to differ, the receiving office forwards your file with the application date preserved.',
      sp: [
        {
          k: 'a',
          x: '→ German social security number',
          href: '/post/german-social-security-number',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Routing can change your paperwork — the Oldenburg-Bremen example',
      id: 'routing-can-change-your-paperwork-the-oldenburg',
    },
    {
      t: 'p',
      x: 'Which office your claim lands at can even decide how much paper touches your hands. Most clients can complete their entire side of the process digitally. The main current exception is carrier-based: when DRV Oldenburg-Bremen is responsible for the refund, Germany Pension Refund prepares the power of attorney and payment declaration and asks the client to send the signed originals to us. That covers Australian cases handled by Oldenburg-Bremen — Australia’s liaison office — and clients of any nationality whose responsible account carrier is Oldenburg-Bremen. It does not apply merely because a client is Australian: Australian cases assigned to DRV Bund or Knappschaft-Bahn-See remain digital for the client. If your carrier has never changed, an insurance number beginning 28 identifies Oldenburg-Bremen — an indicator, not a permanent guarantee. Same passport, different office, different paperwork — routing is why.',
      sp: [],
    },
    {
      t: 'p',
      x: 'If you apply on your own from abroad, this distinction matters less: a DIY application travels to Germany as signed paper originals in every route, because ordinary email is not accepted as an identity-safe filing channel and fax has been discontinued.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'How to find out who has your file right now',
      id: 'how-to-find-out-who-has-your',
    },
    {
      t: 'p',
      x: 'If your claim was forwarded, the first office normally sends an Abgabemitteilung — a short letter naming the new carrier and telling you to contact that office from then on. Keep it: it tells you who owns your file. No letter? Call or write with your insurance number, full name, date of birth, submission date and proof of delivery, and ask four questions in this order:',
      sp: [],
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Which office is responsible for my claim?',
          sp: [],
        },
        {
          x: 'Has that office received my account file?',
          sp: [],
        },
        {
          x: 'Is anything missing from me?',
          sp: [],
        },
        {
          x: 'What is the next processing step?',
          sp: [],
        },
      ],
    },
    {
      t: 'p',
      x: 'In our experience, those four answers locate a file faster than general chasing, because they distinguish “wrong office”, “file in transit” and “waiting on you” — three situations that need three different responses.',
      sp: [],
    },
    {
      t: 'faq',
    },
    {
      t: 'h2',
      x: 'Next step',
      id: 'next-step',
    },
    {
      t: 'p',
      x: 'Use the free office finder above for your recommended first office, then follow the application chapter of our complete refund guide. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee. Prefer not to manage routing yourself? In a managed claim, we identify the recommended first pension office and route the claim accordingly — the account carrier and deciding office can differ, and the DRV may forward the file.',
      sp: [
        {
          k: 'a',
          x: 'complete refund guide',
          href: '/post/how-to-get-a-german-pension-refund',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a private service. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. This guide gives general information, not an individual decision.',
      sp: [],
    },
    {
      t: 'src',
      x: 'Official basis: §§ 126, 127, 127a, 128 and 128a SGB VI · §§ 129, 130, 136 SGB VI · § 147 SGB VI · VKVV Anlage (Bereichsnummern) · § 16 SGB I · § 44 SGB I · DRV liaison-office overview · DRV carrier addresses',
      sp: [
        {
          k: 'a',
          x: '§§ 126, 127, 127a, 128 and 128a SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__126.html',
        },
        {
          k: 'a',
          x: '§§ 129, 130, 136 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__129.html',
        },
        {
          k: 'a',
          x: '§ 147 SGB VI',
          href: 'https://www.gesetze-im-internet.de/sgb_6/__147.html',
        },
        {
          k: 'a',
          x: 'VKVV Anlage (Bereichsnummern)',
          href: 'https://www.gesetze-im-internet.de/vkvv/anlage.html',
        },
        {
          k: 'a',
          x: '§ 16 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__16.html',
        },
        {
          k: 'a',
          x: '§ 44 SGB I',
          href: 'https://www.gesetze-im-internet.de/sgb_1/__44.html',
        },
        {
          k: 'a',
          x: 'DRV liaison-office overview',
          href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Rente/Ausland/Ansprechpartner-und-Verbindungsstellen/ansprechpartner-und-verbindungsstellen_node.html',
        },
        {
          k: 'a',
          x: 'DRV carrier addresses',
          href: 'https://www.deutsche-rentenversicherung.de/DRV/DE/Beratung-und-Kontakt/Kontakt/Anschriften-Uebersicht/anschriften-uebersicht_node.html',
        },
        {
          k: 'b',
          x: 'Official basis:',
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Can I just send my application to DRV Bund in Berlin?',
      a: 'You can — but unless a rule above actually points there, it is rarely the best first move. DRV Bund is the best-known address, not the default one: a claim sent there without a Bund connection must be identified, matched and forwarded, and each hop costs time. Start with the office the six rules point to — in our experience it usually identifies you fastest and loses the least time if responsibility differs. One legal footnote: for people to whom no German insurance number has ever been assigned, § 127 SGB VI does make DRV Bund initially responsible — but if you worked in Germany, you have a number, even if you can’t find it.',
      inSchema: false,
      blocks: [
        {
          t: 'p',
          x: 'You can — but unless a rule above actually points there, it is rarely the best first move. DRV Bund is the best-known address, not the default one: a claim sent there without a Bund connection must be identified, matched and forwarded, and each hop costs time. Start with the office the six rules point to — in our experience it usually identifies you fastest and loses the least time if responsibility differs. One legal footnote: for people to whom no German insurance number has ever been assigned, § 127 SGB VI does make DRV Bund initially responsible — but if you worked in Germany, you have a number, even if you can’t find it.',
          sp: [
            {
              k: 'a',
              x: '§ 127 SGB VI',
              href: 'https://www.gesetze-im-internet.de/sgb_6/__127.html',
            },
          ],
        },
      ],
    },
    {
      q: 'I sent my claim to the wrong office — is my application date lost?',
      a: 'No. A German social-benefit office that is not responsible must forward your application, and your original filing date is preserved (§ 16 SGB I). In our operating experience the transit has cost weeks; watch for the Abgabemitteilung naming the new carrier — and remember the fine print: the statutory-interest clock only starts once a complete application reaches a German pension-insurance carrier.',
      inSchema: false,
    },
    {
      q: 'Do the first two digits of my insurance number prove which office is responsible?',
      a: 'No — with one exception. Numbers beginning 38, 39 or 80–89 are issued only by Knappschaft-Bahn-See, so KBS involvement is certain. Every other valid prefix shows the office that issued your number, which is not necessarily the office legally responsible today. Treat the digits as the best first address, not as proof — and note that some numbers within the ranges are simply not allocated; the rules apply to valid German pension insurance numbers.',
      inSchema: false,
    },
    {
      q: 'My citizenship and my residence point to two different offices — which one is right?',
      a: 'Then you have more than one country connection, and more than one liaison office may come into consideration — this is exactly the situation the DRV’s own guidance treats as needing case-by-case determination. As a practical matter: citizenship connections are the usual starting point, the recommended first office is a recommendation rather than a legal determination, and § 16 SGB I protects your filing date if the file must move. In a managed claim we confirm the routing before submission; if you file yourself, name both connections in your cover letter so the receiving office can pass the file correctly the first time.',
      inSchema: false,
    },
    {
      q: 'Why is a different office answering than the one that holds my account?',
      a: 'Because the deciding office and the account carrier can be two different places. For international claims, a liaison office specialized in your country connection decides — and it must first request your account or file from the carrier holding it. A change of correspondent mid-claim usually means routing worked, not that something went wrong.',
      inSchema: false,
    },
    {
      q: 'Does the responsible office affect how fast I get paid?',
      a: 'The right first office avoids forwarding and file-hunting — the avoidable delays. Beyond that, we cannot guarantee a decision or payment date because the responsible pension office controls processing. What you control is a complete application at the right first address; the interest rule in § 44 SGB I exists for cases that still take too long. How long completed refunds actually took: see the full data and methodology.',
      inSchema: false,
      blocks: [
        {
          t: 'p',
          x: 'The right first office avoids forwarding and file-hunting — the avoidable delays. Beyond that, we cannot guarantee a decision or payment date because the responsible pension office controls processing. What you control is a complete application at the right first address; the interest rule in § 44 SGB I exists for cases that still take too long. How long completed refunds actually took: see the full data and methodology.',
          sp: [
            {
              k: 'a',
              x: 'see the full data and methodology',
              href: '/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      q: 'What if I have no insurance number and no old letters at all?',
      a: 'Your account can still be found — from your personal data. Provide full name and former names, date and place of birth, last German address, employers and your German health insurer; the health insurer is often the key. Write to the most likely original regional office rather than sending an unidentified claim to DRV Bund (see the § 127 footnote above for the rare never-assigned case).',
      inSchema: false,
    },
  ],
  faqInSchema: false,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source: 'GPR_Article_Which_Pension_Office_v1.2_2026-08-27.md',
};

export default page;
