// Generated by scripts/build-guides.mjs from GPR_FormsPage_A1310_EN_v1.3_2026-09-08.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/a1310-payment-declaration',
  kind: 'guide',
  lang: 'en',
  title: 'Form A1310: German Pension Refund Payment Declaration (2026)',
  meta: 'A1310 is the signed payment declaration DRV uses to pay your German pension refund abroad. Which edition to download, how to complete it, what to check.',
  h1: 'Form A1310: The Payment Declaration (Zahlungserklärung) for Your German Pension Refund, Explained in English',
  headline: 'Form A1310: German Pension Refund Payment Declaration',
  eyebrow: 'Form guide · A1310',
  rail: 'Form guide',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'Forms & guides',
      href: '/download',
    },
    {
      label: 'A1310',
    },
  ],
  reviewLine: 'Last checked: 8 September 2026',
  showReviewer: true,
  datePublished: '2026-09-09',
  dateModified: '2026-09-10',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: 'The short answer: Form A1310 („Zahlungserklärung für alle Länder (nicht für Italien)" — payment declaration for all countries except Italy) is the official Deutsche Rentenversicherung (DRV) form that records the bank account your refund is to be paid to — and the people authorized to use that account. The refund application from abroad, V0901, asks for payment details too (Section 11), but in the refund cases we see, DRV generally still requires the separate, signed A1310 as the payment declaration used for the payout — in practice it accompanies almost every refund application from abroad. The two-page PDF is free, in five language editions including German/English (Version 8, Stand 01.07.2026); Italy has its own edition, A1311. This guide explains which edition to download, what each section asks, and what to check before you sign.',
      sp: [
        {
          k: 'b',
          x: 'The short answer:',
        },
      ],
    },
    {
      t: 'p',
      x: 'Official form (free): A1310 German/English — official DRV form page · All editions, A1311 and the other refund forms, explained: → Downloads — official DRV forms',
      sp: [
        {
          k: 'a',
          x: 'A1310 German/English — official DRV form page',
          href: 'drv:A1310',
        },
        {
          k: 'a',
          x: '→ Downloads — official DRV forms',
          href: '/download',
        },
        {
          k: 'b',
          x: 'Official form (free):',
        },
        {
          k: 'b',
          x: 'All editions, A1311 and the other refund forms, explained:',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Why the pension office wants a signed A1310',
      id: 'why-the-pension-office-wants-a-signed',
    },
    {
      t: 'p',
      x: 'In the refund cases we see, the pension office generally releases the refund only once it has a completed, signed payment declaration identifying the payment account. The decision (Bescheid) says how much is refunded; the payment declaration says where the money goes and who may use that account. After the decision, the payment itself is executed by the Renten Service of Deutsche Post AG, a separate payout institution acting for the pension insurance.',
      sp: [],
    },
    {
      t: 'p',
      x: "Why a separate form when V0901 already asks for your bank account? V0901's payment section is short. The A1310 records the payment route, the account holder and any additional person authorized to use the account in more detail, with its own signature lines — and in the refund cases we handle, DRV offices use this separately signed declaration for the payout. Sending it with the application can help avoid a later request.",
      sp: [],
    },
    {
      t: 'p',
      x: 'A German bank account is not required. The account you name must be usable for the payment route and the required declarations — sanctions and banking restrictions can still matter. The form asks for IBAN and BIC/SWIFT where those identifiers apply; for other banking systems, it provides account-number and national-routing fields. Bank charges and exchange-rate losses on transfers abroad are borne by the recipient, as DRV states in its information on payments abroad.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Which edition to download',
      id: 'which-edition-to-download',
    },
    {
      t: 'p',
      x: 'One form number, five language editions. All five have the same form number and purpose — a payment declaration "for all countries (not for Italy)" — but their version numbers and printed notes differ. The German text is what the pension office processes; the other language is there so you can read and complete it. This walkthrough follows German/English Version 8. If you use another edition, follow the notes printed on that form.',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'German/English — Version 8, Stand 01.07.2026 → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: 'Official DRV form page',
              href: 'drv:A1310:de-en',
            },
            {
              k: 'b',
              x: 'German/English',
            },
          ],
        },
        {
          x: 'German/French — Version 8, Stand 01.07.2026 → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: 'Official DRV form page',
              href: 'drv:A1310:de-fr',
            },
            {
              k: 'b',
              x: 'German/French',
            },
          ],
        },
        {
          x: 'German/Spanish — Version 6, Stand 01.07.2026 → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: 'Official DRV form page',
              href: 'drv:A1310:de-es',
            },
            {
              k: 'b',
              x: 'German/Spanish',
            },
          ],
        },
        {
          x: 'German/Portuguese — Version 6, Stand 01.07.2026 → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: 'Official DRV form page',
              href: 'drv:A1310:de-pt',
            },
            {
              k: 'b',
              x: 'German/Portuguese',
            },
          ],
        },
        {
          x: 'German/Greek/Turkish (trilingual) — Version 7, Stand 01.07.2025 → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: 'Official DRV form page',
              href: 'drv:A1310:de-el-tr',
            },
            {
              k: 'b',
              x: 'German/Greek/Turkish',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'All five verified on the official DRV form pages on 4 September 2026; download from the official page — it carries the current version. DRV asks for double-sided (duplex) printing; the PDF can be filled in on screen and is signed on paper. Older numbers you may still find in search — A1312, A1313, A3863 — are retired, and their DRV pages no longer exist; every current edition carries the number A1310.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'A1310, A1311 or R0985?',
      id: 'a1310-a1311-or-r0985',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'A1310 — the payment declaration for an account in any country except Italy; in the refund cases we see, it accompanies almost every refund paid abroad.',
          sp: [
            {
              k: 'b',
              x: 'A1310',
            },
          ],
        },
        {
          x: 'A1311 („Zahlungserklärung Italien", German/Italian; Version 6, Stand 02.05.2025) — the Italy edition. → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:A1311',
            },
            {
              k: 'b',
              x: 'A1311',
            },
          ],
        },
        {
          x: 'R0985 („Angaben zum Zahlungsweg", German; Version 16, Stand 01.07.2025) — described by DRV\'s online service as the payment-route form for a German domestic account („Angaben zum Zahlungsweg bei Inlandskonto"); not the form for an account abroad. → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:R0985',
            },
            {
              k: 'b',
              x: 'R0985',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Completing A1310, section by section',
      id: 'completing-a1310-section-by-section',
    },
    {
      t: 'p',
      x: 'Work from the German/English edition (Version 8, Stand 01.07.2026) and let the English text guide you — the pension office reads the German. The form is two pages.',
      sp: [],
    },
    {
      t: 'p',
      x: "1. You and the account. Your name, your address abroad and your German insurance number (Versicherungsnummer) — exactly as on your refund application, so the declaration can be matched to your file. Then the account: the bank's name and address; the IBAN and BIC/SWIFT where those identifiers apply — for other banking systems, the account-number and national-routing fields the form provides. Three fields are easy to miss: the EURO account checkbox (subject to the country exceptions printed on the form); for a US account, whether it is a checking or savings account; and, where your banking system uses one, the routing number, BSB number or branch/institution number. Copy every identifier from your bank's own documents — one wrong digit can stop or misdirect a transfer. Lost your insurance number? → German social security number",
      sp: [
        {
          k: 'a',
          x: '→ German social security number',
          href: '/post/german-social-security-number',
        },
        {
          k: 'b',
          x: '1. You and the account.',
        },
        {
          k: 'b',
          x: 'EURO account',
        },
        {
          k: 'b',
          x: 'checking or savings',
        },
        {
          k: 'b',
          x: 'routing number, BSB number or branch/institution number',
        },
      ],
    },
    {
      t: 'p',
      x: '2. Section 2 — who may use the account. Tick exactly one of the four options:',
      sp: [
        {
          k: 'b',
          x: '2. Section 2 — who may use the account.',
        },
      ],
    },
    {
      t: 'ol',
      items: [
        {
          x: 'You alone are authorized to use the account.',
          sp: [],
        },
        {
          x: 'You have granted another person authority over the account — the form does not offer this for US or Canadian accounts.',
          sp: [],
        },
        {
          x: 'It is a joint account — for a US or Canadian joint account, the form accepts this only where the joint holder is your spouse.',
          sp: [],
        },
        {
          x: 'You are not the account holder — the current form offers this only for an account at a financial institution in the EU.',
          sp: [],
        },
      ],
    },
    {
      t: 'p',
      x: 'Where none of the options fits your situation, name an account of your own instead.',
      sp: [],
    },
    {
      t: 'p',
      x: '3. Section 3 — the additional person. Depending on the option ticked in Section 2, Section 3 records the joint account holder, the person authorized to use the account, or the payment recipient.',
      sp: [
        {
          k: 'b',
          x: '3. Section 3 — the additional person.',
        },
      ],
    },
    {
      t: 'p',
      x: "4. Signatures. You sign and date the printed form; each additional person named in Section 3 signs the corresponding signature line. The second page carries the Renten Service's data-protection notice.",
      sp: [
        {
          k: 'b',
          x: '4. Signatures.',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Signing and sending',
      id: 'signing-and-sending',
    },
    {
      t: 'p',
      x: 'Print the completed declaration double-sided, sign it, and send it with your refund application on paper to the pension office responsible for your claim — which office that is follows from your insurance history and where you live. → Which German pension office handles your claim If an office has already written to you asking for a payment declaration, reply to that office and quote its reference. Keep a complete copy with the posting date. Ordinary email is not an accepted filing route, because email cannot establish your identity.',
      sp: [
        {
          k: 'a',
          x: '→ Which German pension office handles your claim',
          href: '/post/which-german-pension-office-handles-your-claim',
        },
      ],
    },
    {
      t: 'h2',
      x: 'The mistakes that hold up payment',
      id: 'the-mistakes-that-hold-up-payment',
    },
    {
      t: 'ol',
      items: [
        {
          x: 'An account-holder option the form does not allow for that account. Account authority for another person on a US or Canadian account; a joint US or Canadian account with anyone but your spouse; an account you do not hold outside the EU.',
          sp: [
            {
              k: 'b',
              x: 'An account-holder option the form does not allow for that account.',
            },
          ],
        },
        {
          x: 'Incomplete bank identifiers. An omitted or mistyped IBAN or BIC/SWIFT where those identifiers apply, no routing, BSB or branch number where the banking system uses one, or the wrong checking/savings box for a US account — the office has to come back to you before it can pay.',
          sp: [
            {
              k: 'b',
              x: 'Incomplete bank identifiers.',
            },
          ],
        },
        {
          x: "Missing signatures. Yours — and the Section 3 person's where the option ticked in Section 2 requires one.",
          sp: [
            {
              k: 'b',
              x: 'Missing signatures.',
            },
          ],
        },
        {
          x: 'Printing single-sided or leaving page two out. DRV asks for double-sided printing; an incomplete form is not usable.',
          sp: [
            {
              k: 'b',
              x: 'Printing single-sided or leaving page two out.',
            },
          ],
        },
        {
          x: "An old form. A PDF numbered A1312, A1313 or A3863, or an A1310 with an older Stand, from a third-party site. Use the current edition from DRV's own page.",
          sp: [
            {
              k: 'b',
              x: 'An old form.',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Living in Morocco or Tunisia?',
      id: 'living-in-morocco-or-tunisia',
    },
    {
      t: 'p',
      x: 'If you live in Morocco, Article 35 of the German–Moroccan social-security agreement routes the payment through a Moroccan bank to an account in your own name, and residents of Tunisia are in practice paid the same way — how payment works there is explained on our Morocco and Tunisia pages. Morocco · Tunisia',
      sp: [
        {
          k: 'a',
          x: 'Morocco',
          href: '/morocco',
        },
        {
          k: 'a',
          x: 'Tunisia',
          href: '/tunisia',
        },
      ],
    },
    {
      t: 'h2',
      x: 'In a managed claim',
      id: 'in-a-managed-claim',
    },
    {
      t: 'p',
      x: 'In managed claims, we prepare the correct payment declaration for your payout route — this is also where account-holder checks and banking restrictions are handled. Your refund is paid through the escrow account operated by our German partner law firm; after the agreed fee is deducted, the remaining balance is transferred to the bank account you nominate. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent. fee details · Check your eligibility',
      sp: [
        {
          k: 'a',
          x: 'fee details',
          href: '/pricing',
        },
        {
          k: 'a',
          x: 'Check your eligibility',
          href: '/refund-calculator',
        },
      ],
    },
    {
      t: 'faq',
    },
    {
      t: 'h2',
      x: 'Official downloads and further guides',
      id: 'official-downloads-and-further-guides',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'A1310, German/English (Version 8, Stand 01.07.2026): → Official DRV form page — the other four editions, A1311 and R0985: → Downloads — official DRV forms',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:A1310:de-en',
            },
            {
              k: 'a',
              x: '→ Downloads — official DRV forms',
              href: '/download',
            },
            {
              k: 'b',
              x: 'A1310, German/English',
            },
          ],
        },
        {
          x: 'The refund application itself, section by section: → V0901 form guide (English)',
          sp: [
            {
              k: 'a',
              x: '→ V0901 form guide (English)',
              href: '/v0901-pension-refund-form-english',
            },
            {
              k: 'b',
              x: 'The refund application itself, section by section:',
            },
          ],
        },
        {
          x: 'Which pension office handles your claim: → Which German pension office handles your claim',
          sp: [
            {
              k: 'a',
              x: '→ Which German pension office handles your claim',
              href: '/post/which-german-pension-office-handles-your-claim',
            },
            {
              k: 'b',
              x: 'Which pension office handles your claim:',
            },
          ],
        },
        {
          x: 'The complete guide to the whole refund process — eligibility, timing, payout: How to Get a German Pension Refund (2026)',
          sp: [
            {
              k: 'a',
              x: 'How to Get a German Pension Refund (2026)',
              href: '/post/how-to-get-a-german-pension-refund',
            },
            {
              k: 'b',
              x: 'The complete guide to the whole refund process — eligibility, timing, payout:',
            },
          ],
        },
      ],
    },
    {
      t: 'src',
      x: "Sources: DRV form A1310 in its five language editions (German/English Version 8, Stand 01.07.2026; German/French Version 8, Stand 01.07.2026; German/Spanish Version 6, Stand 01.07.2026; German/Portuguese Version 6, Stand 01.07.2026; German/Greek/Turkish Version 7, Stand 01.07.2025) · DRV form V0901 (Section 11) · DRV form A1311 (Version 6, Stand 02.05.2025) · DRV form R0985 (Version 16, Stand 01.07.2025) and DRV's online-service description · DRV information on pension payments abroad · our V0901 guide, forms registry and routing guide.",
      sp: [
        {
          k: 'b',
          x: 'Sources:',
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Do I need A1310 if I am filing V0901?',
      a: 'In practice, almost always — yes. V0901 asks for payment details in Section 11, but in the refund cases we see, DRV generally still requires the separate, signed A1310 as the payment declaration for the payout. Italy uses A1311.',
      inSchema: true,
    },
    {
      q: 'Which language edition should I use?',
      a: 'Any of the five — they share the form number and purpose, but their version numbers and printed notes differ. The German text is what the office processes; pick the edition whose other language you read best, whatever country you live in. This guide follows German/English Version 8 — if you use another edition, follow the notes printed on that form.',
      inSchema: true,
    },
    {
      q: "Can the refund go to someone else's account?",
      a: 'Only within the options the form offers. On the current A1310, an account you do not hold can be named only where it is at a financial institution in the EU; a joint US or Canadian account is accepted only with your spouse as joint holder; and account authority for another person is not offered for US or Canadian accounts. The other person is entered in Section 3 and signs. In a managed claim, a third-party account can be used where the required account-holder declaration and compliance checks are satisfied. Account-holder checks, international sanctions and banking restrictions can limit where — and in which currency — the money can be sent.',
      inSchema: true,
    },
    {
      q: 'Is a German bank account required?',
      a: 'No. A German bank account is not required. The account must be usable for the payment route and the required declarations; sanctions and banking restrictions can still matter.',
      inSchema: true,
    },
    {
      q: 'My bank details have changed after I sent the form — what now?',
      a: 'Tell the pension office handling your claim immediately. For a replacement account abroad, send a new, signed payment declaration — A1310, or A1311 for Italy — and state that it replaces the earlier one. For a German domestic account, use R0985. Once you have the decision, follow the payment instructions in it.',
      inSchema: true,
    },
    {
      q: 'I am a managed client and was asked to post the original payment declaration — why?',
      a: 'Most clients can complete their Germany Pension Refund steps digitally. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule.',
      inSchema: true,
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source:
    'GPR_FormsPage_A1310_EN_v1.3_2026-09-08.md + cornerstone line (FAQ markup package, 10 Sep 2026)',
};

export default page;
