// Generated by scripts/build-guides.mjs from GPR_FormsPage_V0100_EN_v1.3_2026-09-04.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/v0100-form',
  kind: 'guide',
  lang: 'en',
  title: 'Form V0100: German Pension Account Clarification (2026)',
  meta: 'The pension office sent you form V0100? What a Kontenklärung is, how to clear your German pension record from abroad — and what it means for your refund.',
  h1: 'Form V0100: The German Pension Account Clarification (Kontenklärung), Explained in English',
  headline: 'Form V0100: German Pension Account Clarification',
  eyebrow: 'Form guide · V0100',
  rail: 'Form guide',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'Forms & guides',
      href: '/download',
    },
    {
      label: 'V0100',
    },
  ],
  reviewLine: 'Last checked: 4 September 2026',
  showReviewer: true,
  datePublished: '2026-09-09',
  dateModified: '2026-09-10',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: 'The short answer: Form V0100 („Antrag auf Kontenklärung" — application for account clarification) is the official Deutsche Rentenversicherung (DRV) form for reviewing and completing your German pension record. Many of our readers first meet it in the middle of a refund claim: the pension office sends it, or asks for a Kontenklärung, because it wants your insurance record settled before it decides. It is not itself a rejection — it means the office needs more account information before it can decide. The clarification may simply confirm the record, or it may add periods that change the picture; this guide covers both. The form is free. DRV offers it as a guided online application (recommended) and as a PDF (Version 21, Stand 02.03.2026), with DRV\'s own explanations in V0110.',
      sp: [
        {
          k: 'b',
          x: 'The short answer:',
        },
      ],
    },
    {
      t: 'p',
      x: "Official and free: Kontenklärung online — DRV eAntrag · V0100 as PDF — official DRV form page · V0110 — DRV's explanations to the application",
      sp: [
        {
          k: 'a',
          x: 'Kontenklärung online — DRV eAntrag',
          href: 'eantrag:',
        },
        {
          k: 'a',
          x: 'V0100 as PDF — official DRV form page',
          href: 'drv:V0100',
        },
        {
          k: 'a',
          x: "V0110 — DRV's explanations to the application",
          href: 'drv:V0110',
        },
        {
          k: 'b',
          x: 'Official and free:',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
    {
      t: 'h2',
      x: '"The office sent me V0100 in the middle of my refund claim — is something wrong?"',
      id: 'the-office-sent-me-v0100-in-the',
    },
    {
      t: 'p',
      x: 'No. A refund is decided from the data in your insurance account, and where entries are missing or unconfirmed — school years, training, periods abroad, child-raising, gaps between jobs — the office settles the record first. A Kontenklärung request means your case is being worked on, and the office is telling you exactly what it still needs. The outcome cuts both ways: the clarification can simply confirm what is on file, or it can add months — child-raising periods, for example — that change how your claim is decided. What added months mean is covered in our V0800 guide. → V0800 child-raising-periods guide',
      sp: [
        {
          k: 'a',
          x: '→ V0800 child-raising-periods guide',
          href: '/v0800-child-raising-periods',
        },
      ],
    },
    {
      t: 'p',
      x: 'Some pension carriers ask for a clarification more consistently than others. Based on our managed cases, Knappschaft-Bahn-See (KBS) takes the principle that a benefit should only be decided from a clarified account especially seriously: in refund cases where the account has never been clarified before, KBS requires a Kontenklärung before the decision in almost every case, while other carriers request one selectively. Whether KBS handles your claim follows from your insurance history — insurance numbers beginning with 38, 39 or 80–89 are issued only by KBS. Our routing guide explains which office decides your claim, and why. → Which German pension office handles your claim',
      sp: [
        {
          k: 'a',
          x: '→ Which German pension office handles your claim',
          href: '/post/which-german-pension-office-handles-your-claim',
        },
      ],
    },
    {
      t: 'p',
      x: 'The legal frame, briefly: the insurance account is what the office decides from, and the law expects you to help settle it — insured persons are obliged to cooperate in clarifying the account: to check the record for accuracy and completeness, state the relevant facts and provide the necessary documents (§ 149 Abs. 4 SGB VI). Once the account has been clarified — or once you have not objected to a sent record within six months — the data lying more than six calendar years back are bindingly determined by notice (Feststellungsbescheid); how your periods are counted and valued is then decided when a benefit is determined (§ 149 Abs. 5 SGB VI).',
      sp: [],
    },
    {
      t: 'h2',
      x: '"But most of that time I wasn\'t even in Germany"',
      id: 'but-most-of-that-time-i-wasnt',
    },
    {
      t: 'p',
      x: "In our managed cases, that is the most common reaction to a V0100: the office asks about years that had nothing to do with Germany — often the whole stretch before you arrived and everything since you left — and the form feels like it was sent to the wrong person. It wasn't. The office is asking on purpose.",
      sp: [],
    },
    {
      t: 'p',
      x: "A Kontenklärung reviews the record across a defined span, typically everything from your 17th birthday to today — the 17th birthday because that is the earliest point from which school and study time can count in a German pension record (§ 58 SGB VI). From the office's side, an unexplained stretch inside that span is simply a gap: it cannot tell whether those years hide an unreported German job, a foreign insurance period that matters for a cross-border question, or time with no German pension relevance at all. It can only mark the time as settled once you have said what it was. That is why the request usually reaches from before your first German record entry to the present day — precisely the years that feel least relevant from where you sit.",
      sp: [],
    },
    {
      t: 'p',
      x: "The practical rule that follows: account for the whole requested span, without gaps. Answer it like a timeline — education until year X, employment abroad from X to Y, moved to Germany in Y — so that every year is assigned to something. A year you explain is closed; a year you leave blank is a question the office still has to ask by letter. A gap can legitimately remain in the record — DRV's own guidance says a gap is not automatically an error — but only once the office knows what the time was.",
      sp: [
        {
          k: 'b',
          x: 'account for the whole requested span, without gaps.',
        },
      ],
    },
    {
      t: 'p',
      x: 'And to connect this with the point below: listing your foreign years does not turn them into German contribution months. It is simply how the office classifies the time and moves your claim along.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'What a Kontenklärung actually is',
      id: 'what-a-kontenklärung-actually-is',
    },
    {
      t: 'p',
      x: "Your Versicherungsverlauf is the pension system's record of your insured life in Germany: contribution months from employment, credited periods such as unemployment-benefit months or maternity protection, and — visible as gaps — everything it does not know about yet. A Kontenklärung is the procedure that reviews and completes this record.",
      sp: [],
    },
    {
      t: 'p',
      x: "DRV names the typical gaps itself: school and study periods from age 17, vocational training, periods abroad, child-raising. The typical evidence is unspectacular — employment contracts, school and training certificates, children's birth certificates.",
      sp: [],
    },
    {
      t: 'p',
      x: "Foreign periods belong in the picture. V0100 also asks about periods in foreign insurance systems. Where European coordination rules or a social-security agreement applies, DRV can obtain information from the relevant foreign institution — and EU and UK insurance records are digitally connected to Germany's, so gaps in the story surface. You must nevertheless disclose those periods yourself and provide any insurance numbers and records you have. Two things foreign periods can and cannot do: they can affect whether a pension qualifying period is met — which matters for some refund situations — but they are not added to the 60 German contribution months that the country-specific limit for citizens of the USA, India and certain other countries counts. Only German months count there. → Refund Guide",
      sp: [
        {
          k: 'a',
          x: '→ Refund Guide',
          href: '/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'b',
          x: 'Foreign periods belong in the picture.',
        },
      ],
    },
    {
      t: 'p',
      x: 'For a refund claim, the account matters twice: the five-year qualifying period and the 60-month count are both read from it. Only the official record is reliable — remembered date spans are estimates until the account says otherwise.',
      sp: [],
    },
    {
      t: 'h2',
      x: "V0100's sections, explained in English",
      id: 'v0100s-sections-explained-in-english',
    },
    {
      t: 'p',
      x: 'The paper form (Version 21, Stand 02.03.2026) walks through the same ground as the online version. In order:',
      sp: [],
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Personal details — names including former names, date of birth, contact address, and your last residence in Germany.',
          sp: [
            {
              k: 'b',
              x: 'Personal details',
            },
          ],
        },
        {
          x: 'Representative — only if someone files for you (with authority documentation).',
          sp: [
            {
              k: 'b',
              x: 'Representative',
            },
          ],
        },
        {
          x: 'Missing German employment and contribution periods — employers, places, dates, as precisely as you can document them.',
          sp: [
            {
              k: 'b',
              x: 'Missing German employment and contribution periods',
            },
          ],
        },
        {
          x: 'Foreign residence and insurance periods — countries, foreign insurance numbers, local carriers.',
          sp: [
            {
              k: 'b',
              x: 'Foreign residence and insurance periods',
            },
          ],
        },
        {
          x: 'Missing periods of sickness, unemployment and education — including school and study from age 17.',
          sp: [
            {
              k: 'b',
              x: 'Missing periods of sickness, unemployment and education',
            },
          ],
        },
        {
          x: 'Children — births and raising periods; this is where a V0800 requirement can follow. → V0800 child-raising-periods guide',
          sp: [
            {
              k: 'a',
              x: '→ V0800 child-raising-periods guide',
              href: '/v0800-child-raising-periods',
            },
            {
              k: 'b',
              x: 'Children',
            },
          ],
        },
        {
          x: 'Vocational training, civil-service provision and existing pensions — special coverage that affects how periods are treated.',
          sp: [
            {
              k: 'b',
              x: 'Vocational training, civil-service provision and existing pensions',
            },
          ],
        },
        {
          x: 'Accessible-document preferences — how DRV should send you documents.',
          sp: [
            {
              k: 'b',
              x: 'Accessible-document preferences',
            },
          ],
        },
        {
          x: 'Declaration and signature.',
          sp: [
            {
              k: 'b',
              x: 'Declaration and signature.',
            },
          ],
        },
        {
          x: 'Attachments — the evidence you enclose.',
          sp: [
            {
              k: 'b',
              x: 'Attachments',
            },
          ],
        },
        {
          x: 'Confirmation of personal-status information — where required for your case.',
          sp: [
            {
              k: 'b',
              x: 'Confirmation of personal-status information',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'Answer what applies and mark the rest as not applicable rather than leaving it blank — an unanswered question reads as an open one.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Completing V0100 — online or on paper',
      id: 'completing-v0100-online-or-on-paper',
    },
    {
      t: 'p',
      x: "Online (recommended by DRV): the Kontenklärung is available as a guided online application in DRV's eAntrag service. You can start with just your German insurance number (Versicherungsnummer); the form guides you through the questions with built-in help, lets you upload your evidence as files, can be saved for 30 days, and confirms transmission immediately. If a DRV letter has sent you an access code, DRV says that code also enables a legally secure transaction without a German eID or signature card — worth checking the letter that asked for the clarification. Lost your insurance number? → German social security number",
      sp: [
        {
          k: 'a',
          x: '→ German social security number',
          href: '/post/german-social-security-number',
        },
        {
          k: 'b',
          x: 'Online (recommended by DRV):',
        },
      ],
    },
    {
      t: 'p',
      x: "On paper: download the PDF (Version 21, Stand 02.03.2026) from the official DRV form page, answer the questions, attach copies of your evidence, sign, and send it back to the office that wrote to you — replying to the requesting office keeps everything in one file. DRV's own explanations to the form are in V0110.",
      sp: [
        {
          k: 'b',
          x: 'On paper:',
        },
      ],
    },
    {
      t: 'p',
      x: "Answer completely, in one round — and document each period. The practice that keeps a Kontenklärung short, from our managed cases: attach a document for every period you state — for a study period, a copy of the graduation certificate that covers it; for employment abroad, an employment reference or work record. Where a document no longer exists, provide the most accurate information you can and say explicitly that the document is no longer available — a stated period with a missing-document note is something the office can work with, and DRV's V0110 guidance names alternative evidence such as employer or health-insurance certificates, payslips, employment certificates and witness statements. Every open point the office has to ask about separately is another exchange of letters with a German authority.",
      sp: [
        {
          k: 'b',
          x: 'Answer completely, in one round — and document each period.',
        },
      ],
    },
    {
      t: 'h2',
      x: 'What it means for your refund claim',
      id: 'what-it-means-for-your-refund-claim',
    },
    {
      t: 'p',
      x: "A Kontenklärung adds correspondence, not a verdict: the refund is decided after the record is settled. Three things keep the exchange short — reply within the timeframe the office's letter names (or tell the office you need time to gather documents), answer every question rather than a selection, and attach evidence instead of descriptions where you have it.",
      sp: [],
    },
    {
      t: 'p',
      x: 'Ignoring the request is the one genuinely bad option: it delays the claim, and if the office has warned you in writing about the consequences and set you a reasonable deadline, it may refuse the benefit until the required cooperation is provided (§ 66 SGB I).',
      sp: [],
    },
    {
      t: 'p',
      x: 'Do you have to clarify your account before applying? Not necessarily. Gaps can be reported in the refund application itself, and the office requests what it needs. A Kontenklärung ahead of the application is worth considering when the account is substantially unclear — many periods missing, foreign years unrecorded — so the refund application does not stall on open questions.',
      sp: [
        {
          k: 'b',
          x: 'Do you have to clarify your account before applying?',
        },
      ],
    },
    {
      t: 'p',
      x: "In a managed claim, this is part of what is handled for you: we obtain and review the relevant DRV account information during the managed process where required. The pension office writes by ordinary post, in German — in a managed claim its letters arrive at a German address, reach you as scans, and come with an explanation in plain English; should a letter still reach you directly, you forward it and we take it from there. And silence from the pension office doesn't mean silence from us: you get a status update at least every four weeks. → V0901 form guide (English)",
      sp: [
        {
          k: 'a',
          x: '→ V0901 form guide (English)',
          href: '/v0901-pension-refund-form-english',
        },
        {
          k: 'b',
          x: 'In a managed claim,',
        },
      ],
    },
    {
      t: 'h2',
      x: '"I received a Feststellungsbescheid — where is my refund?"',
      id: 'i-received-a-feststellungsbescheid-where-is-my',
    },
    {
      t: 'p',
      x: "The letter that ends a Kontenklärung is a common source of alarm in our managed cases. You answered the office's questions and expected the refund decision (Erstattungsbescheid). What arrives instead is a Feststellungsbescheid — a formal determination notice that closes a procedure, reads final, and says nothing about money. It can look as if the process is over and the refund went nowhere.",
      sp: [],
    },
    {
      t: 'p',
      x: 'Nothing has gone wrong. The two notices do different jobs. The Feststellungsbescheid ends the account clarification: it bindingly determines the periods in your record (§ 149 Abs. 5 SGB VI). The refund itself is decided in a separate notice that follows, once the office decides your claim from the now-settled account. The clarification was an inserted step in your refund procedure — with it completed, the refund claim continues where it left off.',
      sp: [],
    },
    {
      t: 'p',
      x: 'One thing is worth doing before you file the letter away: check the determined periods against what you reported. The determination is binding for what it covers, and the notice itself explains how — and by when — you can object if something in it is wrong.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Common mistakes with a V0100 request',
      id: 'common-mistakes-with-a-v0100-request',
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Letting it sit. The refund claim waits while the record is open — and prolonged non-cooperation can end in a refusal after a written warning and deadline (§ 66 SGB I). If gathering documents takes time, tell the office.',
          sp: [
            {
              k: 'b',
              x: 'Letting it sit.',
            },
          ],
        },
        {
          x: 'Skipping the "irrelevant" years. The span before Germany and after Germany is asked about on purpose — account for all of it, like a timeline, so no year is left as an open question.',
          sp: [
            {
              k: 'b',
              x: 'Skipping the "irrelevant" years.',
            },
          ],
        },
        {
          x: 'Answering from memory. Contracts, certificates and records beat recollection. Where papers are gone, give the most accurate account you can, say so, and offer the alternative evidence V0110 describes.',
          sp: [
            {
              k: 'b',
              x: 'Answering from memory.',
            },
          ],
        },
        {
          x: "Leaving foreign periods out. You are obliged to disclose them, EU and UK insurance records are digitally connected to Germany's so gaps in the story surface — and foreign periods can change qualifying-period questions even though they never count toward the 60 German months.",
          sp: [
            {
              k: 'b',
              x: 'Leaving foreign periods out.',
            },
          ],
        },
      ],
    },
    {
      t: 'faq',
    },
    {
      t: 'h2',
      x: 'Official downloads and further guides',
      id: 'official-downloads-and-further-guides',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Kontenklärung online (eAntrag) — recommended by DRV: official eAntrag page',
          sp: [
            {
              k: 'a',
              x: 'official eAntrag page',
              href: 'eantrag:',
            },
            {
              k: 'b',
              x: 'Kontenklärung online (eAntrag)',
            },
          ],
        },
        {
          x: 'V0100 — Antrag auf Kontenklärung (PDF; Version 21, Stand 02.03.2026): → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0100',
            },
            {
              k: 'b',
              x: 'V0100 — Antrag auf Kontenklärung',
            },
          ],
        },
        {
          x: 'V0110 — Erläuterungen zum Antrag auf Kontenklärung (Version 24, Stand 02.03.2026): → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0110',
            },
            {
              k: 'b',
              x: 'V0110 — Erläuterungen zum Antrag auf Kontenklärung',
            },
          ],
        },
        {
          x: 'V0800 — child-raising periods — the determination the office often asks for alongside a Kontenklärung: → V0800 child-raising-periods guide',
          sp: [
            {
              k: 'a',
              x: '→ V0800 child-raising-periods guide',
              href: '/v0800-child-raising-periods',
            },
            {
              k: 'b',
              x: 'V0800 — child-raising periods',
            },
          ],
        },
        {
          x: 'All refund forms, explained: → Downloads — official DRV forms',
          sp: [
            {
              k: 'a',
              x: '→ Downloads — official DRV forms',
              href: '/download',
            },
            {
              k: 'b',
              x: 'All refund forms, explained:',
            },
          ],
        },
        {
          x: 'The refund application itself, section by section: → V0901 form guide (English)',
          sp: [
            {
              k: 'a',
              x: '→ V0901 form guide (English)',
              href: '/v0901-pension-refund-form-english',
            },
            {
              k: 'b',
              x: 'The refund application itself, section by section:',
            },
          ],
        },
      ],
    },
    {
      t: 'src',
      x: 'Sources: DRV form V0100 (Version 21, Stand 02.03.2026) with explanations V0110 (Version 24, Stand 02.03.2026) and the official Kontenklärung eAntrag · DRV announcement on the online Kontenklärung (6 July 2026) · DRV brochure „Kontenklärung: Fragen und Antworten" · §§ 58, 149 Abs. 4, 149 Abs. 5 SGB VI · § 66 SGB I · our routing guide and forms registry.',
      sp: [
        {
          k: 'b',
          x: 'Sources:',
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Why does the office ask about periods outside Germany?',
      a: 'Because a gap only closes when the office knows what the time was. Foreign years are never added to your German contribution months — but until you declare them, the office cannot tell them apart from unreported German periods. Account for the whole requested span, typically from your 17th birthday to today, and the record can be settled in one round.',
      inSchema: true,
    },
    {
      q: 'Do I have to clarify my account before applying for the refund?',
      a: 'Not necessarily upfront. Gaps can be reported in the refund application itself, and the office requests what it needs. If your account is substantially unclear, a Kontenklärung first can spare the refund application from stalling on open questions.',
      inSchema: true,
    },
    {
      q: 'Can I do the Kontenklärung online from abroad?',
      a: "Yes. The online application in DRV's eAntrag starts with your insurance number, guides you through the questions, accepts uploaded evidence and confirms transmission immediately. If a DRV letter has provided you an access code, a legally secure submission is possible without a German eID or signature card. The paper PDF remains an alternative.",
      inSchema: true,
    },
    {
      q: 'Does a Kontenklärung request delay my refund?',
      a: 'It means the office settles the record before deciding — the claim is not rejected, it is waiting for facts. A complete, evidenced reply in one round keeps the exchange as short as it can be; individual processing depends on what is open in your account.',
      inSchema: true,
    },
    {
      q: 'What is a Feststellungsbescheid?',
      a: 'The notice by which the office bindingly determines the data in your account that lie more than six calendar years back, once the account is clarified or you have not objected to a sent record within six months (§ 149 Abs. 5 SGB VI). How the periods count toward a benefit is decided when the benefit itself — for example a refund — is determined. It is not the refund decision: the Erstattungsbescheid is a separate notice that follows once the office decides your claim from the settled account.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'The notice by which the office bindingly determines the data in your account that lie more than six calendar years back, once the account is clarified or you have not objected to a sent record within six months (§ 149 Abs. 5 SGB VI). How the periods count toward a benefit is decided when the benefit itself — for example a refund — is determined. It is not the refund decision: the Erstattungsbescheid is a separate notice that follows once the office decides your claim from the settled account — see the chapter above.',
          sp: [],
        },
      ],
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source: 'GPR_FormsPage_V0100_EN_v1.3_2026-09-04.md (live slug /v0100-form)',
};

export default page;
