// Generated by scripts/build-guides.mjs from GPR_FormsPage_V0800_EN_v1.2_2026-09-04.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/v0800-child-raising-periods',
  kind: 'guide',
  lang: 'en',
  title: 'V0800 Form in English: Child-Raising Pension Periods (2026)',
  meta: 'The pension office sent you form V0800? What Kindererziehungszeiten are, who gets the months, and how they can affect a German pension refund.',
  h1: 'Form V0800: Child-Raising Periods (Kindererziehungszeiten) — and What They Mean for Your German Pension Refund',
  headline: 'V0800 Form in English: Child-Raising Pension Periods',
  eyebrow: 'Form guide · V0800',
  rail: 'Form guide',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'Forms & guides',
      href: '/download',
    },
    {
      label: 'V0800',
    },
  ],
  reviewLine: 'Last checked: 3 September 2026',
  showReviewer: true,
  datePublished: '2026-09-09',
  dateModified: '2026-09-10',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: 'The short answer: Form V0800 („Antrag auf Feststellung von Kindererziehungszeiten /Berücksichtigungszeiten wegen Kindererziehung") is the official Deutsche Rentenversicherung (DRV) application for having child-raising periods determined in a German pension record. Many of our readers meet it the same way: it arrives from the pension office in the middle of a refund claim, usually because something in the record points to a child. The form is free — as a guided online application (recommended by DRV) or as a PDF (Version 24, Stand 29.04.2026), with DRV\'s own explanatory guides V0810 and V0811. What the determination changes for a refund cuts in more than one direction, and this guide explains all of them.',
      sp: [
        {
          k: 'b',
          x: 'The short answer:',
        },
      ],
    },
    {
      t: 'p',
      x: "Official and free: V0800 — official DRV form page · V0800 online — DRV eAntrag · V0810 — DRV's explanations to the application · V0811 — DRV's explanations to the supplementary child-raising questionnaire",
      sp: [
        {
          k: 'a',
          x: 'V0800 — official DRV form page',
          href: 'drv:V0800',
        },
        {
          k: 'a',
          x: 'V0800 online — DRV eAntrag',
          href: 'eantrag:',
        },
        {
          k: 'a',
          x: "V0810 — DRV's explanations to the application",
          href: 'drv:V0810',
        },
        {
          k: 'a',
          x: "V0811 — DRV's explanations to the supplementary child-raising questionnaire",
          href: 'drv:V0811',
        },
        {
          k: 'b',
          x: 'Official and free:',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a private service operated by ATLAES GmbH, Berlin. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
    {
      t: 'h2',
      x: '"The office sent me V0800 during my refund claim — is something wrong?"',
      id: 'the-office-sent-me-v0800-during-my',
    },
    {
      t: 'p',
      x: 'No — your record is being settled before the decision. In our experience it usually starts with a maternity entry: when the pension office finds maternity protection (Mutterschutz/Mutterschaftsurlaub) in an insurance record, it typically has the applicant apply for the determination of the child-raising periods before it decides the refund. The office may want this settled, and the law expects you to help: insured persons are obliged to cooperate in clarifying their account — checking the record, stating the relevant facts and providing the necessary documents (§ 149 Abs. 4 SGB VI); more generally, anyone applying for a benefit must state all facts relevant to it (§ 60 SGB I). So the way through is to answer the form completely and truthfully — and to understand what the determination changes. That second part is what the rest of this guide is for.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Mutterschutz, Elternzeit, Kindererziehungszeiten — three different things',
      id: 'mutterschutz-elternzeit-kindererziehungszeiten-three-different-things',
    },
    {
      t: 'p',
      x: "German letters mix three terms that look interchangeable and aren't. Untangling them explains both the entry in your record and the office's request.",
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: "Mutterschutz (maternity protection): the protected weeks around the birth in which an employee did not work, under the Maternity Protection Act. In the pension record, these weeks can appear as a credited period (Anrechnungszeit, § 58 Abs. 1 Nr. 2 SGB VI) where the statutory conditions are met — which is not the same thing as a child-raising contribution period. In the cases we see, this is usually the entry that prompts the office's V0800 request: it signals a birth, so the office checks whether child-raising periods belong in the account.",
          sp: [
            {
              k: 'b',
              x: 'Mutterschutz (maternity protection):',
            },
          ],
        },
        {
          x: 'Elternzeit (parental leave): an employment-law leave status between you and your employer (BEEG). It is not itself a pension-record category — what the pension system credits for raising a child are the two categories below.',
          sp: [
            {
              k: 'b',
              x: 'Elternzeit (parental leave):',
            },
          ],
        },
        {
          x: 'Kindererziehungszeiten (child-raising periods): genuine contribution periods for raising a child in its first years — and months of mandatory insurance (§ 3 SGB VI). You do not pay these contributions; the federal government does (§ 177 Abs. 1 SGB VI). Per child born 1992 or later: 36 calendar months, beginning after the month of birth (§ 56 SGB VI). Per child born before 1992: currently 30 calendar months (§ 249 SGB VI) — and note the enacted change: from 1 January 2027, the „Mütterrente III" reform extends periods for children born before 1992 by up to six months, toward the same 36. DRV applies it automatically; the technical implementation in accounts and payments runs during 2028.',
          sp: [
            {
              k: 'b',
              x: 'Kindererziehungszeiten (child-raising periods):',
            },
          ],
        },
        {
          x: 'Berücksichtigungszeiten (consideration periods): the time raising a child up to its 10th birthday (§ 57 SGB VI). They play a role for some pension purposes, but they do not count toward the five-year qualifying period, and they are not contribution months.',
          sp: [
            {
              k: 'b',
              x: 'Berücksichtigungszeiten (consideration periods):',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Whose months are they?',
      id: 'whose-months-are-they',
    },
    {
      t: 'p',
      x: 'The child-raising period is attributed to the parent who raised the child (§ 56 SGB VI). For parents who raised a child together, the law has a fixed sequence. They can determine, by a joint declaration, which of them the period is attributed to — and the declaration can split it, covering the whole period or only part of it (§ 56 Abs. 2 SGB VI). The declaration is genuinely joint: both parents sign it (DRV provides form V0820 for exactly this, and V0800 asks whether such a declaration exists) — so where it applies, the other parent has to be involved. It works for future months and reaches back at most two calendar months. For raising periods that lie years in the past, the facts therefore decide, not a new agreement: without a valid declaration the months go to the parent who predominantly raised the child; if neither predominantly did, to the mother; and where attribution is still impossible, the months alternate between the parents calendar month by calendar month.',
      sp: [],
    },
    {
      t: 'p',
      x: "Attribution decides whose German record carries the months — and with it, whose qualifying-period and month-count questions they touch, including the 60-month line for agreement-country citizens, which is counted per person. That is a consequence to understand, not something to construct after the fact: for past periods, attribution follows the facts and the sequence above, and every answer on the form must reflect how the raising actually happened. This cuts both ways — if the other parent genuinely was the predominant carer, saying so is not optimization, it is the correct answer. For months still ahead, jointly raising parents make the designation prospectively; it affects both parents' records, so it is a decision worth both of you understanding before signing.",
      sp: [],
    },
    {
      t: 'p',
      x: "Where the raising happened matters too. Raising in Germany — the parent habitually living there with the child — normally satisfies the condition. Periods abroad can also qualify in several situations: when the raising parent has German mandatory contribution periods for work performed abroad during the raising or immediately before the birth (typically posted workers), and in certain cases through the accompanying spouse or registered partner with such periods — even where the spouse lacks them only because of exemption from German insurance (§ 56 Abs. 3 SGB VI). In EU/EEA/Swiss/UK constellations, coordination-law rules can add further routes. DRV's own guide V0810 describes the possibilities — so periods abroad should not automatically be treated as excluded. Separately, parents who acquired equivalent old-age coverage in certain other systems can be excluded (§ 56 Abs. 4 SGB VI).",
      sp: [],
    },
    {
      t: 'p',
      x: 'The V0800 asks exactly these questions — birth, raising timeline, who raised, where — which is why the answers decide more than a formality.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'What the determination changes for a refund — honestly, in every direction',
      id: 'what-the-determination-changes-for-a-refund',
    },
    {
      t: 'p',
      x: "1. The months count. Child-raising periods are contribution months. They count toward the five-year qualifying period for a German pension — and toward the 60-month line that applies to citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay, and to Japanese citizens (as well as refugees and stateless persons) living in Japan. For those citizens, a refund before retirement age requires fewer than 60 German contribution months. With up to 36 months per child, a determination can move an account across that line — and from 2027, up to six additional months per child born before 1992 count as well. Crossing 60 closes the refund-before- retirement-age route; the contributions then secure a German pension at retirement age instead — paid worldwide, with a possible survivor's pension for a spouse later. That is a different outcome, not lost money; whether it is the better one depends on your situation. If the 60-month line is close in your case, understand this chapter before anything is filed — the counting rules are in our full guide. → Refund Guide",
      sp: [
        {
          k: 'a',
          x: '→ Refund Guide',
          href: '/post/how-to-get-a-german-pension-refund',
        },
        {
          k: 'b',
          x: '1. The months count.',
        },
      ],
    },
    {
      t: 'p',
      x: '2. A recent child-raising period can move your earliest application date. Child-raising periods are periods of mandatory insurance (§ 3 SGB VI), and a refund before retirement age requires that 24 calendar months have passed since mandatory insurance ended, without new mandatory insurance beginning (§ 210 Abs. 2 SGB VI). The clock runs from the end of the most recent mandatory-insurance period — which can be the end of a child-raising period, not the end of your last job. In plain terms: if a determined child-raising period ended less than two years ago, the earliest possible application date moves accordingly, and an application filed too early is rejected. For children raised in Germany years before you left, this changes nothing. Retirement-age and survivor applications carry no such waiting period.',
      sp: [
        {
          k: 'b',
          x: '2. A recent child-raising period can move your earliest application date.',
        },
      ],
    },
    {
      t: 'p',
      x: '3. The months add no refund cash. A refund pays back your own employee-share contributions. The contributions for child-raising periods were paid by the federal government, not by you — so the determined months count for every month-count, but they never increase the refund amount.',
      sp: [
        {
          k: 'b',
          x: '3. The months add no refund cash.',
        },
      ],
    },
    {
      t: 'p',
      x: '4. A month is never counted twice — and working never cancels the period. If you worked and raised a child in the same calendar month, that month counts once — employment and child-raising in parallel do not stack. The reverse holds too: returning to work does not end the child-raising period (see the FAQ).',
      sp: [
        {
          k: 'b',
          x: '4. A month is never counted twice — and working never cancels the period.',
        },
      ],
    },
    {
      t: 'p',
      x: "5. At retirement age, the qualifying period decides the route. Whoever reaches German retirement age with the five-year qualifying period met — child-raising months included — has a pension entitlement; for the citizenship groups whose refund route was limited before retirement age, the pension then takes the refund's place. How retirement-age cases work is covered in our full guide.",
      sp: [
        {
          k: 'b',
          x: '5. At retirement age, the qualifying period decides the route.',
        },
      ],
    },
    {
      t: 'p',
      x: 'And the form is not optional once the office requires it. Refund applications must be complete and truthful — consequences are something to understand, never something to manage by leaving children or periods out. For citizens of countries without the 60-month rule, the month-count itself carries no cap; the effects that can still matter are the application-date rule in point 2 and the qualifying-period picture — and the payout amount never changes either way.',
      sp: [
        {
          k: 'b',
          x: 'And the form is not optional once the office requires it.',
        },
      ],
    },
    {
      t: 'p',
      x: "In a managed claim, this is part of what is handled for you: we obtain and review the relevant DRV account information during the managed process where required. The pension office writes by ordinary post, in German — in a managed claim its letters arrive at a German address, reach you as scans, and come with an explanation in plain English; should a letter still reach you directly, you forward it and we take it from there. And silence from the pension office doesn't mean silence from us: you get a status update at least every four weeks. → V0901 form guide (English)",
      sp: [
        {
          k: 'a',
          x: '→ V0901 form guide (English)',
          href: '/v0901-pension-refund-form-english',
        },
        {
          k: 'b',
          x: 'In a managed claim,',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Completing V0800',
      id: 'completing-v0800',
    },
    {
      t: 'p',
      x: "Online (recommended by DRV): V0800 is available as a guided online application in DRV's eAntrag — guided questions, file upload for evidence, immediate confirmation of receipt.",
      sp: [
        {
          k: 'b',
          x: 'Online (recommended by DRV):',
        },
      ],
    },
    {
      t: 'p',
      x: "On paper: download the PDF (Version 24, Stand 29.04.2026) from the official DRV form page. DRV's own explanations come with it: V0810 for the application, V0811 for the supplementary child-raising questionnaire.",
      sp: [
        {
          k: 'b',
          x: 'On paper:',
        },
      ],
    },
    {
      t: 'p',
      x: "What the form asks, in short: the children and their births; who raised each child, when and in which country; your and — where relevant — the other parent's insurance situation during the raising; and whether a joint attribution declaration exists. Depending on your answers, two companion forms can come into play: V0805, the supplementary child-raising questionnaire the form itself calls for in certain raising situations, and V0820, the parents' joint declaration on attribution (both parents sign; also available in eAntrag). Have ready evidence of the parent-child relationship — a birth certificate is the most common document, but DRV accepts alternatives (see V0810) — plus your raising timeline. The completed form goes back to the office handling your claim, so everything stays in one file.",
      sp: [
        {
          k: 'b',
          x: 'What the form asks, in short:',
        },
        {
          k: 'b',
          x: 'V0805',
        },
        {
          k: 'b',
          x: 'V0820',
        },
      ],
    },
    {
      t: 'faq',
    },
    {
      t: 'h2',
      x: 'Official downloads and further guides',
      id: 'official-downloads-and-further-guides',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'V0800 — Antrag auf Feststellung von Kindererziehungszeiten / Berücksichtigungszeiten wegen Kindererziehung (PDF; Version 24, Stand 29.04.2026): → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0800',
            },
            {
              k: 'b',
              x: 'V0800 — Antrag auf Feststellung von Kindererziehungszeiten / Berücksichtigungszeiten wegen Kindererziehung',
            },
          ],
        },
        {
          x: 'V0800 online (eAntrag) — recommended by DRV: official eAntrag page',
          sp: [
            {
              k: 'a',
              x: 'official eAntrag page',
              href: 'eantrag:',
            },
            {
              k: 'b',
              x: 'V0800 online (eAntrag)',
            },
          ],
        },
        {
          x: "V0810 / V0811 — DRV's official explanations (Stand 29.04.2026 / 26.06.2019): → Official DRV form pages",
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form pages',
              href: 'drv:V0810',
            },
            {
              k: 'b',
              x: "V0810 / V0811 — DRV's official explanations",
            },
          ],
        },
        {
          x: 'V0805 — Zusatzfragebogen zur Kindererziehung (Version 10, Stand 24.06.2020): → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0805',
            },
            {
              k: 'b',
              x: 'V0805 — Zusatzfragebogen zur Kindererziehung',
            },
          ],
        },
        {
          x: 'V0820 — joint declaration on attribution (Version 8, Stand 27.06.2023; also in eAntrag): → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0820',
            },
            {
              k: 'b',
              x: 'V0820 — joint declaration on attribution',
            },
          ],
        },
        {
          x: 'V0100 — account clarification, the request that often travels with this one: → V0100 account-clarification guide',
          sp: [
            {
              k: 'a',
              x: '→ V0100 account-clarification guide',
              href: '/v0100-form',
            },
            {
              k: 'b',
              x: 'V0100 — account clarification',
            },
          ],
        },
        {
          x: 'All refund forms, explained: → Downloads — official DRV forms',
          sp: [
            {
              k: 'a',
              x: '→ Downloads — official DRV forms',
              href: '/download',
            },
            {
              k: 'b',
              x: 'All refund forms, explained:',
            },
          ],
        },
        {
          x: 'The refund application itself, section by section: → V0901 form guide (English)',
          sp: [
            {
              k: 'a',
              x: '→ V0901 form guide (English)',
              href: '/v0901-pension-refund-form-english',
            },
            {
              k: 'b',
              x: 'The refund application itself, section by section:',
            },
          ],
        },
      ],
    },
    {
      t: 'src',
      x: "Sources: DRV form V0800 (Version 24, Stand 29.04.2026) with official explanations V0810 and V0811, supplementary forms V0805 and V0820 · DRV's Mütterrente-III information · §§ 3, 54, 56, 57, 58, 149, 177, 210, 249 SGB VI · § 60 and § 66 SGB I · our forms registry and refund guides.",
      sp: [
        {
          k: 'b',
          x: 'Sources:',
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Do I have to fill in V0800 if the office sends it?',
      a: 'Yes — answer it completely and truthfully. Insured persons are obliged to cooperate in clarifying their account (§ 149 Abs. 4 SGB VI), applicants must state all facts relevant to a benefit (§ 60 SGB I), and the office decides the refund once the record is settled. Leaving children or periods out is not an option; what you can and should do is understand the consequences. And the determination notice (Feststellungsbescheid) you receive afterwards is not the refund decision: the refund is decided separately, from the settled record.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'Yes — answer it completely and truthfully. Insured persons are obliged to cooperate in clarifying their account (§ 149 Abs. 4 SGB VI), applicants must state all facts relevant to a benefit (§ 60 SGB I), and the office decides the refund once the record is settled. Leaving children or periods out is not an option; what you can and should do is understand the consequences — see the chapter above. And the determination notice (Feststellungsbescheid) you receive afterwards is not the refund decision: the refund is decided separately, from the settled record.',
          sp: [],
        },
      ],
    },
    {
      q: 'Can child-raising months block my refund?',
      a: 'They never reduce the refund amount — but they can affect whether and when the before-retirement-age route is open. For citizens of the 60-month countries, determined months can push the account to 60 or more, which closes that route; what remains is a German pension at retirement age, paid worldwide. And for anyone applying before retirement age, a child-raising period that ended less than 24 months ago moves the earliest application date (§ 210 Abs. 2 SGB VI). For every other constellation the months only help the qualifying-period picture.',
      inSchema: true,
    },
    {
      q: 'My child was born after I left Germany — does V0800 concern me?',
      a: "Child-raising periods require raising in Germany or an equal-status raising abroad — mainly German contribution periods for work abroad during the raising or immediately before the birth, in some cases through an accompanying spouse or registered partner, and in EU/EEA/Swiss/UK cases via coordination rules (§ 56 Abs. 3 SGB VI; details in DRV's V0810). For many people who left Germany for good before the birth, no German child-raising periods arise — but answer the office's questions as they are; the determination itself sorts out what counts.",
      inSchema: true,
    },
    {
      q: 'I went back to work shortly after Mutterschutz — do child-raising periods still concern me?',
      a: "Yes — this is one of the most common misunderstandings we hear. In pension law, working and raising a child are not mutually exclusive: the child-raising period runs for the raising parent whether or not they returned to work. Normal employment does not exclude it — the exclusions in § 56 SGB VI concern parents covered by certain other old-age systems, not working parents. A calendar month with both employment and child-raising counts once toward the month-count, not twice; but the period still belongs in your record, so the office's questions about children apply to you even if you worked throughout.",
      inSchema: true,
    },
    {
      q: 'Do the determined months increase my refund amount?',
      a: 'No. The refund pays back your own employee-share contributions; the contributions for child-raising periods were paid by the federal government. The months count toward the qualifying period and the 60-month line — the payout does not change.',
      inSchema: true,
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source: 'GPR_FormsPage_V0800_EN_v1.2_2026-09-04.md',
};

export default page;
