// Generated by scripts/build-guides.mjs from GPR_FormsPage_V0900_DE_v1.1_2026-09-03.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/v0900-formular',
  kind: 'guide',
  lang: 'de',
  title: 'V0900: Beitragserstattung im Inland — Anleitung (2026)',
  meta: 'V0900 erklärt: Wer die Beitragserstattung im Inland bekommt — Beamte, Regelaltersgrenze, Hinterbliebene —, wie der Online-Antrag läuft, welche Fehler Sie vermeiden.',
  h1: 'Formular V0900: Beitragserstattung bei Aufenthalt im Inland — so funktioniert der Antrag',
  headline: 'V0900: Beitragserstattung im Inland — Anleitung',
  eyebrow: 'Formular-Anleitung · V0900',
  rail: 'Anleitung',
  crumbs: [
    {
      label: 'Startseite',
      href: '/',
    },
    {
      label: 'Formulare',
      href: '/download',
    },
    {
      label: 'V0900',
    },
  ],
  reviewLine: 'Zuletzt geprüft: 3. September 2026',
  showReviewer: true,
  datePublished: '2026-09-03',
  dateModified: '2026-09-03',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: 'Kurz erklärt: Mit dem Formular V0900 („Antrag auf Beitragserstattung bei Aufenthalt im Inland") beantragen Sie die Erstattung von Rentenbeiträgen bei der Deutschen Rentenversicherung (DRV), wenn Sie in Deutschland leben. Das Formular deckt drei Gruppen ab: dauerhaft versicherungsfreie oder von der Versicherungspflicht befreite Personen — typischerweise Beamtinnen und Beamte und Richterinnen und Richter auf Lebenszeit sowie Berufssoldatinnen und Berufssoldaten —, Personen, die die Regelaltersgrenze erreicht haben, ohne die allgemeine Wartezeit von fünf Jahren zu erfüllen, und Hinterbliebene, wenn wegen dieser Wartezeit kein Anspruch auf eine Rente wegen Todes besteht. Der Antrag ist kostenlos — als Online-Antrag der DRV (empfohlen, etwa 20 Minuten) oder als PDF.',
      sp: [
        {
          k: 'b',
          x: 'Kurz erklärt:',
        },
      ],
    },
    {
      t: 'p',
      x: 'Offiziell und kostenlos: Online-Antrag (eAntrag) der DRV · V0900 als PDF — Version 26, Stand 02.03.2026 · V0910 — die offiziellen Erläuterungen der DRV zum Ausfüllen',
      sp: [
        {
          k: 'a',
          x: 'Online-Antrag (eAntrag) der DRV',
          href: 'eantrag:',
        },
        {
          k: 'a',
          x: 'V0900 als PDF — Version 26, Stand 02.03.2026',
          href: 'drv:V0900',
        },
        {
          k: 'a',
          x: 'V0910 — die offiziellen Erläuterungen der DRV zum Ausfüllen',
          href: 'drv:V0910',
        },
        {
          k: 'b',
          x: 'Offiziell und kostenlos:',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund ist ein privater Dienstleister. Wir sind nicht Teil der Deutschen Rentenversicherung und weder mit ihr noch mit einer anderen Behörde verbunden. Den Antrag stellen Sie direkt bei der Deutschen Rentenversicherung; die Antragstellung dort ist kostenlos.',
      sp: [],
    },
    {
      t: 'p',
      x: 'Sie leben noch in Deutschland, möchten Ihre Beiträge aber nach dem Wegzug zurückfordern?',
      sp: [
        {
          k: 'b',
          x: 'Sie leben noch in Deutschland, möchten Ihre Beiträge aber nach dem Wegzug zurückfordern?',
        },
      ],
    },
    {
      t: 'p',
      x: 'Dann ist V0900 in der Regel nicht Ihr Formular: Für den Antrag aus dem Ausland wird V0901 verwendet. Ob und ab wann eine Erstattung möglich ist, hängt unter anderem von Staatsangehörigkeit, Wohnsitz, Versicherungszeiten und einer Wartefrist von 24 Monaten ab. → Zur englischen V0901-Anleitung — auf Wunsch bereiten wir dort alles für Sie vor; eingereicht wird die Erstattung über unsere deutsche Partnerkanzlei.',
      sp: [
        {
          k: 'a',
          x: 'Zur englischen V0901-Anleitung',
          href: '/v0901-pension-refund-form-english',
        },
        {
          k: 'b',
          x: 'V0901',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Wer kann sich Beiträge erstatten lassen?',
      id: 'wer-kann-sich-beiträge-erstatten-lassen',
    },
    {
      t: 'p',
      x: '1. Dauerhaft versicherungsfreie und befreite Personen (§ 210 Abs. 1a SGB VI). Wer auf Dauer versicherungsfrei ist — Beamtinnen, Beamte und Richter auf Lebenszeit, Berufssoldatinnen und Berufssoldaten — oder dauerhaft von der Versicherungspflicht befreit wurde, etwa als Mitglied eines berufsständischen Versorgungswerks, kann sich früher gezahlte Beiträge erstatten lassen, wenn die allgemeine Wartezeit von fünf Jahren nicht erfüllt ist. Nicht erstattungsberechtigt sind Sie dagegen, solange der Status nur vorläufig ist: als Beamtin oder Richter auf Zeit oder auf Probe, als Soldat auf Zeit, als Beamter auf Widerruf im Vorbereitungsdienst oder bei nur befristeter Befreiung. Auch Versicherungsfreiheit oder Befreiung allein wegen einer geringfügigen Beschäftigung genügt nicht — ein Minijob neben einer qualifizierenden Haupttätigkeit schadet aber nicht. Wichtig: Seit August 2010 dürfen Sie in diesem Status freiwillige Beiträge zahlen — es besteht also eine echte Wahl zwischen Erstattung und freiwilliger Versicherung. Wer aber während der Versicherungsfreiheit oder Befreiung auch nur einen wirksamen freiwilligen Beitrag nach neuem Recht gezahlt hat, verliert damit den Erstattungsanspruch. Sonderfälle — etwa Beurlaubung ohne Dienstbezüge oder Bedienstete internationaler Organisationen — gehören in die Einzelfallprüfung (siehe FAQ).',
      sp: [
        {
          k: 'b',
          x: '1. Dauerhaft versicherungsfreie und befreite Personen (§ 210 Abs. 1a SGB VI).',
        },
        {
          k: 'b',
          x: 'solange',
        },
        {
          k: 'b',
          x: 'neben',
        },
      ],
    },
    {
      t: 'p',
      x: '2. Regelaltersgrenze ohne fünf Jahre Wartezeit (§ 210 Abs. 1 Nr. 2 SGB VI). Wer die Regelaltersgrenze erreicht, aber die Wartezeit nicht erfüllt, erhält keine Regelaltersrente — kann sich die Beiträge aber erstatten lassen. Hier gibt es keine Wartefrist; auch das Recht auf freiwillige Beiträge oder eine noch laufende Pflichtversicherung stehen der Erstattung in diesem Fall nicht entgegen. Prüfen Sie vorher zwei Dinge: Ausländische Versicherungszeiten können über zwischen- und überstaatliches Recht angerechnet werden — dann besteht unter Umständen doch ein Rentenanspruch statt der Erstattung. Und: Möglicherweise können Sie die Wartezeit noch durch weitere freiwillige Beiträge erfüllen; eine Nachzahlung für zurückliegende Monate ist dagegen nur in besonderen gesetzlich geregelten Fällen möglich (§ 282 SGB VI). Lassen Sie sich dazu von der Deutschen Rentenversicherung beraten, bevor Sie sich entscheiden.',
      sp: [
        {
          k: 'b',
          x: '2. Regelaltersgrenze ohne fünf Jahre Wartezeit (§ 210 Abs. 1 Nr. 2 SGB VI).',
        },
      ],
    },
    {
      t: 'p',
      x: '3. Hinterbliebene (§ 210 Abs. 1 Nr. 3 SGB VI). Witwen, Witwer, hinterbliebene eingetragene Lebenspartner und Waisen können sich die Beiträge der verstorbenen Person erstatten lassen, wenn kein Anspruch auf eine Rente wegen Todes besteht, weil deren Versicherungskonto die allgemeine Wartezeit — auch mit Zusammenrechnung ausländischer Zeiten — nicht erfüllt. Es gilt keine Wartefrist, aber die einzige echte Frist des Erstattungsrechts: Der Anspruch erlischt vier Jahre nach Ablauf des Todesjahres. Wer in welcher Reihenfolge anspruchsberechtigt ist und wie aufgeteilt wird, haben wir im Hinterbliebenen-Kapitel unseres Ratgebers erklärt (auf Englisch). → German widow pension',
      sp: [
        {
          k: 'a',
          x: '→ German widow pension',
          href: '/post/german-widow-pension',
        },
        {
          k: 'b',
          x: '3. Hinterbliebene (§ 210 Abs. 1 Nr. 3 SGB VI).',
        },
      ],
    },
    {
      t: 'p',
      x: 'Zählen Sie die fünf Jahre nicht selbst zu knapp: Ein einziger Tag versicherter Beschäftigung in einem Kalendermonat zählt als voller Monat. Angerechnet werden auch Monate mit Arbeitslosengeld, Kindererziehungszeiten (30 Monate pro Kind bei Geburten vor 1992, 36 ab 1992; Feststellung über Antrag V0800) und weitere Zeiten — zum Beispiel Wartezeitmonate aus einem Versorgungsausgleich nach einer Scheidung. Berücksichtigungszeiten bis zum 10. Geburtstag des Kindes zählen dagegen nicht zur fünfjährigen Wartezeit. Maßgeblich sind das geklärte deutsche Versicherungskonto und gegebenenfalls die von ausländischen Versicherungsträgern bestätigten Zeiten — ausländische Zeiten müssen Sie im Antrag angeben. Weniger als 60 deutsche Beitragsmonate bedeuten deshalb nicht automatisch, dass eine Erstattung möglich ist.',
      sp: [
        {
          k: 'b',
          x: 'Zählen Sie die fünf Jahre nicht selbst zu knapp:',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Was wird erstattet — und was nicht?',
      id: 'was-wird-erstattet-und-was-nicht',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Erstattet wird der Arbeitnehmeranteil Ihrer Pflichtbeiträge. Der Arbeitgeberanteil wird nie erstattet.',
          sp: [
            {
              k: 'b',
              x: 'Arbeitnehmeranteil',
            },
          ],
        },
        {
          x: 'Freiwillige Beiträge und Pflichtbeiträge Selbstständiger werden zur Hälfte erstattet — die andere Hälfte wird wie ein Arbeitgeberanteil behandelt.',
          sp: [
            {
              k: 'b',
              x: 'Freiwillige Beiträge',
            },
          ],
        },
        {
          x: 'Beiträge, die vollständig von Dritten getragen wurden — etwa vom Bund oder von einem Leistungsträger während eines Leistungsbezugs —, bringen kein Geld; die Monate zählen aber bei der Wartezeit mit. Selbst getragene Anteile aus solchen Zeiten werden erstattet.',
          sp: [],
        },
        {
          x: 'Beträge aus der Zeit vor 2002 werden aus DM umgerechnet (Kurs 1,95583 DM je Euro). Beiträge im Beitrittsgebiet für Zeiten bis einschließlich 30. Juni 1990 werden nicht erstattet.',
          sp: [],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Was bedeutet die Erstattung für Ihre Rente?',
      id: 'was-bedeutet-die-erstattung-für-ihre-rente',
    },
    {
      t: 'p',
      x: 'Die Beitragserstattung ist eine Alles-oder-nichts-Entscheidung: Erstattet wird immer der gesamte erstattungsfähige Betrag, und mit der Erstattung wird das bisherige Versicherungsverhältnis aufgelöst. Alle bis dahin zurückgelegten Zeiten verlieren ihre Wirkung; wer später wieder einzahlt, beginnt bei null. Ob sich das rechnet, hängt von Ihrer Absicherung außerhalb der gesetzlichen Rentenversicherung ab — bei Beamtinnen und Beamten etwa von der Versorgung. Es gibt Konstellationen, in denen die Erstattung sinnvoll ist, und solche, in denen weitere freiwillige Beiträge — oder in besonderen Fällen eine gesetzlich geregelte Nachzahlung — der bessere Weg zu einer laufenden Rente wären. Die Entscheidung will überlegt sein; die Deutsche Rentenversicherung berät kostenlos.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Welche Angaben und Unterlagen benötigen Sie?',
      id: 'welche-angaben-und-unterlagen-benötigen-sie',
    },
    {
      t: 'p',
      x: 'Für den Antrag (aktuelle Fassung: V0900, Version 26, Stand 02.03.2026 — geprüft am 3. September 2026) sollten Sie bereithalten:',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Ihre Versicherungsnummer (auf Renteninformationen, Gehaltsunterlagen oder DRV-Schreiben),',
          sp: [
            {
              k: 'b',
              x: 'Versicherungsnummer',
            },
          ],
        },
        {
          x: 'Ihre Bankverbindung (IBAN) für die Auszahlung,',
          sp: [
            {
              k: 'b',
              x: 'Bankverbindung (IBAN)',
            },
          ],
        },
        {
          x: 'Ihren Versicherungsverlauf, falls vorhanden,',
          sp: [
            {
              k: 'b',
              x: 'Versicherungsverlauf',
            },
          ],
        },
        {
          x: 'bei Antragstellung durch Vertreter: Vollmacht oder Betreuungsnachweis,',
          sp: [
            {
              k: 'b',
              x: 'Vollmacht',
            },
          ],
        },
        {
          x: 'als Beamtin oder Beamter: das Festsetzungsblatt Ihrer Bezügestelle.',
          sp: [
            {
              k: 'b',
              x: 'Festsetzungsblatt',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'Dazu kommen je nach Fall Angaben zu ausländischen Versicherungszeiten, Kindererziehung, früheren Leistungen der Rentenversicherung und — bei Hinterbliebenen — zur verstorbenen Person. Die offiziellen Erläuterungen zum Formular liefert die DRV in V0910 gleich mit.',
      sp: [
        {
          k: 'b',
          x: 'V0910',
        },
      ],
    },
    {
      t: 'p',
      x: 'V0900 online einreichen? Ja — und die DRV empfiehlt diesen Weg selbst: Der Online-Antrag (eAntrag) führt Sie durch alle Fragen, Sie können Unterlagen hochladen, den Antrag zwischenspeichern und erhalten eine sofortige Eingangsbestätigung. Die DRV veranschlagt etwa 20 Minuten; zum Start genügt die Versicherungsnummer. Alternativ senden Sie das unterschriebene PDF per Post an Ihren Rentenversicherungsträger.',
      sp: [
        {
          k: 'b',
          x: 'V0900 online einreichen?',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Häufige Fehler — sie verzögern oder verhindern die Erstattung',
      id: 'häufige-fehler-sie-verzögern-oder-verhindern-die',
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Im falschen Status beantragt. Solange Sie auf Zeit, auf Probe oder auf Widerruf verbeamtet (oder Soldat auf Zeit) sind oder nur befristet befreit, ist die Erstattung nach § 210 Abs. 1a unzulässig — sie kommt erst mit dem dauerhaften Status in Betracht.',
          sp: [
            {
              k: 'b',
              x: 'Im falschen Status beantragt.',
            },
          ],
        },
        {
          x: 'Lücken einfach hingenommen. Fehlende Zeiten können Sie direkt im V0900 angeben und mit Unterlagen belegen. Erst wenn das Versicherungskonto umfassend ungeklärt ist, lohnt vor dem Antrag eine Kontenklärung (Formular V0100).',
          sp: [
            {
              k: 'b',
              x: 'Lücken einfach hingenommen.',
            },
          ],
        },
        {
          x: 'Die fünf Jahre falsch gezählt. Siehe oben: angerechnete Monate (Arbeitslosengeld, Kindererziehung, Versorgungsausgleich) und ausländische Zeiten verändern das Ergebnis in beide Richtungen.',
          sp: [
            {
              k: 'b',
              x: 'Die fünf Jahre falsch gezählt.',
            },
          ],
        },
        {
          x: 'Die Freiwilligen-Beitrags-Falle. Ein einziger wirksamer freiwilliger Beitrag, gezahlt während der dauerhaften Versicherungsfreiheit oder Befreiung, lässt den Erstattungsanspruch nach § 210 Abs. 1a entfallen.',
          sp: [
            {
              k: 'b',
              x: 'Die Freiwilligen-Beitrags-Falle.',
            },
          ],
        },
        {
          x: 'Die Reha-Falle übersehen. Hat die Rentenversicherung früher eine Leistung finanziert — etwa eine medizinische oder berufliche Rehabilitation (auch wenn sie nach Krankenkasse aussah) — oder eine Erwerbsminderungsrente gezahlt, sind nur die danach gezahlten Beiträge erstattungsfähig; die Erstattung löscht trotzdem den gesamten Anspruch. Klären Sie vor dem Antrag, wer eine frühere Reha bezahlt hat.',
          sp: [
            {
              k: 'b',
              x: 'Die Reha-Falle übersehen.',
            },
          ],
        },
        {
          x: 'Die Tragweite unterschätzt. Die Erstattung löscht alle Zeiten endgültig. Vergleichen Sie vorher die Alternative weiterer freiwilliger Beiträge — und lassen Sie sich von der DRV beraten.',
          sp: [
            {
              k: 'b',
              x: 'Die Tragweite unterschätzt.',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'Offizieller Download',
      id: 'offizieller-download',
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Online-Antrag (eAntrag) der Deutschen Rentenversicherung — empfohlen: → Online-Antrag der DRV',
          sp: [
            {
              k: 'a',
              x: '→ Online-Antrag der DRV',
              href: 'eantrag:',
            },
            {
              k: 'b',
              x: 'Online-Antrag (eAntrag)',
            },
          ],
        },
        {
          x: 'V0900 — Antrag auf Beitragserstattung bei Aufenthalt im Inland (PDF; Version 26, Stand 02.03.2026): → DRV-Formularseite',
          sp: [
            {
              k: 'a',
              x: '→ DRV-Formularseite',
              href: 'drv:V0900',
            },
            {
              k: 'b',
              x: 'V0900 — Antrag auf Beitragserstattung bei Aufenthalt im Inland',
            },
          ],
        },
        {
          x: 'V0910 — Erläuterungen zum Antrag auf Beitragserstattung (Stand 02.03.2026): → DRV-Formularseite',
          sp: [
            {
              k: 'a',
              x: '→ DRV-Formularseite',
              href: 'drv:V0910',
            },
            {
              k: 'b',
              x: 'V0910 — Erläuterungen zum Antrag auf Beitragserstattung',
            },
          ],
        },
        {
          x: 'V0100 — Antrag auf Kontenklärung (Version 21, Stand 02.03.2026): → DRV-Formularseite',
          sp: [
            {
              k: 'a',
              x: '→ DRV-Formularseite',
              href: 'drv:V0100',
            },
            {
              k: 'b',
              x: 'V0100 — Antrag auf Kontenklärung',
            },
          ],
        },
        {
          x: 'V0800 — Antrag auf Feststellung von Kindererziehungszeiten / Berücksichtigungszeiten wegen Kindererziehung (Stand 29.04.2026): → DRV-Formularseite',
          sp: [
            {
              k: 'a',
              x: '→ DRV-Formularseite',
              href: 'drv:V0800',
            },
            {
              k: 'b',
              x: 'V0800 — Antrag auf Feststellung von Kindererziehungszeiten / Berücksichtigungszeiten wegen Kindererziehung',
            },
          ],
        },
      ],
    },
    {
      t: 'faq',
    },
    {
      t: 'src',
      x: 'Quellen: DRV-Formular V0900 (Version 26, Stand 02.03.2026) und Erläuterungen V0910 · DRV Online-Antrag (eAntrag) · DRV-Formulare V0100 und V0800 · § 210 SGB VI · § 282 SGB VI (GRA) · § 3 Nr. 3b EStG.',
      sp: [
        {
          k: 'b',
          x: 'Quellen:',
        },
      ],
    },
  ],
  faqTitle: 'FAQ',
  faq: [
    {
      q: 'Bekomme ich auch die Arbeitgeberanteile zurück?',
      a: 'Nein. Erstattet wird der Arbeitnehmeranteil; freiwillige Beiträge und Pflichtbeiträge Selbstständiger werden zur Hälfte erstattet. Arbeitgeberanteile werden nie erstattet.',
      inSchema: true,
    },
    {
      q: 'Ist die Erstattung steuerpflichtig?',
      a: 'Die Erstattung wird ohne Abzug deutscher Steuern ausgezahlt; das deutsche Recht stellt Beitragserstattungen steuerfrei (§ 3 Nr. 3b EStG). Bei Wohnsitz im Ausland kann die dortige Behandlung abweichen. Das ist eine allgemeine Information, keine individuelle Steuerberatung.',
      inSchema: true,
    },
    {
      q: 'Ich habe die Regelaltersgrenze erreicht — muss ich eine Wartefrist einhalten?',
      a: 'Nein. Bei der Erstattung wegen nicht erfüllter Wartezeit an der Regelaltersgrenze gibt es keine Wartefrist; auch ein Recht auf freiwillige Beiträge oder eine noch laufende Pflichtversicherung stehen in diesem Fall nicht entgegen. Prüfen Sie aber zuerst, ob Sie die Wartezeit noch erfüllen können.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'Nein. Bei der Erstattung wegen nicht erfüllter Wartezeit an der Regelaltersgrenze gibt es keine Wartefrist; auch ein Recht auf freiwillige Beiträge oder eine noch laufende Pflichtversicherung stehen in diesem Fall nicht entgegen. Prüfen Sie aber zuerst, ob Sie die Wartezeit noch erfüllen können — siehe oben.',
          sp: [],
        },
      ],
    },
    {
      q: 'Ich arbeite bei einer internationalen Organisation in Deutschland — gilt das als befreit?',
      a: 'Wer aufgrund eines Sitzstaatsabkommens von der deutschen Versicherungspflicht befreit ist — typisch bei internationalen Organisationen mit Sitz in Deutschland —, kann grundsätzlich nach § 210 Abs. 1a erstattungsberechtigt sein, wenn die Wartezeit (auch unter Anrechnung besonderer Zeiten) nicht erfüllt ist. Die Details sind ein Fall für die Einzelfallprüfung bei der DRV.',
      inSchema: true,
    },
    {
      q: 'Kann ich nach einer Erstattung später wieder einzahlen?',
      a: 'Ja — wenn später erneut Versicherungspflicht eintritt oder Sie zur freiwilligen Versicherung berechtigt sind. Die durch die Erstattung untergegangenen Zeiten leben jedoch nicht wieder auf; das Konto beginnt bei null.',
      inSchema: true,
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Zur englischen V0901-Anleitung →',
      href: '/v0901-pension-refund-form-english',
    },
    {
      label: 'Alle Formulare',
      href: '/download',
    },
  ],
  source:
    'GPR_FormsPage_V0900_DE_v1.1_2026-09-03.md (live slug /v0900-formular)',
};

export default page;
