// Generated by scripts/build-guides.mjs from GPR_FormsPage_V0901_EN_v1.1_2026-08-31.md.
// Do not edit copy here — regenerate from the handoff.
import type { ArticleData } from '../articles/types';

const page: ArticleData = {
  path: '/v0901-pension-refund-form-english',
  kind: 'guide',
  lang: 'en',
  title:
    'V0901 Form in English: German Pension Refund Application Guide (2026)',
  meta: 'V0901 is the official German pension refund application from abroad. Section-by-section English walkthrough, A1310 — and the mistakes that delay refunds.',
  h1: 'Form V0901: Your German Pension Refund Application, Explained in English',
  headline: 'V0901 Form in English: German Pension Refund Application Guide',
  eyebrow: 'Form guide · V0901',
  rail: 'Form guide',
  crumbs: [
    {
      label: 'Home',
      href: '/',
    },
    {
      label: 'Forms & guides',
      href: '/download',
    },
    {
      label: 'V0901',
    },
  ],
  reviewLine: 'Last checked: 31 August 2026',
  showReviewer: true,
  datePublished: '2026-09-02',
  dateModified: '2026-09-10',
  imageUrl:
    'https://static.wixstatic.com/media/da88a8_eeadb28f689f4702b5a53c1ff8bab97d~mv2.png',
  blocks: [
    {
      t: 'p',
      x: 'The short answer: Form V0901 („Antrag auf Beitragserstattung bei Aufenthalt im Ausland" — application for a contribution refund while living abroad) is the official Deutsche Rentenversicherung (DRV) application for having your German pension contributions refunded after you have left Germany. The official PDF is free, and DRV publishes it in several bilingual editions — including German/English (download below). Most applicants also need form A1310, the payment declaration that lets DRV transfer the refund to a bank account outside Germany. You can file both yourself — this guide walks you through every section — or have us prepare everything, with the filing handled by our German partner law firm.',
      sp: [
        {
          k: 'b',
          x: 'The short answer:',
        },
        {
          k: 'b',
          x: 'A1310',
        },
      ],
    },
    {
      t: 'quote',
      x: 'Germany Pension Refund is a private service. We are not part of or affiliated with Deutsche Rentenversicherung or any German government authority. You may apply directly to Deutsche Rentenversicherung without using our service; the pension office charges no application fee.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Who applies with V0901?',
      id: 'who-applies-with-v0901',
    },
    {
      t: 'p',
      x: 'You use V0901 if you live outside Germany and want your contributions back. Before retirement age, three conditions must hold for most applicants:',
      sp: [],
    },
    {
      t: 'ul',
      items: [
        {
          x: 'Citizenship: you are not a citizen of Germany, an EU or EEA country, Switzerland or the UK. Every citizenship you hold counts — one blocking passport blocks, even if you never use it.',
          sp: [
            {
              k: 'b',
              x: 'Citizenship:',
            },
          ],
        },
        {
          x: 'Residence: you live outside the EU and the UK. Norway, Iceland, Liechtenstein and Switzerland are fine as countries of residence.',
          sp: [
            {
              k: 'b',
              x: 'Residence:',
            },
          ],
        },
        {
          x: 'Waiting period: at least 24 full calendar months have passed since your last mandatory pension insurance in Germany, the EU, the UK, Türkiye, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia or Serbia. New mandatory insurance in any of these restarts the clock from its end. You can apply from the 1st of the 25th month.',
          sp: [
            {
              k: 'b',
              x: 'Waiting period:',
            },
          ],
        },
      ],
    },
    {
      t: 'p',
      x: 'The 60-month rule. One further limit applies only to citizens of the USA, India, Canada, Australia, Brazil, South Korea, the Philippines, Albania, Moldova, North Macedonia and Uruguay — and to Japanese citizens living in Japan, as well as refugees and stateless persons living there: a refund is possible only with fewer than 60 German contribution months. From 60 months, your contributions instead secure a German pension paid at retirement age. No other citizenship has a contribution limit.',
      sp: [
        {
          k: 'b',
          x: 'The 60-month rule.',
        },
      ],
    },
    {
      t: 'p',
      x: 'Special rules exist for some situations — living in India or Israel, citizens of Bosnia and Herzegovina, Kosovo, Montenegro and Serbia, and people who have reached German retirement age with fewer than five years of contributions (they can apply without the 24-month wait). Our free eligibility checker gives you a preliminary indication of whether the standard rules appear to fit your case; it is not an individual legal decision, and edge cases get individual review — the complete country rules are in our full guide. Check your eligibility · full guide',
      sp: [
        {
          k: 'a',
          x: 'Check your eligibility',
          href: '/refund-calculator',
        },
        {
          k: 'a',
          x: 'full guide',
          href: '/post/how-to-get-a-german-pension-refund',
        },
      ],
    },
    {
      t: 'p',
      x: 'Still living in Germany? Then V0901 is the wrong form. The domestic application is V0900 — common for civil servants, judges and people reaching retirement age with short contribution histories. → V0900-Formular erklärt (Deutsch)',
      sp: [
        {
          k: 'a',
          x: '→ V0900-Formular erklärt (Deutsch)',
          href: '/v0900-formular',
        },
        {
          k: 'b',
          x: 'Still living in Germany?',
        },
        {
          k: 'b',
          x: 'V0900',
        },
      ],
    },
    {
      t: 'h2',
      x: 'Where does the completed form go?',
      id: 'where-does-the-completed-form-go',
    },
    {
      t: 'p',
      x: 'Not always to the office you expect: which DRV carrier decides your claim follows from your insurance history, citizenship and country of residence — and the account carrier and the deciding office can differ. A wrongly addressed application is forwarded with its filing date preserved, but the transit costs weeks. Our routing guide — with the office finder embedded — explains the precedence rules and identifies the recommended first office for your case. → Which German pension office handles your claim',
      sp: [
        {
          k: 'a',
          x: '→ Which German pension office handles your claim',
          href: '/post/which-german-pension-office-handles-your-claim',
        },
      ],
    },
    {
      t: 'p',
      x: 'One more route note for self-filers: DRV does not accept refund applications by ordinary email, because email cannot establish your identity. From abroad, a do-it-yourself application generally goes on paper, by post.',
      sp: [],
    },
    {
      t: 'h2',
      x: 'Completing V0901, section by section',
      id: 'completing-v0901-section-by-section',
    },
    {
      t: 'p',
      x: 'The current form is V0901, Version 21 (Stand 28.11.2023) — checked 27 August 2026. It is a fillable PDF, and most of it is easier than it looks. Work through it in this order:',
      sp: [],
    },
    {
      t: 'p',
      x: 'Before you start. Download the German/English edition of V0901 and — for the payout — the German/English payment declaration A1310 (Version 8, Stand 01.07.2026; DRV asks for it to be printed double-sided). Have your passport, proof of your residence abroad and any German insurance papers you still hold within reach.',
      sp: [
        {
          k: 'b',
          x: 'Before you start.',
        },
        {
          k: 'b',
          x: 'A1310',
        },
      ],
    },
    {
      t: 'p',
      x: "Your personal data (Ziffern 2–3 of the form). Names — including any former names — date of birth, and your contact address abroad. Precision here matters twice: DRV's queries and the decision go to this address, and these are exactly the details an official body later certifies on page 13.",
      sp: [
        {
          k: 'b',
          x: 'Your personal data (Ziffern 2–3 of the form).',
        },
      ],
    },
    {
      t: 'p',
      x: 'Your German insurance number (Versicherungsnummer). You find it on old payslips, your Sozialversicherungsausweis or any DRV letter. Lost it? A claim can still be filed using other identifiers, such as your full name, date of birth and last registered address in Germany — and we can help identify or recover a missing number. → German social security number',
      sp: [
        {
          k: 'a',
          x: '→ German social security number',
          href: '/post/german-social-security-number',
        },
        {
          k: 'b',
          x: 'Your German insurance number (Versicherungsnummer).',
        },
      ],
    },
    {
      t: 'p',
      x: "Nationality and residence. State your citizenship and current country of residence — and be complete: every citizenship you hold counts for eligibility, and EU and UK insurance records are digitally connected to Germany's, so gaps in the story surface.",
      sp: [
        {
          k: 'b',
          x: 'Nationality and residence.',
        },
      ],
    },
    {
      t: 'p',
      x: "Your insurance history. List your German employment and contribution periods as well as you can reconstruct them. Estimates are allowed where papers are gone — the official account decides in the end. But if what you remember and what DRV's account shows don't match, clear the account first (Kontenklärung, form V0100) rather than letting the refund application stall on open questions. Periods you did not work can still count toward the 60-month line — months on unemployment benefit, for example, or child-raising periods.",
      sp: [
        {
          k: 'b',
          x: 'Your insurance history.',
        },
      ],
    },
    {
      t: 'p',
      x: 'Marriage and name changes. Where applicable, DRV asks for documentation — this is how contribution records filed under a former name are matched to you.',
      sp: [
        {
          k: 'b',
          x: 'Marriage and name changes.',
        },
      ],
    },
    {
      t: 'p',
      x: "The certification block (page 13). V0901 needs no separate identity form: the personal data from Ziffern 2–3 is certified on the application itself, by an official body. The form's own list of accepting bodies is broad — authorities of your country of residence, pension insurance carriers, notaries, banks, hospitals, the Red Cross and, exceptionally, German embassies and consulates. The practical consequence: fill in everything else first, because your application travels to the certifying body before it travels to Germany.",
      sp: [
        {
          k: 'b',
          x: 'The certification block (page 13).',
        },
      ],
    },
    {
      t: 'p',
      x: "The payment declaration (A1310). V0901 asks for payment details in Section 11 — but in the refund cases we see, DRV generally still requires the separate, signed A1310 as the payment declaration for the payout, so send it with the application. Your bank details — IBAN/SWIFT or the local format — go on the A1310, which covers every country except Italy (Italy uses A1311); it also records who may use the account, with the form's own restrictions for US, Canadian and third-party accounts — see our A1310 guide, section by section. A third-party account can be used where the required account-holder declaration and compliance checks are satisfied. A German bank account is not required.",
      sp: [
        {
          k: 'a',
          x: 'our A1310 guide, section by section',
          href: '/a1310-payment-declaration',
        },
        {
          k: 'b',
          x: 'The payment declaration (A1310).',
        },
      ],
    },
    {
      t: 'p',
      x: 'Sign, copy, send. Sign and date both forms, keep complete copies together with the send date, and post the application on paper to the recommended office (see above).',
      sp: [
        {
          k: 'b',
          x: 'Sign, copy, send.',
        },
      ],
    },
    {
      t: 'h2',
      x: 'The five mistakes that delay — or prevent — refunds',
      id: 'the-five-mistakes-that-delay-or-prevent',
    },
    {
      t: 'ol',
      items: [
        {
          x: 'Applying too early. The conditions are checked on the application date; an application filed before the 24-month waiting period has passed is rejected and can trigger extra confirmation demands. waiting-period calculator',
          sp: [
            {
              k: 'a',
              x: 'waiting-period calculator',
              href: '/refund-calculator',
            },
            {
              k: 'b',
              x: 'Applying too early.',
            },
          ],
        },
        {
          x: "A missing or incomplete payment declaration. In the refund cases we see, DRV generally does not release a refund to an account outside Germany without a usable, signed A1310 — the form's account-holder options and their US, Canadian and EU restrictions are explained in our A1310 guide.",
          sp: [
            {
              k: 'a',
              x: 'our A1310 guide',
              href: '/a1310-payment-declaration',
            },
            {
              k: 'b',
              x: 'A missing or incomplete payment declaration.',
            },
          ],
        },
        {
          x: "Gaps in your record. If your remembered employment and the DRV account don't match, clarify the account first (Kontenklärung, form V0100), so the refund application doesn't stall on open questions.",
          sp: [
            {
              k: 'b',
              x: 'Gaps in your record.',
            },
          ],
        },
        {
          x: 'Filing by email. Ordinary email is not an accepted filing route for identity reasons — see the route note above.',
          sp: [
            {
              k: 'b',
              x: 'Filing by email.',
            },
          ],
        },
        {
          x: "An outdated mailing address. Queries and the decision go to the address on file; if letters can't reach you, deadlines can pass unnoticed.",
          sp: [
            {
              k: 'b',
              x: 'An outdated mailing address.',
            },
          ],
        },
      ],
    },
    {
      t: 'h2',
      x: 'File it yourself — or have it handled',
      id: 'file-it-yourself-or-have-it-handled',
    },
    {
      t: 'p',
      x: 'Everything above is doable on your own: the official forms are free, and this guide plus the official links below are all you need.',
      sp: [],
    },
    {
      t: 'p',
      x: "If you would rather not manage a German administrative procedure from abroad, our managed service takes it over: we check your eligibility before anything is filed and prepare the application and payment documents from the information and evidence you provide; our German partner law firm files the claim with the recommended pension office, and the German correspondence is handled within the agreed scope — until your refund is paid out through the law firm's escrow account. After the refund reaches escrow, the agreed fee is deducted and the balance is transferred to the account you nominate. Fully digital in most cases. And when DRV Oldenburg-Bremen is the office responsible for your refund, we prepare the power of attorney and payment declaration and ask you to send us the signed originals — a limited exception rather than the rule. The process is designed to avoid preventable delays (see the full data and methodology: /german-pension-refund-processing-time) — the five mistakes above are exactly what we screen for.",
      sp: [],
    },
    {
      t: 'p',
      x: 'The fee: Our fee is 9.75% of the refunded amount, capped at €2,500 including VAT, with no upfront payment and no minimum fee. No refund, no fee. details',
      sp: [
        {
          k: 'a',
          x: 'details',
          href: '/pricing',
        },
        {
          k: 'b',
          x: 'The fee:',
        },
      ],
    },
    {
      t: 'note',
      x: 'Check your eligibility now',
      sp: [
        {
          k: 'a',
          x: 'Check your eligibility now',
          href: '/refund-calculator',
        },
      ],
    },
    {
      t: 'faq',
    },
    {
      t: 'downloads',
      forms: ['V0901', 'A1310'],
    },
    {
      t: 'src',
      x: 'Sources: DRV form V0901, bilingual German/English edition (Version 21, Stand 28.11.2023) · DRV form A1310, German/English edition (Version 8, Stand 01.07.2026) · DRV form V0100 (Kontenklärung) · § 210 SGB VI · our routing guide, processing-time data page and refund calculator.',
      sp: [
        {
          k: 'b',
          x: 'Sources:',
        },
      ],
    },
  ],
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Can I download V0901 in English?',
      a: 'Yes. DRV publishes the official PDF in bilingual editions, including German/English — one document carries both languages, so you read English while DRV receives its German form. The download is free.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'Yes. DRV publishes the official PDF in bilingual editions, including German/English — one document carries both languages, so you read English while DRV receives its German form. The download is free. → Official DRV form page',
          sp: [
            {
              k: 'a',
              x: '→ Official DRV form page',
              href: 'drv:V0901:de-en',
            },
          ],
        },
      ],
    },
    {
      q: 'Do I need form A1310?',
      a: 'In practice, almost always — yes. V0901 asks for payment details in Section 11, but in the refund cases we see, DRV generally still requires the separate, signed A1310 as the payment declaration for the payout. A1310 covers every country except Italy (A1311). A German bank account is not required.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'In practice, almost always — yes. V0901 asks for payment details in Section 11, but in the refund cases we see, DRV generally still requires the separate, signed A1310 as the payment declaration for the payout. A1310 covers every country except Italy (A1311). A German bank account is not required. Section-by-section guide: Form A1310 explained in English.',
          sp: [
            {
              k: 'a',
              x: 'Form A1310 explained in English',
              href: '/a1310-payment-declaration',
            },
          ],
        },
      ],
    },
    {
      q: 'How long does the refund take?',
      a: 'Processing time depends on the responsible pension office, and we cannot guarantee a decision or payment date. For measured results, see the full data and methodology on our processing-time page — we publish the current figures there rather than repeating them across the site.',
      inSchema: true,
      blocks: [
        {
          t: 'p',
          x: 'Processing time depends on the responsible pension office, and we cannot guarantee a decision or payment date. For measured results, see the full data and methodology on our processing-time page — we publish the current figures there rather than repeating them across the site. → Processing Times & Data',
          sp: [
            {
              k: 'a',
              x: '→ Processing Times & Data',
              href: '/german-pension-refund-processing-time',
            },
          ],
        },
      ],
    },
    {
      q: 'Can I apply while visiting Germany?',
      a: 'The conditions are checked on the application date, and the refund requires that you live outside the EU and the UK. A short visit is not the same as moving back — but if you have moved back to Germany, the residence condition is no longer met until you live abroad again.',
      inSchema: true,
    },
  ],
  faqInSchema: true,
  cta: [
    {
      label: 'Check your eligibility — free →',
      href: '/refund-calculator',
    },
    {
      label: 'Start my claim',
      href: '/get-your-refund',
    },
  ],
  source:
    'GPR_FormsPage_V0901_EN_v1.1_2026-08-31.md + A1310 change guide pairs A1–A4 (8 Sep 2026)',
};

export default page;
